---
title: "HW3"
subtitle: STAT561 Fall 2018
author: 'Shen Qu'
date: "10/18/2018"
output: html_document
---

**1 .48**Prove the necessity part of Theorem 1.5.3.

Theorem 1.5.3 The junction F{x) is a cdf if and only if the following three conditions hold:

a. $\lim_{x\to-\infty}F(x)=0\ \& \lim_{x\to\infty}F(x)=1$;  
b. F is non-decreasing; and   
c. F is right-continuous; that is, for every number x0, $\lim_{x\to\infty}F(x)=F(x_0)$

-Proof c.

let $C_1,C_2$,...be a sequance of events such that $C1\subset C_2\subset$... 

let $A_1=C_1$ and for $n\ge2,\ A_n=C_n\setminus C_{n-1}$, then
$$\bigcup_{i=1}^\infty A_i=\bigcup_{i=1}^\infty C_i$$

$$P[\lim_{n\to\infty}C_n]=P[\lim_{n\to\infty}\bigcup_{i=1}^nC_i]=P[\bigcup_{i=1}^{\infty}C_i]=P[\bigcup_{i=1}^{\infty}A_i]=\sum_{i=1}^{\infty}P(A_i)=\lim_{n\to\infty}\sum_{i=1}^nP(A_i)$$

$$=\lim_{n\to\infty}\Big[P(A_1)+\sum_{i=2}^nP(A_i)\Big]=\lim_{n\to\infty}\Bigg[P(C_1)+\sum_{i=2}^n\Big[P(C_i)-P(C_i\cap C_{i-1})\Big]\Bigg]$$

$$=\lim_{n\to\infty}\Bigg[P(C_1)+\sum_{i=2}^n\Big[P(C_i)-P(C_{i-1})\Big]\Bigg]=\lim_{n\to\infty}P(C_n)$$

$$So\quad P(\lim_{n\to\infty}C_n)=\lim_{n\to\infty}P(C_n)$$

Now let $B_1,B_2$,...be a sequance of events such that $B1\supset B_2\supset$... 

$$Then\ B_1^c\subset B_2^c\subset...$$

$$So\quad P(\lim_{n\to\infty}B_n^c)=\lim_{n\to\infty}P(B_n^c)$$

$$left\quad P(\lim_{n\to\infty}B_n^c)=P\left(\lim_{n\to\infty}\bigcup_{i=1}^nB_i^c\right)=P\left(\bigcup_{i=1}^{\infty}B_i^c\right)=P\left({\bigcap_{i=1}^{\infty}B_i}^c\right)$$

$$=1-P\left(\bigcap_{i=1}^{\infty}B_i\right)=1-P\left(\lim_{n\to\infty}\bigcap_{i=1}^nB_i\right)=1-P\left(\lim_{n\to\infty}B_n\right)\quad $$

$$right\quad \lim_{n\to\infty}P(B_n^c)=\lim_{n\to\infty}(1-P(B_n))=1-\lim_{n\to\infty}P(B_n)$$

$$So\quad \lim_{n\to\infty}P(B_n)=P(\lim_{n\to\infty}B_n)$$

let $B_n=(-\infty,\ x+\frac1n]$, n=1,2,3,...
Note: $B_i\supset B_2\supset$...

$$\lim_{n\to\infty}B_n=(-\infty,\ x]$$

$$P\left(\lim_{n\to\infty}B_n\right)=P\left((-\infty,\ x]\right)=F_X(x)$$

$$left\quad \lim_{n\to\infty}P(B_n)=\lim_{n\to\infty}P\left((-\infty,\ x+\frac1n]\right)=\lim_{n\to\infty}F_X(x+\frac1n)$$

$$\therefore \lim_{n\to\infty}F_X(x+\frac1n)=F_X(x)$$


**2.2** In each of the following find the pdf of Y.
(a) $Y=X^2\quad and\quad f_X(x)=1, 0<x<1$

$$F_Y(y)=P(Y\le y)=P(X^2\le y)=P(-\sqrt y\le X\le\sqrt y)=P(X\le\sqrt y)-P(X\le-\sqrt y)$$

$$\because f_X(x)=1, 0<x<1,\quad X\le 0\ is\ \emptyset\quad \therefore P(X\le-\sqrt y)=0,\quad F_X(x)=\int f_X(x)=\int1=x $$

$$F_Y(y)=P(X\le\sqrt y)=F_X(\sqrt y)=\sqrt y,\ 0<\sqrt y<1$$

$$f_Y(y)=\frac{dF_Y(y)}{dy}=\frac{d\sqrt y}{dy}=\frac1{2\sqrt y},\quad 0<y<1$$

(b) $Y=-\log X$ and X has pdf

$$f_X(x)=\frac{(n+m+1)!}{n!m!}x^n(1-x)^m,\quad 0<x<1,\quad
n,m\ positive\ integers$$

 > $Y=-\log X$ is a monotone decreasing function, thus we can use shortcut.

$$\because Y=-\log X,\quad \therefore X=e^{-Y}$$

$$f_Y(y)=f_X(x)|\frac{dx}{dy}|=\frac{(n+m+1)!}{n!m!}(e^{-y})^n(1-e^{-y})^m|\frac{d(e^{-y})}{dy}|=\frac{(n+m+1)!}{n!m!}e^{-ny-y}(1-e^{-y})^m,\ 0<y<\infty$$

(c) $Y=e^X$ and X has pdf

$$fx(x)=\frac1{\sigma^2}xe^{-(x/\sigma)^2/2},\quad 0<x<\infty,\quad\sigma^2\ a\ positive\ constant$$

 > $Y=e^X$ is a monotone increasing function, thus we can use shortcut.

$$\because Y=e^X,\quad \therefore X=\ln Y$$

$$f_Y(y)=f_X(x)|\frac{dx}{dy}|=\frac1{\sigma^2}xe^\frac{-(\frac x\sigma)^2}2|\frac{d(\ln y)}{dy}|=\frac{\ln (y)}{\sigma^2y}e^\frac{-(\frac{\ln y}\sigma)^2}2$$

**2.12** A random right triangle can be constructed in the following manner. Let X be a random angle whose distribution is uniform on $(0, \pi/2)$. For each X, construct a triangle as pictured below. Here, Y = height of the random triangle. For a fixed constant d, find the distribution of Y and EY.



**2.17** A median of a distribution is a value m such that $P(X\lem)\ge\frac12\ and\ P(X\gem)\ge\frac12$. (If X i s continuous, m satisfies $\int_{-\infty}^mf(x)dx=\int_m^\infty f(x)dx=\frac12$.) Find the median of the following distributions.

(a) $f(x)=3x^2,\quad 0<X<1$  

(b) $f(x)=\frac1{\pi(1+x^2)},\quad-\infty<X<\infty$

