---
title: "Probability Theory 3-6"
subtitle: "STAT 561 Week 2,3"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
     toc: true
     css: "ninjutsu.css"
     seal: yes
     nature:
      highlightStyle: github

---

## {.tabset .tabset-fade .tabset-pills}

### 1.3 Conditional Probability  

`2018.10.2`

#### 1. Conditional Probability
Definition 1.3.2  

> $P(A|B)=\frac{P(A\cap B)}{P(B)}$, provided P(B)>0

#### 2. Is this a vaild probability function?  

 > (1) $\forall A, is P(A|B)\ge0$ yes
   (2) $P(S|B)=\frac{P(S\cap B)}{P(B)}=\frac{P(B)}{P(B)}=1$ yes
   (3) Suppose $A_1\cap A_2=\emptyset$ 

$$P(A_1\cup A_2|B)=\frac{P[(A_1\cup A_2)\cap B]}{P(B)}=\frac{P[(A_1\cap B)\cup (A_2\cap B)]}{P(B)}=\frac{P[(A_1\cap B)+P(A_2\cap B)]}{P(B)}=P(A_1|B)+P(A_2|B)$$

#### 3. statistically independent
Definition 1.3.7

The events A and B are independent, if $P(A\cap B)=P(A)P(B)$

Note: Suppose P(B)>0 and that A and B are independent, then

$$P(A|B)=\frac{P(A\cap B)}{P(B)}=\frac{P(A)P(B)}{P(B)}=P(A)$$

#### 4. Example Roll 2 dice

$$S=\begin{Bmatrix}
11 & 12 & \cdots & 16 \\ 
21 & 22 & \cdots & 26 \\ 
\vdots & \vdots & \vdots & \vdots \\
61 & 62 & \cdots & 66 \end{Bmatrix}$$

let A be the event that the 1st dice=6; B....=6. 

$$P(A)=\frac6{36},\quad P(B)=\frac6{36},\quad P(A\cap B)=\frac1{36}$$

Since $\frac1{36}=\frac16\frac16$, A adn B are independent.

#### 5. Example Draw 2 cards

Draw 2 cards from a deck of 52 without replacement.   

let A: 1st card is an ace; 
    B: 2nd...

$$P(A\cap B)=\frac{4\times 3}{52\times 51}=\frac1{13\times 17}\ne\frac1{13}\frac1{13}$$
$$P(A)=\frac{4\times 51}{52\times 51}=\frac4{52}=\frac1{13}$$
$$P(B)=\frac{4\times 3+48\times 4}{52\times 51}=\frac4{52}=\frac1{13}$$
Therefore A and B are dependent

#### 6. (recall 1.2.2)

According to the Law of Total Probability  
Theorem 1.2.11 (a).  
$$P(A)=\sum_{i=1}^\infty{P(C_i)}P(A|C_i)$$

#### 7. Bayes' Rule
Theorem 1.3.5
Select a particular index K where $P(C_k)\ne0$

$$P(C_k|A)=\frac{P(C_k\cap A)}{P(A)}=\frac{P(C_k)P(A|C_k) }{\sum_{i=1}^\infty{P(C_i)}P(A|C_i)}$$

#### 8-11. Example

If the person does not hase the substance, the test results will be negative 96% of the time.

$$P(B^c|A^c)=0.96$$

Question: Given that the test results are positive, what is the prabability that the person uses the substance?

let A: person uses substances
    B: test result is positive

Assume: 1 in 20 persons use the substance P(A)=0.05

If the person uses the substance, the test results will be positive 99% of the time. P(B|A)=0.99
<picture>

How does this use Bayes's Rule?

$$P(B|A)=\frac{P(B|A)P(A)}{P(B|A)P(A)+P(B|A^c)P(A^c)}=\frac{0.05\times 0.99}{0.05\times0.99+0.95\times0.04}=0.566 $$

`2018.10.4`

#### 1.2. Two sons problem

Assume P(M)=P(F)=0.5; Assume independent births

You see a person with one of their children, a son. You know that they have 2 children. Find the probability that their other child is a son.

Let A: 1st child is M; B: 2nd child is M, Find

$$P(A\cap B|A\cup B)=\frac{P[(A\cup B)\cap(A\cup B)]}{P(A\cup B)}=\frac{P(A\cap B)}{P(A\cup B)}=\frac{\frac14}{\frac34}=\frac13$$

#### 3. Monty Hall problem

You choose door #1. Monty Hall opens one of the 2 remaining doors to reveal a joke prize. He them gives you the chance to swith your choose. Should you?

Swich $\implies P(w)=\frac23$


### 1.4 Random variable  

#### 4. Random variable
Definition 1.4.1

> A random variable is a function from the sample space into the set of real numbers

$$X:S\to \mathbb{R}$$

> The range of the random variable X is the set of real numbers that X maps onto

#### 5.Example: Flip 2 coins

S={HH, HT, TH, TT}

let X be the # of heads

X(HH)=2, X(HTH)=1, X(TH)=1, X(TT)=0. range of X is {0,1,2}


#### 6. Definitions

Definition 1.5.7

> If the range of X is countable (finite or countable infinite), then X is a **discrete random variable**.

Definition 1.5.8

> If the range of X is an interval, then X is a **continuous random variable**.

Definition of induced **probability function**

> let A be a subset of the range of X.

$$P_x(A)=P[\{s\in S: X(s)\in A\}]$$

#### 7.Example: Roll 2 coins

$$S=\begin{Bmatrix}
11 & 12 & \cdots & 16 \\ 
21 & 22 & \cdots & 26 \\ 
\vdots & \vdots & \vdots & \vdots \\
61 & 62 & \cdots & 66 \end{Bmatrix}$$

Let X be the maximum of the 2 dice
Find the probability that x=5

$$P_x(\{5\})=P\big[\{15,25,35,45,51,52,53,54,55\}\big]=\frac9{36}=\frac14$$

### 1.5 Distribution Functions

#### 8. pmf $ cdf

definition 1.6.1
> let $r_i\in range of X$, let $p_x(r_i)=Px(\{r_i\}),\ p_x$ is called a **probability mass function** (pmf)

definition 1.5.1
> let $F_X(x)=PX\big[(-\infty,x])\big]$, this is called the **cumulative distribution function** (cdf) of the random variable X.

#### 9.10. Example: Flip 3 coins

let x= # heads

Find the pmf ; cdf for x

S={HHH, HTH, HHT, HTT, THH, THT, TTH, TTT}
 ={3,   2,   2,   1,   2,   1,   1,   0}

pmf:
$$p_x(0)=\frac18\quad p_x(1)=\frac38\quad p_x(2)=\frac18\quad p_x(3)=\frac18\quad p_x(1.5)=0$$

cdf
 $$F(x)=P(X\le x)=0$$

### 1.6 Density and Mass Functions 

`2018.10.9`

#### 1. cdf conditions
Theorem 1.5.3 

>A cdf F(x) should satisfy 3 conditions:   
a. $\lim_{x\to-\infty}F(x)=0\ \& \lim_{x\to\infty}F(x)=1$;  
b. F is non-decreasing; and   
c. F is right-continuous, which means $\lim_{x\to\infty}f(x)>0$

#### 2. proof condition c.

#### 3. Probability Density Function
Definition 1.6.3

#### 4. Proof pdf