---
title: 'USP654 Fall 2017 HW1'
date: "10/09/2017"
output: html_document
---

**Due on 10/23**

[**Solutions**](hw01_solutions.html)

# Correlation and Ordinary Least Squares Regression

Anticipated time to complete: 3-4 hours

Please answer the following questions to the best of your ability using any combination of lectures, readings, and labs to support your work. In some cases I ask you to calculate things via equations, but you are welcome to use R/SPSS functions to check your work. If you use R or SPSS to answer a question, please provide the output including the code. Precision to 2 decimal places is sufficient.

I am in general far more interested in how you grapple with a question than your final results. In particular, I will not mark you down automatically for an incorrect numeric answer! Anyone can get “the answer” to multiple decimal places these days. Fewer can engage with those answers in a meaningful way. Understanding how an answer might be wrong is often more valuable than a trivially correct result.

All necessary data and auxiliary readings are in the homework folder. 

Please submit your assignment to D2L by 10/23. Feel free to work together, but turn in only your own work, in your own words, or risk both parties losing credit due to close similarity between answers.

1. Using [the provided california Transit Oriented Development (TOD) dataset](californiatod.csv), answer the following questions. Assuming the dataset represents the entire TOD projects in California (population) when the dataset was collected, so be sure to consider that fact in your responses. `transit` is the share of transit trips among all households living in a property while density is the development density in dwelling units/acre. 

    a. Report the mean & standard deviation of transit usage (`transit` variable) and density. Calculate the Pearson correlation coefficient (`rxy`) between transit usage (`transit` variable) and density. Use any formula that’s convenient, but only use built in functions (e.g. cor() in R or correlations in SPSS) to check your work. Briefly interpret the result, including a supporting plot if you think it helps.
    
    a. Now explain in words and functional formula(e) how you might model the relationship between transit usage and density  as a linear regression model. Be sure to identify and justify your assignment of variables, and explain the assumptions of your population regression function.

    a. Use equations (or matrix algebra, if you must!) to calculate ordinary least squares (OLS) solutions for $\beta_0$ and $\beta_1$ in your regression function (again, you may use built-in functions like lm() to check your work, but obtain the results using simple algebraic functions like sum()). Interpret the values obtained.
    
    a. Calculate the conditional means of Y for each value of X=x in the population. How are these results related to your population regression function?
    
    a. Plot (R, SPSS, or another method) the following clearly:
    
	     - XY scatterplot of the data
	     - Conditional means of Y given X=x for all values of X
	     - Your population regression line (PRL)
	    
	  a. Explain the key features of your plot in e), keeping in mind this is a population regression! For one value of X, explain precisely how each of the Y|X values relates to the PRL. Feel free to sketch on a copy of the plot to make your points clear.
	  
	  a. Use equations to calculate and then interpret (making reference to your plot if useful):
	     i. The sum of squared residuals (SSR)
	     i. The total sum of squares (TSS)
	     i. The coefficient of determination (R2)
	  
	  a. Use the solved PRL to predict the value of $Y$ for an $X$ that does not appear in the data. Write out the equation and solution.
	  
	  a. Make a case for the inclusion of two additional explanatory/control variables you might include to better explain transit use. Describe your hypothesis of effect direction of the new variables, and how you would operationalize the variables (e.g. coding them as dummy variables).
	  
1. Repeat (1) with your own dataset of a random sample. First make it clear whether you are working with a population or a sample. If your dataset is for a population, draw randomly from the population (with `sample_n()` function in R and `Data/Select Cases` in SPSS) to create a random sample of at least 10 observations. For this section, you may use built-in software functions (e.g. cor() and lm() in R, or correlations and regression in SPSS) for each part. No need to write out the equations again. For each sub-question in (1), interpret the results in term of sample regression. For part (e), plot the sample regression lines (SRL) on the plot. In addition to repeating (a)-(h) above, additionally answer the following.
	
	  i. Interpret the significance of:
	     - the model;
	     - the estimate of $\beta_0$ and $\beta_1$.
	  
	  i. Construct 95% confidence intervals for each $\beta$ in your SRL estimates. Interpret the range and its statistical meaning.
	  
	  i. For question 1.i, in addition to describing your hypothesis of effect direction of the new variables, and how you would operationalize the variables (e.g. coding them as dummy variables), run regression models with the two additional variables and conduct hypothesis tests whether the full model with additional variables are statistically better than the restricted model you estimated earlier.
	  
1. Choose ONE of the articles included in the folder to read. In 2-3 paragraphs, briefly describe the primary research question(s), research hypotheses, and experimental design of the study; then, choose ONE of the presented models and interpret the results. Include in your interpretation discussions of significance and effect size. Also include your own critique in terms of the modeling and interpretation. Make a case for one additional continuous explanatory/control variable and one discrete/dummy variable the authors could perhaps have included. 

    Please note the below points for your chosen study (Both paper available on D2L):
  
    - [Baskin et al. (Physical Activity Correlates)](https://link.springer.com/article/10.1007%2Fs12160-012-9437-7) - Paper states that standardized coefficients listed in Tables 2 & 3, but they are actually unstandardized (i.e. in original variable units). Also ignore typo where states “logistic regression” was run. All models are in fact classical linear regression.
    - [Lund (Pedestrian environments & community)](http://journals.sagepub.com/doi/abs/10.1177/0739456X0202100307) - Don’t worry about “Hierarchical Linear Model” (HLM); this is just a term for adding variables to a linear regression in groups and doesn’t impact the estimation or interpretation of results.
