---
title: "USP 570"
author: ""
date: ''
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
options(width = 2000)
options(repos="https://cran.rstudio.com")
```

#  {.tabset .tabset-fade .tabset-pills}

## Course Info

Link to The Transportation Planning Process
https://www.planning.dot.gov/documents/briefingbook/bbook_07.pdf

## Case study

Some basics about the existing land use and transportation, e.g. population size, density, land area, transit infrastructure/system, etc. 

What challenges/issues the region is facing with respect to transportation and land use

How transportation and land use is governed 

How the current regional transportation plan integrates land use

Any innovative approaches or success stories for integrating transportation and land use

https://docs.google.com/spreadsheets/d/1G83Ar37TttNj6MD6Hj13-2HMaXgjqvQwauKjrYWlqDU/

## Policy Memos

 - Anti-displacement strategies. 

The Metropolis MPO is in the process of planning the region’s first light rail line from downtown Cosmopolis to the region’s airport about 15 miles away. The planned route will go through three different cities and some unincorporated county land. The region faces a shortage of affordable housing and the planned route includes some neighborhoods with large shares of households below median income. The MPO is concerned about the potential for the new public investment to displace many of the lower-income households in the corridor. They want to address this issue from the beginning of the planning process. Prepare a memo for the MPO board as they start this planning process that covers the following:

Defines and explain gentrification and displacement, including what is known from other regions. What is are the causes? Why is this a problem?

Recommends what type of data analysis the MPO staff should undertake as they develop their plans.

Discuss and evaluate policy options for reducing displacement. Identify what criteria should be used to evaluate the options. Since this is an early analysis, your evaluation is not expected to be detailed or definitive. Think of this as an initial screening. More in depth analysis will come later. Use what is or is not known from the research and other regions. In evaluating the strategies, consider what agencies or other entities would be involved in implementation.


 - Accessibility measures for regional transportation planning. 

Choose a metropolitan area. This could be the same one that you use for your case study assignment. Imagine that they are going to update their regional transportation plan, along with their processes for selecting projects for funding, at all scales. The staff wants to incorporate measures of accessibility into decision making and needs the MPO board to agree. Prepare a memo for the MPO board that does the following:

Explains and defines accessibility, including why it should be used in transportation decision making
Defines different options for measuring accessibility for use in the regional transportation plan, as well as at the project level (e.g. new roadway capacity, transit infrastructure, bike/pedestrian infrastructure, demand and system management projects, etc.).
Evaluates the accessibility measures. You evaluation should use clear criteria and draw on existing sources.
Discusses how equity could be incorporated in the accessibility measures. In doing so, how are you defining equity?
Note: if the region you have chosen has already adopted accessibility measures in their planning process you should either (1) pick another region; or (2) ignore their existing measures.


 - Infill development and parking. 
 
Choose a major city within a metropolitan area, likely the one you are using for your case study. The city will need to have a well-established transit system, with several high-frequency bus routes (e.g. 10-15 minute headways in peak) and, ideally, some rail or bus rapid transit. Imagine that the city is reconsidering their parking requirements for new development, including infill development. Prepare a memo for the planning commission that does the following:

Explains the role of parking in travel demand, using evidence

Explains the role of parking in housing costs

Proposes options for a new parking requirements for both residential and commercial land uses. For this, draw on examples of what other cities have done, but do not let that limit your options.

Evaluate the options, using evidence and clear criteria. Your criteria must include equity, which you also need to define.

Provide a recommendation

You can base this analysis on the existing parking requirements for the city, but if they are not easily available, that is not necessary. But your analysis should take into account the specific context of the city, particularly the transit service and other factors.

 - Autonomous vehicles and land use. 
 
Choose a metropolitan area. This could be the same one that you use for your case study assignment. Imagine that you have been asked by the MPO to provide advice on how the MPO, as well as the cities within the region, should be planning for autonomous vehicles. Prepare a memo that does the following:

Explains the current and projected status of AVs

Discusses how AVs could influence demand for transportation and, in turn land use. For this analysis, use both theory and research.

Identifies the benefits and costs of these possible outcomes.

Presents policy and planning options for mitigating or otherwise addressing the possible land use effects.
Discusses how the MPO and cities may need alter the tools and analyses they use to consider AVs.

This memo is just one of a series that the MPO is commissioning on this topic. Therefore, your memo should focus on land use (broadly defined, including housing, parking, urban design). Other memos will covers topics related to AVS such as safety and liability.

 - TOD incentives. 
 
Choose a metropolitan area. This could be the same one that you use for your case study assignment. But, it needs to be a metro area with fixed-guideway (rail or “real” BRT) transit. Prepare a memo that does the following:

Explains what TOD is and how it may affect travel and transit use

Presents options for how the region an promote more TOD

Evaluate the options, using evidence and clear criteria. Your criteria must include equity, which you also need to define. You must also explain who (e.g. MPO, transit agency, city, etc.) would be responsible for implementing each option.

Provide a recommendation(s)

Identify a performance measure(s) to track progress in implementation. In doing so, consider inputs, outputs, and outcomes.
 
 - Federal transportation reauthorization or the Green New Deal. 

Congress is just starting to discussion reauthorization of the most recent surface transportation bill, the FAST-ACT. There are also proposals for a Green New Deal. For this memo, choose one of those national discussions for context. Choose a member of Congress (House or Senate) and imagine that you are a policy staffer for that member. Provide a memo that does the following:

Explains the relationships between transportation and land use and relates them to key concerns of the elected official. This will require you to know a bit about the official you chose. For example, is climate change a key concern for her/him? Jobs?

Explain the federal role in transportation and land use decision making.

Provide options for the reauthorization or Green New Deal for how it could include more transportation and land use-related items to help achieve the elected official’s goals. These could be policy or funding-related. Be as specific as possible.

Evaluate the options. Keep in mind the context of your audience of one. For example, what interest groups would be affected or be potential allies? In addition, how might the option affect different constituencies, e.g. by income and race?


 - State legislation to increase housing density. 

Last year, the California legislature considered SB 827 (Scott Wiener), a bill to increase housing density around transit. The bill failed, but has been reintroduced (SB 50). Washington State is also considering legislation to increase housing density, including HB 1923 (Fitzgibbon) and SB 5423/5769 (Palumbo). In Oregon, a bill by Senator Courtney would up-zone around transit and one by House Speaker Kotek would ban single-family-only zoning. Imagine that none of these bills pass this session and that it is 2020. Pick one of those states and imagine you work for a newly-elected state legislator who wants to understand the issue better, knowing that new legislation will be introduced that she will need to vote on. She ran on a platform to improve housing affordability, but did not have specifics. Prepare a memo to her that does the following:

Briefly summarizes the problem these bills are trying to address

Explains how housing density affects travel, and, therefore, other outcomes (e.g. emissions). Use theory and evidence.

Describes the main elements of at least three of the bills that failed. You may include other bills that you identify from other states.

Evaluate the elements of these bills, using evidence and clear criteria. Your criteria must include equity, which you also need to define.

Provide a recommendation to the new state legislator for what she should support. This may be elements of those previous bills, or a new option that you develop based on your analysis.
 
 - Urban growth boundaries. 

Imagine that you work for the National Conference of State Legislators. Several members have inquired about urban growth boundaries as a statewide policy. Prepare a memo that does the following:

Explains urban growth boundaries (UGBs) and their use in the U.S. and elsewhere

Explains how UGBs affect land use and travel behavior, and how transportation planning and investments interacts with UGBs.

Discuss the pros and cons of state legislation to mandate UGBs, focusing on transportation and land use impacts. Use evidence to support your points.

What are the equity implications of UGBs? Are there policies to address those implications?

## Week 2

 - Reading

1. Levinson & Krizek - Chapters 1 & 2

2. OECD, International Transport Forum, Linking People and Places, 2017 https://www.itf-oecd.org/linking-people-and-places

3. Susan Handy, "Enough with the “Ds” Already — Let’s Get Back to “A” Transfers Magazine, Spring 2018
https://transfersmagazine.org/enough-with-the-ds-already-lets-get-back-to-a/

4. One article from the list on the first tab of the shared Google sheet for this course:

https://docs.google.com/spreadsheets/d/1G83Ar37TttNj6MD6Hj13-2HMaXgjqvQwauKjrYWlqDU/

For the article, pay particular attention to the theories being use to guide the research. You will be expected to discuss your article in class, explaining the theory or theories used and how land use/built environment was measured and incorporated into the analysis. Refer to pages 4-5 in Levinson & Krizek for a brief overview of some of the relevant theories.

 - Activity

There are several on-line tools that measure some form of accessibility. Before class, use at least two of these tools to measure the accessibility of your current home and your childhood home. Come prepared in class to talk about what you found. What exactly was it measuring? How well does the score match your sense of accessibility for that location?

All Transit:  https://alltransit.cnt.org/

WalkScore: https://www.walkscore.com/

Bicycle Network Analysis: https://bna.peopleforbikes.org/#/  (city-level only)

Mobility Score: https://transitscreen.com/mobilityscore/

EPA Access to Jobs & Workers via Transit Tool: 
Overview: https://www.epa.gov/smartgrowth/smart-location-mapping#Trans45
Link to tool: https://epa.maps.arcgis.com/home/webmap/viewer.html?webmap=3bffc086a9b34928a632ab6c8530ebcf

EPA Walkability Index: 
Overview: https://www.epa.gov/smartgrowth/smart-location-mapping#walkability  
Link to tool: http://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fgeodata.epa.gov%2Farcgis%2Frest%2Fservices%2FOA%2FWalkabilityIndex%2FMapServer&source=sd

## Week 3

 - Reading
 
1. Levinson & Krizek, Chapters 3 (Homebuying) and 4 (Jobseeking)

2. Peter O. Muller, "Chapter 3: Transportation and Urban Form" in The Geography of Urban Transportation, Third Edition, Susan Hanson and Genevieve Giuliano, editors, Guilford Press, 2004. (Attached below)

3. One article that you find that uses hedonic modeling to assess the impacts of transportation infrastructure on real estate values. Two examples are attached, one old and one new, both from PSU faculty:

   Chen, H., Rufolo, A., Dueker, K.J. (1998) Measuring and Impact of Light Rail Systems on Single-Family Home Values: A Hedonic Approach with Geographic Information System Application. Transportation Research Record 1617: 38-43.

   Liu, J.H., Shi, W. (2017) Impact of Bike Facilities on Residential Property Prices. Transportation Research Record, 2662: 50-58.

To find your article, you could use Google Scholar to find articles that have cited either of those two articles, or were used in the literature review for the Liu and Shi article. You can also use search terms such as "impact of freeways on housing prices." The only limitations are that it should be from a peer-reviewed source and it needs to include a hedonic (regression) model that has transportation infrastructure (road, freeway, bike lanes, transit line, sidewalks, pipeline, etc.) as an independent variable and some type of real estate value (home prices, land value, rents, etc.) as the dependent variable. 

After reading the article, fill in a row on the Week 3 tab of our course Google sheet. You do not need to include this in your reading reflection for the week. Also, be prepared to discuss in class. 

https://docs.google.com/spreadsheets/d/1G83Ar37TttNj6MD6Hj13-2HMaXgjqvQwauKjrYWlqDU/edit#gid=2049364506

## Week 4

 - Reading

Levinson and Krizek, Chapters 7-9

Zuk, M., Bierbaum, A. H., Chapple, K., Gorska, K., Loukaitou-Sideris, A., Ong, P., & Thomas, T. (2015, August). Gentrification, displacement and the role of public investment: a literature review. Journal of Planning Literature, Vol. 32. https://journals.sagepub.com/doi/10.1177/0885412217716439

## Week 5

 - Reading
 
Levinson & Krizek Chapters 5 & 6, Traveling and Scheduling

Please skim the Southwest Corridor Equitable Housing Strategy, in preparation for our guest speaker, Ryan Curren, City of Portland: https://www.portlandoregon.gov/bps/article/675321
You do not need to cover this in your reading reflection.

 - Activity

Complete an travel & activity survey. I'm providing a copy of the instrument used for the Oregon Household Activity Survey in 2009. Note that it is not printed in the original booklet format, so it is a little less convenient. A pdf of the file is attached here. I also have a printed copy for all of you available at the front desk of USP (URBN 350). The form has instructions. If your last name starts with H-L, complete the diary for Sunday; M-O Tuesday, and Q-U Wednesday. Also note that the people who really would have completed this survey had already completed an enrollment survey that included demographics and other relevant information. The diary is just for recording activities and travel for one day. 

Be prepared in class to discuss your activity diary and experience, including these summary numbers:

Total # places you went
Total time (minutes) spent traveling. (You will have to calculate this with the times on the form)

## Week 6

 - Reading
 
Levinson & Krizek, Chapter 10

California recently made a major change (SB 743) in how they will evaluation new development and other projects, shifting the focus from Level of Service (LOS) to Vehicle Miles Travelled (VMT).

For context, read a short background story here: 
https://www.spur.org/news/2016-06-30/why-california-accidentally-encouraged-driving-and-how-thats-about-change and an update here: https://cal.streetsblog.org/2019/01/04/at-last-new-rules-are-final-car-delay-is-sometimes-not-an-environmental-impact/

Then go to the Office of Planning and Research website: http://opr.ca.gov/ceqa/updates/sb-743/ 
There is a Technical Advisory from December 2018. Read sections A-D. You can skim the rest. Watch four videos (narrative presentations) linked just below the technical advisory. Each is only 7.5 minutes long. Finally, look through the Key Resources section and find something that interests you. Read it and be prepared to share in a small group discussion in class. 

## Week 7

 - Reading
 
Chapter 11 Arranging

Ewing, Reid, et al. "Identifying and measuring urban design qualities related to walkability." Journal of Physical Activity and Health 3.s1 (2006): S223-S240. (Copy posted below)

 - Activity

Over the past few years, a number of researchers have developed tools to assess the bikeability or walkability of a neighborhood. These “audit” tools are being used for a variety of purposes. For this week, you are going to use one of those audit tools, focusing on walkability:

“The Measurement Instrument for Urban Design Quantities measures five urban design qualities of streetscapes: imageability, visual enclosure, human scale, transparency, and complexity. The operational definitions take the form of statistically-derived equations that link objectively measured physical features of the environment to ratings of urban design qualities.” http://www.activelivingresearch.org/node/10635. The manual and Excel spreadsheet for this tool are posted below. I have printed some paper copies of the manual. They are at the front desk in URBN 350 if you want to pick one up.

You should audit two blocks. One should be the block where you live. Choose another block that is different in urban design from where you live. Come to class with your sheets filled out and be prepared to discuss and critique the audit. 

## Week 8

 - Reading
 
Levinson & Krizek - Chapter 12, Assembling

The Rough Draft of Metro’s Designing Livable Streets and Trails Guide can be found by following this link: https://www.oregonmetro.gov/events/designing-livable-streets-and-trails-technical-work-group-meeting/2019-05-20 Review it and include in your reading reflection. Also, be prepared to discuss it with Lake McTighe in class.  Here's Lake's email about it;

Greetings Design Technical Work Group Members and Interested Parties:

A Rough Draft (pre-technical review, pre-layout and formatting) of Metro’s Designing Livable Streets and Trails Guide is available for review and comment by the technical work group and interested parties.

The goal of the rough draft is to showcase the broader themes, topics and layout of the guide. Placeholders indicate photographs, schematics, street and trail renderings and some graphics that are under development. Photos in the rough draft may also be placeholders. We are aiming to reduce the number of pages substantially by reducing repetition and tightening up the narrative and through layout solutions.

   Keep in mind that the guide is not providing specific engineering design details. It provides Metro’s recommended design approach to create livable streets and trails and achieve community outcomes.

   Input provided by end of day Tuesday, May 28 will be considered as the guide is finalized.  

   As you review the document, please consider the following: Is anything missing? Is anything unclear or confusing? Do you have concerns or questions about the content?                                                                                                                                                      
The Technical Work Group will meet on Monday, May 20 to provide input on the Rough Draft. Interested parties are welcome to attend the meeting. This will be the final meeting of the Technical Work Group

Technical Work Group MEETING NOTICE & MATERIALS

Meeting: Input on Rough Draft of Designing Livable Streets and Trails Guide*

Date: Monday, May 20, 2019

Time: 2 to 4 p.m.

Place: Metro Regional Center, Council Chamber – 600 NE Grand Avenue, Portland

Agenda:

   Overview of Rough Draft

   Next Steps to incorporate input and finalize the Guide

   Small group discussions

   Large group discussion
   
## Week 9

 - Reading
 
Required Reading (include in your reading reflection)

Levinson & Krizek Chapter 13 Administering

Guidebook to Funding Transportation Through Land Value Return and Recycling

You can either read the guidebook linked here:
http://www.trb.org/Publications/Blurbs/177574.aspx (focus on Chapters 1-3) and/or
Watch a webinar/video linked here:
http://www.trb.org/main/blurbs/178905.aspx

 - In-class discussion/activity

Several cities internationally have adopted congestion pricing programs, most notably Singapore, London, and Stockholm. Others are mentioned in Chapter 13. There are also examples in the U.S. of congestion pricing on roadways or lanes. It also looks like New York City will be adopting area-wide congestion pricing for part of Manhattan. Portland is also now discussing it.

Choose one of the places in the US or internationally that has implemented some type of congestion pricing, either area (e.g. London) or for specific roadways. To be considered congestion pricing, the fee should vary in a way that attempts to target congested times and/or locations. So, regular toll roads or toll bridges do not count. 

Find some evidence of how it was adopted and how it is working. Be on the lookout for any evidence on effects on land use, though that may not exist for some places. We're going to have a discussion, using that evidence, about the application of congestion pricing in Portland. 
 
## Week 9

 - Reading

Levinson & Krizek, Chapter 14

Planning Advisory Service Report 592, Planning for Autonomous Mobility (focus on Chapters 1-4, attached below)