---
title: "Policy Memo"
subtitle: "Accessibility measures for regional transportation planning"
date: 'May 2 - June 11'
output:
  word_document: null
  pdf_document: default
bibliography: bib_usp570.bib
mainfont: Times New Roman
geometry: margin=1in
spacing: single
fontsize: 12pt
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

To:  Scott Haggerty, chair of governing Commission of Bay Area Metropolitan Transportation Commission

From: Shen Qu, Policy Advisor

Date: 5/2/2019 

RE: Define and measure accessibility in Plan Bay Area 2050

# Summary

Accessibility, the ease of reaching destinations, is an important land use and transportation performance measure [@boisjoly2017insider].
The decision-making process should include clear accessibility objectives, definitions, and indicators in Plan Bay Area 2050. Some approaches and tools can promote achieving greater accessibility. The equity analysis of accessibility can help to reduce the risks of social exclusion for vulnerable individuals [@preston2007accessibility; @lucas2012transport]. 
Ultimately, the use of metrics in policy and practice is key to make progress toward the Bay Area long-range transportation and land use goals while preserving the character of its diverse communities and adapting to future population growth.

# Background

Plan Bay Area 2050 is an integrated long-range plan of transportation and land use developed and adopt by MTC (Metropolitan Transportation Commission) and ABAG (Association of Bay Area Governments). Work on Plan Bay Area 2050 is expected to begin in August 2019 and focused update that builds upon the growth pattern and strategies developed in the original Plan Bay Area 2040 (adopted in July 2017) but with updated planning assumptions that incorporate key economic, demographic and financial trends from the last four years.

Re-examining the prior Plan’s goals and targets is one of the first steps in updating Plan Bay Area in order to make them as meaningful as possible in measuring the Plan’s performance. In the current 13 performance targets [^1], three goals are about 'Equitable Access'[^2]. It is also a response to the most recent federal transportation bills – the Fixing America’s Surface Transportation Act (FAST Act) that require Plan Bay Area to address ‘accessibility and mobility of people and freight’ [@act2015fixing]. 

However, the federal guidelines and the prior plan don't define access explicitly. The terms accessibility and mobility are used as a vague term that do not reflect the ease of reaching various destinations and often are conflated, “misused,” or “abused” in practice [@halden2011use]. Although the three targets are components of accessibility, they do not fully reflect access to destinations and translate into indicators effectively. In spite of access to affordable housing, a broader environmental, economic and social goals should be included.


Explicitly defining and measuring accessibility as the end goal of the transportation network would encourage the establishment of accessibility-based performance indicators to assess the overall benefits of potential investments, and help decision-making for MTC and ABAG.

[^1]: The 13 performance targets are included in six categories: Climate Protection, Healthy and Safe Communities, Open Space and Agricultural Preservation, Equitable Access, Economic Vitality, and Transportation System Effectiveness.
[^2]: The three goals include: Decrease the share of lower-income residents’ household income consumed by transportation and housing by 10%; Increase the share of affordable housing in PDAs, TPAs, or high-opportunity areas by 15%; Do not increase the share of low- and moderate-income renter households in PDAs, TPAs, or high-opportunity areas that are at risk of displacement.

# Definition

Accessibility, defined as the ease of reaching destinations, services, or activities; the distribution, character, or amount of activity around a given place; the choices that the built environment offers to travelers [@preston2007accessibility; @litman2013new; @handy2018enough]. It is largely contingent on the spatial distribution of destinations, influenced by the distribution of residential, economic, cultural and social activities. 

The concept of accessibility has been a common element in the goals and objectives of transport plans [@hansen1959accessibility]. It is one of the most comprehensive performance measures of land use and transportation systems [@boisjoly2017get], which provides residents with greater access to a variety of opportunities. For individual, living in an area with high accessibility to jobs is associated with shorter trips, as is working in an area of high housing accessibility. For firms, high accessibility means that easy access to suppliers, workforce, customers, desirable environment, amenities, friendly government, etc. [@levinson2018metropolitan, p.111] Greater access is associated with higher employment rates, greater transit use, and less greenhouse gas emissions [@chen2008role; @owen2015modeling]. It is not only to support and foster economic development through improved employment accessibility for deprived areas, but also to enhance social inclusion and reduce social inequities. 


Accessibility is an instrumental concept in explaining the spatial form and function of metropolitan areas. 
It is the "fundamental force for the relationship between transport and land use in a city" [@levinson2018metropolitan, p.22] and impacts on city organization, development, and planning to achieve more sustainable outcomes. Moreover, it’s a goal that almost everyone can agree on to assess current conditions and proposed policies [@handy2018enough]. 

# The accessibility measures

The accessibility measures relate to the spatial distribution of opportunities such as households, jobs, retail stores, healthcare, and other services. The metrics can help policymakers to define regional transportation priorities.

 - Cumulative-opportunity measures: the availability of opportunities close by

Cumulative-opportunity measures typically account for the number of opportunities that can be reached from a specific location using a particular mode within a travel costs threshold [@handy1997measuring]. For example, the number of jobs that are within 45 minutes of travel times by transit from a specific place (counting exchange opportunities within a defined geographic parameter).

Cumulative-opportunity measures are easy to generate, interpret, and communicate. Policy-makers most commonly use them as they provide a comprehensive measure of the land use and transport system at the regional level [@dodson2007investigating]. It is thus better suited for planning documents.

 - Gravity-based measure: the ease and worth of travel to destinations far away

The gravity-based measure discounts opportunities with a distance-decay function based on the travel costs (pitting the importance of given exchange opportunities against travel time impedances). The farther opportunities receive less weight than closer. This measure better reflects travel behavior as it accounts for the travelers’ perceptions of time [@ben1979disaggregate]. 

This measure is not directly expressed in terms of the number of opportunities, is more complex to generate, and more difficult to interpret and communicate [@geurs2004accessibility; @owen2015modeling].

Integrating both cumulative-opportunity and gravity-based measure, including access to transport and destinations, would provide a good indication of transport coverage, captures the performance of the land use and transportation systems, and better reflect the social and economic benefits [@banister2008sustainable; @koenig1980indicators; @wachs1973physical].

 - The evaluation of local/neighborhood accessibility.

Local accessibility is primarily determined by nearby activity (approximately one-half to one mile in residential areas). The destinations include grocery stores, schools, hospitals, parks or public transport station. It is a reflection of the available opportunities for jobs and services at the neighborhood levels. 

Local accessibility policy initiatives speak more to issues of mixing uses on a parcel or neighborhood scale, site design, and more directly, facilitating circulation patterns that enhance walking, bicycling, and transit use. Local accessibility is often associated with cycling and walking. Distance thresholds are used instead of travel time thresholds (0.5 miles for walking). These appear to be appropriate measures of accessibility, as time is generally proportional to the distance traveled by bicycle or foot. 

How better a new transport infrastructure improvement increases accessibility? Who and where can directly use the facility? Sufficient information about the tradeoffs inherent in different development scenarios can help regions choose projects more objectively. Analyzing future development scenarios in terms of their levels of accessibility could provide better information about the performance and the costs of different transportation-infrastructure and land-use scenarios, and leverage MTC’s influence on municipal-level land-use decisions. 


# Equity analysis

Equity analysis based on accessibility is about the environmental justice assessment, which evaluates whether there are any disproportionately high and adverse impacts on low-income or minority populations [^3]. It promotes proximity to services, amenities, and opportunity areas for specific vulnerable groups relatively the general population. It assesses the distribution of benefits and burdens on communities of concern in comparison to the rest of the region and helps Plan Bay Area’s objective to advance equity in the region. Equity analysis can include specific types of destinations, modes, jobs, social groups, or temporal fluctuations.

[^3]: "Environmental justice is the fair treatment and meaningful involvement of all people regardless of race, color, national origin, or income with respect to the development, implementation, and enforcement of environmental laws, regulations, and policies."  [@EPA2019EJ]

The accessibility to all jobs may not represent the opportunities that are available to different groups of populations.
It is necessary to segment the accessibility analysis by socio-economic groups such as income, level of education, gender and vehicle ownership that affect one's abilities and needs to access destinations. 

Measures of generalized costs (including financial and time costs) better reflect the total costs of travel as they include both financial and time burdens. These measures can also provide insight on fare structures and trip affordability, address the financial constraints that vulnerable individuals may face.

Time restrictions also play an important role in determining accessibility, which include land use, transport and individual constraints such as (opening hours, schedule of services, job starting time, etc.)


# More options 

More efforts are needed to implement accessibility-based approaches effectively. The utility-based measures capture the economic benefits provided by changes in the network. Utility-based measures account for most components of accessibility and can be included in traditional cost-benefit analysis [@van2016accessible]. 

Other dimensions of accessibility such as affordability, transfer and digital connectivity [@lyons2016guidance] should not be neglected in metropolitan transportation plans and should come up as the aspects of accessibility objectives.

Accessibility maps and metrics provide an overview of the land use and transportation network, are useful tools to communication gaps and thus helps decision-makers, planners and the general population to better grasp the impacts of transportation investments. 

# Conclusion

Plan Bay Area 2050 will set a roadmap for future transportation investments and will identify what it would take to accommodate expected growth.
Accessibility, the ease of reaching destinations, allows capturing the complex interactions between land use and transportation systems while providing a social perspective on transportation planning. 

Setting clear accessibility requirements for transportation planning processes and planning documents could provide greater transparency and foster the inclusion of accessibility aspect in the decision-making process. Integrating Plan Bay area 2050 goals with accessibility-focused performance measures could help MTC, ABAG, and local governments make better decisions about the selection and prioritization of transportation infrastructure [@boisjoly2017insider].




Notes {#notes}
==========



---
nocite: | 
  @litman2017evaluating
...


References {#references .unnumbered}
==========



