---
title: "RESEARCH PAPER"
author: ""
date: 'May 2 - June 11'
output:
  pdf_document: 
geometry: margin=1in
mainfont: Times New Roman
fontsize: 12pt
spacing: double
---

The other option is a research paper that exploresa topic of your choosing in depth, using a wide range of literature and your own data analysis.Your objective is to provide an original contribution.The topic must relate to transportation andland useand one or more of the theories presented in the textbook. 

Your paper could answera broad question (e.g. How should we measure sprawl? How does regional urban form affect commuting behavior? How does a rail line or bike path influence property values?) using a specific data source. 

Alternatively, you would take a specific project or policy and evaluate itin depth.The paper must include some original data analysis. 

This most likely will be analysis of secondary data, such as the Census, a travel survey (e.g. NHTS), the American Housing Survey, GIS data (e.g. RLIS), etc. If you want to collect your own quantitative data or perform a qualitative analysis (e.g. in depth observation, interviews, content analysis, etc.), that’s possible, but will take more planning and work. Check with me first. 

The paper must include a literature review that includes at least five academic (i.e. peer reviewed journal articles) sources. 

Details: 15-20 pages, double-spaced, not including figures, tables, and references. Initial topic due in class on April 18. This should include a brief description of the topic, a list of key references (including academic literature), specific research question(s)and hypotheses, and the data source(s) you plan to use. 

Paper update due May 2. This should include a draft of the introduction/background sections, the literature review, and the methodology. (10 points) 

Final paper due Tuesday June 115 pm.(40 points)

### \textcolor[rgb]{0.7,0.7,0.7}{Week 2}



```{r, eval =F}
.
```