---
title: "Reading reflections"
subtitle: "USP 570"
author: 'Shen Qu'
date: "Week 8"
output:
  word_document: null
  pdf_document: default
bibliography: bib_usp570.bib
mainfont: Times New Roman
geometry: margin=1in
spacing: double
fontsize: 12pt
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)

options(width = 2000)
options(repos="https://cran.rstudio.com")

# install.packages("citr")
```


 - The 'Diamond of Design'
 
@levinson2018metropolitan [Chapter.11] introduced a new 'Diamond,' a structure of four key design tenets-hierarchy, morphology, layers, and architectural content. Here authors define the term 'design' as "how elements of place and plexus arrange their parts into a whole on a variety of scales, from the neighborhood to the metropolis." This framework even covers the cities system as a high-level hierarchy place. This perspective is more from engineering or computer science. The authors compare the layers of place and plexus with the OSI (Open Systems Interconnection) Model, a computer networking framework. This viewpoint is different from the planner who has a design background, but it provides a powerful tool to explain the complexity of urban land use and transportation.

 - Objectively measure subjective qualities



[^1]: Intraclass Correlation Coefficient reflects the proportion of the variance of an observation that is the result of differences between treatments.

 - Discussion: predetermined or prior information.




References {#references .unnumbered}
==========
