---
title: "Reading reflections"
subtitle: "USP 570"
author: 'Shen Qu'
date: "Week 9"
output:
  word_document: null
  pdf_document: default
bibliography: bib_usp570.bib
mainfont: Times New Roman
geometry: margin=1in
spacing: double
fontsize: 12pt
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)

options(width = 2000)
options(repos="https://cran.rstudio.com")

# install.packages("citr")
```


 - The 'Diamond of Operation'
 
@levinson2018metropolitan [Chapter.12] provide a $2\times2$ combination to explain transportation administering. The two rows are queuing and charging. As the authors said, "Based on ability and willingness to wait, queues ration makes people wait in line," which is more equitable. "Prices ration based on ability and willingness to pay money, are more efficient than queues from an economic point of view." The two columns are short term and long term. When "operating and allocating scarce resources," the mechanisms between short term and long term are different. The short-term strategies can allocate the use of limited road space through queuing or pricing. The long-term strategies focus on growth controls for funding infrastructure or achieving other goals like revitalization, smart growth, etc.

 - Growth management and funding transportation

@levinson2018metropolitan use another $2\times2$ combination to summarize the techniques of value capture: New or existing land development; New or existing infrastructure.
The new-new combination includes impact fees and joint development; the double-existing combination has land-value taxes and transportation utility fees; The new infrastructure with existing development use special assessments and tax increment financing (TIF); The new development with existing infrastructure relates to Air right.

@vadali2018guidebook discussed these techniques from a perspective of investment. The guidebook introduced ten value capture methods with two categories: land value return and recycling methods and land value return-like methods. The former is "the public recovery of a portion of the increased land value that is created as a result of public-sector investment in infrastructure and the reutilization of that value to invest in infrastructure," which is based on the beneficiary principle. The later is based on the cost principle.

 -------------------------------------------------------------------
 Land value return and recycling methods Land value return–like methods
 --------------------------------------- ---------------------------
 Land value tax or split rate tax        Transportation utility fee

 Betterment levy                         Tax increment financing
 
 Special assessment district fee         Development impact fee
 
 Sale of public land or air rights       Exaction or proffer
 
 Lease of public land or air rights       
 
 Joint development fee or interface fee
 -------------------------------------------------------------------


 - Discussion: 

The short-term strategies usually arrange the traffic flow to optimize the use of transportation infrastructure. [@levinson2018metropolitan] Through congestion or charging, the transportation engineers try to achieve the maximum flow or eliminate the bottleneck. Some policies or tools may have significant effects on transportation in the short term but may come back to its original point in the long run. Such as, adding a new lane for a highway may release the congestion for several months or several years. But it will attract more traffic flow from around here, influence people's location choices, induce more demand, and resume the current congestion level at the end.

Urban planners are more concerned about long-term strategies, which think of solving transportation problems through regulating the use of land. The concept behind the growth management is that "providing public goods and services creates value and those who receive that value should return a portion of that value to the public sector to compensate for the costs incurred to provide the public goods and services." Because transportation is a semi-public good with the properties of nonrivalrous and nonexcludable. Up til now, there is no efficient way to capture and measure the use of transportation infrastructure for each user. Even it becomes possible, the charging cost and transaction cost are unacceptable. By the development of ITS and automated driving system, the realtime full-coverage transportation services may be available for everyone in the future. As claimed by some TNC, the transportation-as-a-service (Taas) can precisely calculate the degree of resource consuming for each trip, including the cost of fuels, vehicles, roads, environmental effects, and management system. The customers just choose the time, destinations, quality, and payment. This scenario will redefine the boundary of public goods in the transportation field. Once the new mechanism can internalize all the externalities, the land use may have a whole new pattern and distinctive spatial structure.


References {#references .unnumbered}
==========
