---
title: 'STAT311 Notes'
author: ""
date: ""
output: html_document
---

#  {.tabset .tabset-fade .tabset-pills}

Introduction to Mathematical Analysis

> Draft

## 1. TOOLS FOR ANALYSIS
 1.1. BASIC CONCEPTS OF SET THEORY
 
 **Theorem 1.1.1** Two sets A and B are equal if and only if $A\subset B$ and $B\subset A$.
 
 N = f1;2;3; : : :g, the set of natural numbers or positive integers.
 Z = f0;1;􀀀1;2;􀀀2; : : :g, the set of integers (that is, the natural numbers together with zero
and the negative of each natural number).
 Q = fm=n : m;n 2 Z;n 6= 0g, the set of rational numbers.
 R, the set of real numbers.
 Intervals. For a;b 2 R, we have
[a,b] = {x 2 R : a  x  bg,
(a,b] = {x 2 R : a < x  bg,
[a,¥) = {x 2 R : a  xg,
(a,¥) = {x 2 R : a < xg,

For two sets A and B, the union, intersection, difference, and symmetric difference of A and B are
given respectively by
A[B = fx : x 2 A or x 2 Bg;
$A\B = fx : x 2 A and x 2 Bg;$
AnB = fx : x 2 A and x =2 Bg;and
A D B = (AnB)[(BnA):
If $A\B = / 0$, we say that A and B are disjoint.
 
Theorem 1.1.2 Let A;B, and C be subsets of a universal set X. Then the following hold:
(a) A[Ac = X;
(b) $A\Ac = / 0$;
(c) (Ac)c = A;
(d) (Distributive law) $A\(B[C) = (A\B)[(A\C)$;
9
(e) (Distributive law) $A[(B\C) = (A[B)\(A[C)$;
(f) (DeMorgan’s law) $An (B[C) = (AnB)\(AnC)$;
(g) (DeMorgan’s law) $An (B\C) = (AnB)[(AnC)$;
(h) $AnB = A\Bc$:
 
 Theorem 1.1.3 Let fAi : i 2 Ig be an indexed family of subsets of a universal set X and let B be a
subset of X. Then the following hold:

(a) $B[Ti2I Ai=Ti2I B[Ai$;
(b) $B\Si2I Ai=Si2I B\Ai$;
(c) $BnTi2I Ai=Si2I BnAi$;
(d) $BnSi2I Ai=Ti2I BnAi$;
(e) $Ti2I Aic=Si2I Ac$;
(f) $Si2I Aic=Ti2I Ac$.
 
 
 1.2. FUNCTIONS

 **Definition 1.2.1** Let X and Y be sets. A function from X into Y is a subset $f\subset X\timesY$ with the following properties
(a) For all x 2 X there is y 2 Y such that (x;y) 2 f .
(b) If (x;y) 2 f and (x; z) 2 f , then y = z.
 
 **Definition 1.2.2** A function f : X !Y is called surjective (or is said to map X onto Y) if for every
element y 2 Y, there exists an element x 2 X such that f (x) = y.

 **Theorem 1.2.1** Let f : X !Y. If there are two functions g: Y ! X and h: Y ! X such that
g( f (x)) = x for every x 2 X and f (h(y)) = y for every y 2 Y, then f is bijective and g = h = f 1.

 **Definition 1.2.3** Let f : X !Y be a function and let A be a subset of X. Then the image of A under
f is given by
f (A) = f f (a) : a 2 Ag:
It follows from the definition that
f (A) = fb 2 Y : b = f (a) for some a 2 Ag:
Moreover, f is surjective if and only if f (X) =Y.
For a subset B of Y, the preimage of B under f is defined by
f (B) = fx 2 X : f (x) 2 Bg:

 **Remark 1.2.2** Note that, despite the notation, the definition of preimage does not require the
function to have an inverse. It does not even require the function to be injective.

 **Theorem 1.2.3** Let f : X !Y be a function, let A be a subset of X, and let B be a subset of Y. The
following hold:
 (a) A  f 1( f (A)).
 (b) f ( f 􀀀1(B)) B.

 **Theorem 1.2.4** Let f : X !Y be a function, let A;B  X, and let C;D Y. The following hold:
(a) If C  D, then f 1(C) f 1(D);
(b) f 1(DnC) = f 1(D) n f 1(C);
(c) If A  B, then f (A)  f (B);
(d) f (AnB)  f (A) n f (B).

 **Theorem 1.2.5** Let f : X !Y be a function, let fAaga2I be an indexed family of subsets of X, and
let fBb gb2J be an indexed family of subsets of Y. The following hold:
(a) f (Sa2I Aa) =Sa2I f (Aa);
(b) f (Ta2I Aa) Ta2I f (Aa);
(c) f 1(Sb2J Bb ) =Sb2J f 1(Bb );
(d) f 1(Tb2J Bb ) =Tb2J f 1(Bb ).

 **Theorem 1.2.6** Let f : X !Y and g: Y !Z be two functions and let B  Z. The following hold:
(a) (g  f )1(B) = f 1(g1(B));
(b) If f and g are injective, then g  f is injective;
(c) If f and g are surjective, then g  f is surjective;
(d) If g  f is injective, then f is injective;
(e) If g  f is surjective, then g is surjective.

 **Definition 1.2.4** A sequence of elements of a set A is a function with domain N and codomain A.

 **Definition 1.2.5** We say that set A is finite if it is empty or if there exists a natural number n and a one-to-one correspondence f : A!f1;2; : : : ;ng. A set is infinite if it is not finite.

 **Theorem 1.2.7** Suppose A is an infinite set. Then there exists a one-to-one function f : N!A.

 1.3. THE NATURAL NUMBERS AND MATHEMATICAL INDUCTION
 
 **Theorem 1.3.1** Principle of Mathematical Induction. For each natural number n 2 N, suppose
that P(n) denotes a proposition which is either true or false. Let A = fn 2 N : P(n) is trueg. Suppose
the following conditions hold:
  (a) 1 2 A. 
  (b) For each k 2 N, if k 2 A, then k+1 2 A. 
Then A = N.
 
 **Theorem 1.3.2** — Generalized Principle of Mathematical Induction. Let n0 2 N and for each
natural n  n0, suppose that P(n) denotes a proposition which is either true or false. Let A = fn 2
N : P(n) is trueg. Suppose the following two conditions hold:
(a) n0 2 A.
(b) For each k 2 N, k  n0, if k 2 A, then k+1 2 A.
Then fk 2 N : k  n0g  A.
 
 **Theorem 1.3.3** —Principle of Strong Induction. For each natural n 2N, suppose that P(n) denotes
a proposition which is either true or false. Let A = fn 2 N : P(n) is trueg. Suppose the following
two conditions hold:
(a) 1 2 A.
(b) For each k 2 N, if 1;2; : : : ;k 2 A, then k+1 2 A.
Then A = N.
 **Remark 1.3.4** Note that the inductive step above says that, in order to prove P(k+1) is true, we
may assume not only that P(k) is true, but also that P(1), P(2),. . . ,P(k1) are true.
There is also a generalized version of this theorem where the base case is for some integer n0 > 1.
 
 1.4. ORDERED FIELD AXIOMS
 
 **Proposition 1.4.1** For x;y; z 2 R, the following hold:
  (a) If x+y = x+z, then y = z;
  (b) 􀀀(􀀀x) = x;
  (c) If x 6= 0 and xy = xz, then y = z;
  (d) If x 6= 0, then 1=(1=x) = x;
  (e) 0x = 0 = x0;
  (f) 􀀀x = (􀀀1)x;
  (g) x(􀀀z) = (􀀀x)z = 􀀀(xz).
  (h) If x > 0, then 􀀀x < 0; if x < 0, then 􀀀x > 0;
  (i) If x < y and z < 0, then xz > yz;
  (j) 0 < 1.
 
 **Definition 1.4.1** Given x 2 R, define the absolute value of x by
jxj =
(
x; if x  0;
x; if x < 0:

 **Proposition 1.4.2** Let x;y;M 2 R and suppose M > 0. The following properties hold:
(a) jxj  0;
(b) jxj = jxj;
(c) jxyj = jxjjyj;
(d) jxj < M if and only if M < x < M. (The same holds if < is replaced with.)
 
 **Theorem 1.4.3** — Triangle Inequality. Given x;y 2 R,
jx+yj  jxj+jyj:

 **Corollary 1.4.4** For any x;y 2 R,
jjxj􀀀jyjj jx􀀀yj:

 **Remark 1.4.5** The absolute value has a geometric interpretation when considering the numbers in
an ordered field as points on a line. The number jaj denotes the distance from the number a to 0.
More generally, the number d(a;b) = ja􀀀bj is the distance between the points a and b. It follows
easily from Proposition 1.4.2 that d(x;y)  0, and d(x;y) = 0 if and only if x = y. Moreover, the
triangle inequality implies that
d(x;y) d(x; z)+d(z;y);
for all numbers x;y; z.

 
 1.5. THE COMPLETENESS AXIOM FOR THE REAL NUMBERS
 
 **Definition 1.5.1** Let A be a subset of R. A number M is called an upper bound of A if
x  M for all x 2 A:
If A has an upper bound, then A is said to be bounded above.
 
 **Definition 1.5.2** Let A be a nonempty set that is bounded above. We call a number a a least upper
bound or supremum of A, if
(1) x  a for all x 2 A (that is, a is an upper bound of A);
(2) If M is an upper bound of A, then a  M (this means a is smallest among all upper bounds).
 
 **Proposition 1.5.1** Let A be a nonempty subset of R that is bounded above. Then a = supA if and
only if
  (1) x  a for all x 2 A;
  (2) For any e > 0, there exists a 2 A such that a e < a.
 
 The Completeness Axiom. Every nonempty subset A of R that is bounded above has a least upper
bound. That is, supA exists and is a real number.
 
 **Definition 1.5.3** Let A be a nonempty subset of R that is bounded below. We call a number b a
greatest lower bound or infimum of A, denoted by b = infA, if
(1) x  b for all x 2 A (that is, b is a lower bound of A);
(2) If N is a lower bound of A, then b  N (this means b is largest among all lower bounds).
 
 **Proposition 1.5.2** Let A be a nonempty subset of R that is bounded below. Then b = infA if and
only if
(1’) x  b for all x 2 A;
(2’) For any e > 0, there exists a 2 A such that a < b +e.
 
 **Theorem 1.5.3** Let A and B be nonempty sets and A  B. Suppose B is bounded above. Then
supA  supB.
 
 **Definition 1.5.4** The extended real number system consists of the real field R and the two symbols
 and . We preserve the original order in R and define
 < x < 
for every x 2 R
 
 **Definition 1.5.5** If A 6= /0 is not bounded above in R, we will write supA = . If A is not bounded
below in R, we will write infA = .
 
 1.6. APPLICATIONS OF THE COMPLETENESS AXIOM
 
 **Theorem 1.6.1** — The Archimedean Property. The set of natural numbers is unbounded above.
 **Theorem 1.6.2** The following hold:
  (a) For any x 2 R, there exists n 2 N such that x < n;
  (b) For any e > 0, there exists n 2 N such that 1=n < e;
  (c) For any x > 0 and for any y 2 R, there exists n 2 N such that y < nx;
  (d) For any x 2 R, there exists m 2 Z such that m􀀀1 x < m.
 
 **Theorem 1.6.3** — The Density Property of Q. If x and y are two real numbers such that x < y, then
there exists a rational number r such that
x < r < y:
 **Proposition 1.6.4** The number p 2 is irrational.
 
 **Theorem 1.6.5** Let x and y be two real numbers such that x < y. Then there exists an irrational
number t such that
x < t < y:
 
## 2. SEQUENCES
 2.1. CONVERGENCE
 
 **Definition 2.1.1** Let fang be a sequence of real numbers. We say that the sequence fang converges
to a 2 R if, for any e > 0, there exists a positive integer N such that for any n 2 N with n  N, one
has
janaj < e (or equivalently, a􀀀e < an < a+e):
 
 **Lemma 2.1.2** Let  0. If  < e for all e > 0, then  = 0:
 
 **Theorem 2.1.3** A convergent sequence fang has at most one limit.
 
 **Lemma 2.1.4** Given real numbers a;b, then a  b if and only if a < b+e for all e > 0.
 
 **Theorem 2.1.5** — Comparison Theorem. Suppose fang and fbng converge to a and b, respectively,
and an  bn for all n 2 N. Then a  b.

 **Theorem 2.1.6** — The Squeeze Theorem. Suppose the sequences fang, fbng, and fcng satisfy
an  bn  cn for all n 2 N;
and limn! an = limn! cn = `. Then limn!¥ bn = `.
 
 **Definition 2.1.2** A sequence fang is bounded above if the set fan : n 2 Ng is bounded above.
Similarly, the sequence fang is bounded below if the set fan : n 2 Ng is bounded below. We say that
the sequence fang is bounded if the set fan : n 2 Ng is bounded, that is, if it is both bounded above
and bounded below.
 
 **Theorem 2.1.7** A convergent sequence is bounded.
 
 **Definition 2.1.3** Let fang¥ n=1 be a sequence of real numbers. The sequence fbng¥ n=1 is called a
subsequence of fang¥ n=1 if there exists a sequence of increasing positive integers
n1 < n2 < n3 <  ;
such that bk = ank for each k 2 N.
 
 **Lemma 2.1.8** Let fnkgk be a sequence of positive integers with
n1 < n2 < n3 < 
Then nk  k for all k 2 N.

 **Theorem 2.1.9** If a sequence fang converges to a, then any subsequence fankg of fang also converges
to a.
 
 **Remark 2.1.10** Given a positive integer k0, it will be convenient to also talk about the sequence
fangnk0 , that is, a function defined only for the integers greater than or equal to k0. For simplicity
of notation, we may also denote this sequence by fang whenever the integer k0 is clear from the
context. For instance, we talk of the sequence fang given by
$$a_n=\frac{n+1}{(n-1)(n-2)}$$
 
 2.2. LIMIT THEOREMS
 
 **Theorem 2.2.1** Let fang and fbng be sequences of real numbers and let k be a real number. Suppose
fang converges to a and fbng converges to b. Then the sequences fan +bng, fkang, and fanbng
converge and
  (a) limn!¥(an+bn) = a+b;
  (b) limn!¥(kan) = ka;
  (c) limn!¥(anbn) = ab;
  (d) If in addition b 6= 0 and bn 6= 0 for n 2 N, then an bn converges and limn!¥anbn=ab
 
 2.3. MONOTONE SEQUENCES
 
 **Definition 2.3.1** A sequence fang is called increasing if
an  an+1 for all n 2 N:
It is called decreasing if
an  an+1 for all n 2 N:
 
 **Theorem 2.3.1** — Monotone Convergence Theorem. Let fang be a sequence of real numbers.
The following hold:
(a) If fang is increasing and bounded above, then it is convergent.
(b) If fang is decreasing and bounded below, then it is convergent.
 
 **Remark 2.3.2** It follows from the proof of Theorem 2.3.1 that if fang is increasing and bounded
above, then
limn!¥an = supfan : n 2 Ng:
Similarly, if fang is decreasing and bounded below, then
limn!¥an = inffan : n 2 Ng:
 
 **Theorem 2.3.3** — Nested Intervals Theorem. Let fIng¥ n=1 be a sequence of nonempty closed
bounded intervals satisfying In+1  In for all n 2 N. Then the following hold:
  (a) T¥ n=1 In 6= / 0.
  (b) If, in addition, the lengths of the intervals In converge to zero, then T¥ n=1 In consists of a single point.

 **Definition 2.3.2** A sequence fang is said to diverge to  if for every M 2 R, there exists N 2 N such
that
an > M for all n N:

 **Remark 2.3.4** We should not confuse a sequence that diverges to ¥ (that is, one that satisfies the
previous definition), with a divergent sequence (that is, one that does not converge).

 **Theorem 2.3.5** If a sequence fang is increasing and not bounded above, then
limn!¥an = ¥:
Similarly, if fang is decreasing and not bounded below, then
limn!¥an = 􀀀¥:

 **Theorem 2.3.6** Let fang, fbng, and fcng be sequences of real numbers and let k be a constant.
Suppose
limn!¥an = ¥; limn!¥bn = ¥; and limn!¥cn = 􀀀¥
Then
  (a) limn!¥(an+bn) = ¥;
  (b) limn!¥(anbn) = ¥;
  (c) limn!¥(ancn) = 􀀀¥;
  (d) limn!¥ kan = ¥ if k > 0, and limn!¥ kan = 􀀀¥ if k < 0;
  (e) limn!¥1an= 0. (Here we assume an 6= 0 for all n.)

 **Theorem 2.3.7** Suppose an  bn for all n 2 N.
  (a) If limn!¥ an =¥, then limn!¥ bn = ¥.
  (b) If limn!¥ bn = , then limn!¥ an =¥.

 2.4. THE BOLZANO-WEIERSTRASS THEOREM
 
 **Theorem 2.4.1** — Bolzano-Weierstrass. Every bounded sequence fang of real numbers has a
convergent subsequence.
 
 **Definition 2.4.1** (Cauchy sequence). A sequence fang of real numbers is called a Cauchy sequence
if for any e > 0, there exists a positive integer N such that for any m;n  N, one has
jamanj < e:

 **Theorem 2.4.2** A convergent sequence is a Cauchy sequence
 
 **Theorem 2.4.3** A Cauchy sequence is bounded.
 
 **Lemma 2.4.4** A Cauchy sequence that has a convergent subsequence is convergent.
 
 **Theorem 2.4.5** Any Cauchy sequence of real numbers is convergent.
 
 **Remark 2.4.6** It follows from Definition 2.4.1 that fang is a Cauchy sequence if and only if for
every e > 0, there exists N 2 N such that
 
 jan+panj < e for all n N and for all p 2 N:

 **Definition 2.4.2** A sequence fang is called contractive if there exists k 2 [0;1) such that
jan+2an+1j kjan+1anj for all n 2 N:
 
 **Theorem 2.4.7** Every contractive sequence is convergent.
 
 2.5. LIMIT SUPERIOR AND LIMIT INFERIOR
 
 **Proposition 2.5.1** Let fang be a bounded sequence. Define
sn = supfak : k  ng (2.8)
and
tn = inffak : k  ng: (2.9)
Then fsng and ftng are convergent.
 
 **Definition 2.5.1** Let fang be a sequence. Then the limit superior of fang, denoted by limsupn!¥ an,
is defined by 

limsup n!¥ an = lim n!¥ supfak : k ng:
 
 **Theorem 2.5.2** If fang is not bounded above, then

limn!¥sn = ¥;

 **Remark 2.5.3** By Theorem 2.5.2, we see that if fang is not bounded above, then
 
limsupn!¥an = ¥:

 **Theorem 2.5.4** Let fang be a sequence and ` 2 R. The following are equivalent:
 
  (a) $limsupn!¥ an =\iota$.
  (b) For any e > 0, there exists N 2 N such that
an < `+e for all n N;
and there exists a subsequence of fankg of fang such that
limk!¥ank = `:
 
 **Theorem 2.5.5** Let fang be a sequence and ` 2 R. The following are equivalent:
  
  (a) liminfn!¥ an = `.
  (b) For any e > 0, there exists N 2 N such that
an > `􀀀e for all n  N;
and there exists a subsequence of fankg of fang such that
lim k!¥ ank = `:

 **Corollary 2.5.6** Let fang be a sequence. Then
limn!¥an = ` if and only if limsupn!¥an = liminfn!¥an = `:

 **Corollary 2.5.7** Let fang be a sequence.
 
  (a) Suppose limsupn!¥ an = ` and fankg is a subsequence of fang with
limk!¥ank = `0:Then `0  `.
  (b) Suppose liminfn!¥ an = ` and fankg is a subsequence of fang with
limk!¥ank = `0:Then `0  `.
 
 **Remark 2.5.8** Let fang be a bounded sequence. Define
A = fx 2 R : there exists a subsequence fankg with limank = xg:
 
 **Theorem 2.5.9** Suppose fang is a sequence such that an > 0 for every n 2 N and
limsupn!¥an+1an= ` < 1:
Then limn!¥ an = 0.
 
 **Theorem 2.5.10** Suppose fang is a sequence such that an > 0 for every n 2 N and
liminfn!¥an+1an= ` > 1:
Then limn!¥ an = ¥.
 
 
 2.6. OPEN SETS, CLOSED SETS, COMPACT SETS, AND LIMIT POINTS
 
 The open ball in R with center a 2 R and radius d > 0 is the set
B(a;d) = (a􀀀d;a+d):

 **Definition 2.6.1** A subset A of R is said to be open if for each a 2 A, there exists d > 0 such that
B(a;d)  A:

 **Theorem 2.6.1** The following hold:
  (a) The subsets /0 and R are open.
  (b) The union of any collection of open subsets of R is open.
  (c) The intersection of a finite number of open subsets of R is open.

 **Definition 2.6.2** A subset S of R is called closed if its complement, Sc = RnS, is open.

 **Theorem 2.6.2** The following hold:
  (a) The sets /0 and R are closed.
  (b) The intersection of any collection of closed subsets of R is closed.
  (c) The union of a finite number of closed subsets of R is closed.

 **Theorem 2.6.3** A subset A of R is closed if and only if for any sequence fang in A that converges
to a point a 2 R, it follows that a 2 A.

 **Theorem 2.6.4** If A is a nonempty subset of R that is closed and bounded above, then maxA exists.
Similarly, if A is a nonempty subset of R that is closed and bounded below, then minA exists
 
 **Definition 2.6.3** A subset A of R is called compact if for every sequence fang in A, there exists a
subsequence fankg that converges to a point a 2 A

 **Theorem 2.6.5** A subset A of R is compact if and only if it is closed and bounded.
 
 **Definition 2.6.4** (cluster/limit/accumulation point). Let A be a subset of R. A point a 2 R (not
necessarily in A) is called a limit point of A if for any d > 0, the open ball B(a;d) contains an infinite number of points of A.

A point a 2 A which is not an accumulation point of A is called an isolated point of A.
 
 **Theorem 2.6.6** Any infinite bounded subset of R has at least one limit point
 
 **Definition 2.6.5** Let D be a subset of R. We say that a subset V of D is open in D if for every a 2 V, there exists d > 0 such that
$B(a;d)\cap D\subset V$

 **Theorem 2.6.7** Let D be a subset of R. A subset V of D is open in D if and only if there exists an
open subset G of R such that
 $V = D\cap G$
 
 **Theorem 2.6.8** Let D be a subset of R. The following hold:
 
  (a) The subsets /0 and D are open in D.
  (b) The union of any collection of open sets in D is open in D.
  (c) The intersection of a finite number of open sets in D is open in D.

 **Definition 2.6.6** Let D be a subset of R. We say that a subset A of D is closed in D if DnA is open
in D.

 **Theorem 2.6.9** Let D be a subset of R. A subset K of D is closed in D if and only if there exists a
closed subset F of R such that

$K = D\cap F$
 
 **Corollary 2.6.10** Let D be a subset of R. A subset K of D is closed in D if and only if for every
sequence fxkg in K that converges to a point ¯ x 2 D it follows that ¯ x 2 K.
 
 **Theorem 2.6.11** Let D be a subset of R. The following hold:
 
  (a) The subsets /0 and D are closed in D.
  (b) The intersection of any collection of closed sets in D is closed in D.
  (c) The union of a finite number of closed sets in D is closed in D.
 
 
## 3. LIMITS AND CONTINUITY
 3.1. LIMITS OF FUNCTIONS
 
 **Definition 3.1.1** Let f : D!R and let ¯ x be a limit point of D. We say that f has a limit at ¯ x if there exists a real number ` such that for every e > 0, there exists d > 0 with
 
j f (x)`j < e
for all x 2 D for which 0 < jx􀀀 ¯ xj < d. In this case, we write

limx!¯ xf (x) = `:

 **Remark 3.1.1** Note that the limit point ¯ x in the definition of limit may or may not be an element of the domain D. In any case, the inequality j f (x)`j < e need only be satisfied by elements of D.
 
 **Theorem 3.1.2** — Sequential Characterization of Limits. Let f : D!R and let ¯ x be a limit point
of D. Then
limx!¯ xf (x) = ` (3.1)

if and only if
limn!¥f (xn) = ` (3.2)

for every sequence fxng in D such that xn 6= ¯ x for every n and fxng converges to ¯ x.
 
 **Corollary 3.1.3** Let f : D!R and let ¯ x be a limit point of D. If f has a limit at ¯ x, then this limit is unique.
 
 **Corollary 3.1.4** Let f : D!R and let ¯ x be a limit point of D. Then f does not have a limit at ¯ x if and only if there exists a sequence fxng in D such that xn 6= ¯ x for every n, fxng converges to ¯ x, and f f (xn)g does not converge.
 
 **Theorem 3.1.5** Let f , g : D → R and let x¯ be a limit point of D. Suppose that 
 
 lim f (x) = £1, lim g(x) = £2,x→x¯x→x¯

and that there exists δ > 0 such that

f (x) ≤ g(x) for all x ∈ B(x¯; δ ) ∩ D, x /= x¯.

Then £1 ≤ £2.
 
 **Theorem 3.1.6** Let f , g : D → R and let x¯ be a limit point of D. Suppose 
 lim f (x) = £1, lim g(x) = £2,x→x¯x→x¯
and £1 < £2. Then there exists δ > 0 such that
f (x) < g(x) for all x ∈ B(x¯; δ ) ∩ D, x /= x¯.
 
 **Theorem 3.1.7** Let f , g, h : D → R and let x¯ be a limit point of D. Suppose there exists δ > 0 such that f (x) ≤ g(x) ≤ h(x) for all x ∈ B(x¯; δ ) ∩ D, x /= x¯. If limx→x¯ f (x) = limx→x¯ h(x) = £, then limx→x¯ g(x) = £.
 
 **Remark 3.1.8** We will adopt the following convention. When we write limx→x¯ f (x) without speci- fying the domain D of f we will assume that D is the largest subset of R such that if x ∈ D, then f (x) results in a real number. 
 
 3.2. LIMIT THEOREMS
 
 **Definition 3.2.1** Let f ;g: D ! R and let c be a constant. The functions f +g, f g, and c f are
respectively defined as functions from D to R by

(f +g)(x) = f (x)+g(x);

( f g)(x) = f (x)g(x);

(c f )(x) = c f (x)
 
 for x 2 D. Let eD = fx 2 D : g(x) 6= 0g. The function fg is defined as a function from eD to R by 
 fg(x) =f (x)g(x)
for x 2 eD.
 
 **Theorem 3.2.1** Let f ;g: D!R and let c 2 R. Suppose ¯ x is a limit point of D and
limx!¯ xf (x) = `; limx!¯ xg(x) = m:
Then
  (a) limx!¯ x( f +g)(x) = `+m,
  (b) limx!¯ x( f g)(x) = `m,
  (c) limx!¯ x(c f )(x) = c`,
  (d) limx!¯ xfg(x) =mprovided that m 6= 0.
 
 **Theorem 3.2.2** (Cauchy’s criterion) Let f : D!R and let ¯ x be a limit point of D. Then f has a limit at ¯ x if and only if for any e > 0, there exists d > 0 such that
j f (r)􀀀 f (s)j < e whenever r; s 2 D and 0 < jr􀀀 ¯ xj < d;0 < js􀀀 ¯ xj < d:
 
 **Definition 3.2.2** Let a 2 R and d > 0. Define
B􀀀(a;d) = (a􀀀d;a) and B+(a;d) = (a;a+d):

Given a subset A of R, we say that a is a left limit point of A if for any d > 0, B(a;d) contains an infinite number of elements of A. Similarly, a is called a right limit point of A if for any d > 0, B+(a;d) contains an infinite number of elements of A.
 
 **Definition 3.2.3** (One-sided limits) Let f : D!R and let ¯ x be a left limit point of D. We write
limx!¯ x􀀀f (x) = `

if for every e > 0, there exists d > 0 such that

j f (x)`j < e for all x 2 B( ¯ x;d)

We say that ` is the left-hand limit of f at ¯ x. The right-hand limit of f at ¯ x can be defined in a similarway and is denoted limx!¯ x+ f (x).
 
 **Theorem 3.2.3** Let f : D!R and let ¯ x be both a left limit point of D and a right limit point of D.
Then
limx!¯ xf (x) = `
if and only if
limx!¯ x+f (x) = ` and limx!¯ x􀀀f (x) = `:
 
 **Definition 3.2.4** (monotonicity) Let f : (a;b)!R.
  (1) We say that f is increasing on (a;b) if, for all x1;x2 2 (a;b), x1 < x2 implies f (x1)  f (x2).
  (2) We say that f is decreasing on (a;b) if, for all x1;x2 2 (a;b), x1 < x2 implies f (x1)  f (x2).
If f is increasing or decreasing on (a;b), we say that f is monotone on this interval. Strict monotonicity can be defined similarly using strict inequalities: f (x1) < f (x2) in (1) and f (x1) > f (x2) in (2).

 **Theorem 3.2.4** Suppose f : (a;b) ! R is increasing on (a;b) and ¯ x 2 (a;b). Then limx!¯ x􀀀 f (x)
and limx!¯ x+ f (x) exist. Moreover,
supa<x<¯ x
f (x) = limx!¯ x􀀀f (x) f ( ¯ x) limx!¯ x+f (x) = inf¯ x<x<bf (x):
 
 **Definition 3.2.5** (infinite limits) Let f : D!R and let ¯ x be a limit point of D. We write

limx!¯ xf (x) = ¥

if for every M 2 R, there exists d > 0 such that
$f (x) > M for all x 2 B0( ¯ x;d)\D:$

Similarly, we write
$limx!¯ xf (x) = ¥$

if for every M 2 R, there exists d > 0 such that
$f (x) < M for all x 2 B0( ¯ x;d)\D:$
 
 **Definition 3.2.6** (limits at infinity) Let f : D → R, where D is not bounded above. We write 
 
 lim f (x) = £ x→∞
if for every ε > 0, there exists c ∈ R such that
| f (x) − £| < ε for all x > c, x ∈ D.
Let f : D → R, where D is not bounded below. We write
limx→−∞f (x) = £
if for every ε > 0, there exists c ∈ R such that
| f (x) − £| < ε for all x < c, x ∈ D.
We can also define
lim f (x) = ±∞ and limf (x) = ±∞x→∞x→−∞
in a similar way.
 
 3.3. CONTINUITY
 
 **Definition 3.3.1** Let D be a nonempty subset of R and let f : D → R be a function. The function f is said to be continuous at x0 ∈ D if for any real number ε > 0, there exists δ > 0 such that if x ∈ D and |x − x0| < δ , then

| f (x) − f (x0)| < ε.

If f is continuous at every point x ∈ D, we say that f is continuous on D (or just continuous if no confusion occurs).
 
 **Remark 3.3.1** Note that the above definition of continuity does not mention limits. This allows to include in the definition, points x0 2 D which are not limit points of D. If x0 is an isolated point of D, then there is d > 0 such that $B(x0;d)\D = fx0g$. It follows that for $x 2 B(x0;d)\D,j f (x) f (x0)j = 0 < e$ for any epsilon. Therefore, every function is continuous at an isolated point of its domain.
 
 **Theorem 3.3.2** Let f : D → R and let x0 ∈ D be a limit point of D. Then f is continuous at x0 if and only if
lim f (x) = f (x0).x→x0
 
 **Theorem 3.3.3** Let f : D → R and let x0 ∈ D. Then f is continuous at x0 if and only if for any sequence {xk} in D that converges to x0, the sequence { f (xk)} converges to f (x0).
 
 **Theorem 3.3.4** Let f , g : D → R and let x0 ∈ D. Suppose f and g are continuous at x0. Then
  (a) f + g and f g are continuous at x0.
  (b) c f is continuous at x0 for any constant c. f
  (c) If g(x0) /= 0, then g (defined on D- = {x ∈ D : g(x) /= 0}) is continuous at x0.
 
 **Theorem 3.3.5** Let f : D → R and let g : E → R with f (D) ⊂ E. If f is continuous at x0 and g is continuous at f (x0), then g ◦ f is continuous at x0.
 
 3.4. PROPERTIES OF CONTINUOUS FUNCTIONS
 
 **Theorem 3.4.1** Let D be a nonempty compact subset of R and let f : D → R be a continuous function. Then f (D) is a compact subset of R. In particular, f (D) is closed and bounded.
 
 **Definition 3.4.1** We say that the function f : D → R has an absolute minimum at x¯ ∈ D if
f (x) ≥ f (x¯) for every x ∈ D.
Similarly, we say that f has an absolute maximum at x¯ if
f (x) ≤ f (x¯) for every x ∈ D.
 
 **Theorem 3.4.2** — Extreme Value Theorem. Suppose f : D → R is continuous and D is a compact set. Then f has an absolute minimum and an absolute maximum on D.
 
 **Remark 3.4.3** The proof of Theorem 3.4.2 can be shortened by applying Theorem 2.6.4. However, we have provided a direct proof instead.

 **Corollary 3.4.4** If f : [a, b] → R is continuous, then it has an absolute minimum and an absolute maximum on [a, b].
 
 **Lemma 3.4.5** Let f : D → R be continuous at c ∈ D. Suppose f (c) > 0. Then there exists δ > 0 such that

f (x) > 0 for every x ∈ B(c; δ ) ∩ D.
 
 **Remark 3.4.6** An analogous result holds if f (c) < 0.

 **Theorem 3.4.7** Let f : [a, b] → R be a continuous function. Suppose f (a) · f (b) < 0 (this means either f (a) < 0 < f (b) or f (a) > 0 > f (b)). Then there exists c ∈ (a, b) such that f (c) = 0.
 
 **Theorem 3.4.8** — Intermediate Value Theorem. Let f : [a, b] → R be a continuous function. Suppose f (a) < γ < f (b). Then there exists a number c ∈ (a, b) such that f (c) = γ.

The same conclusion follows if f (a) > γ > f (b).
 
 **Corollary 3.4.9** Let f : [a, b] → R be a continuous function. Let
m = min{ f (x) : x ∈ [a, b]} and M = max{ f (x) : x ∈ [a, b]}.
Then for every γ ∈ [m, M], there exists c ∈ [a, b] such that f (c) = γ.
 
 **Theorem 3.4.10** Let f : [a, b] → R be strictly increasing and continuous on [a, b]. Let c = f (a) and d = f (b). Then f is one-to-one, f ([a, b]) = [c, d], and the inverse function f −1 defined on [c, d] by

f −1( f (x)) = x where x ∈ [a, b],

is a continuous function from [c, d] onto [a, b].
 
 **Remark 3.4.11** A similar result holds if the domain of f is the open interval (a, b) with some additional considerations. If f : (a, b) → R is increasing and bounded, following the argument in Theorem 3.2.4 we can show that both limx→a+ f (x) = c and limx→b− f (x) = d exist in R (see Exercise 3.2.10). Using the Intermediate Value Theorem we obtain that f ((a, b)) = (c, d). We can now proceed as in the previous theorem to show that f has a continuous inverse from (c, d) to (a, b).

If : (a, b) → R is increasing, continuous, bounded below, but not bounded above, then limx→a+ f (x) = c ∈ R, but limx→b− f (x) = ∞ (again see Exercise 3.2.10). In this case we can show using the Inter- mediate Value Theorem that f ((a, b)) = (c, ∞) and we can proceed as above to prove that f has a continuous inverse from (c, ∞) to (a, b).
 
 3.5. UNIFORM CONTINUITY
 
 **Definition 3.5.1** Let D be a nonempty subset of R. A function f : D → R is called uniformly continuous on D if for any ε > 0, there exists δ > 0 such that if u, v ∈ D and |u − v| < δ , then

| f (u) − f (v)| < ε.

 **Theorem 3.5.1** If f : D → R is uniformly continuous on D, then f is continuous at every point x0 ∈ D

Definition 3.5.2 (Hölder continuity). Let D be a nonempty subset of R. A function f : D → R is said to be Hölder continuous if there are constants £ ≥ 0 and α > 0 such that

| f (u) − f (v)| ≤ £|u − v|α for every u, v ∈ D.

The number α is called the Hölder exponent of the function. If α = 1, then the function f is called Lipschitz continuous.

 **Theorem 3.5.2** If a function f : D → R is Hölder continuous, then it is uniformly continuous.
 
 **Theorem 3.5.3** Let D be a nonempty subset of R and f : D → R. Then f is uniformly continuous on D if and only if the following condition holds (C) for every two sequences {un}, {vn} in D such that limn→∞(un − vn) = 0, it follows that limn→∞( f (un) − f (vn)) = 0.
 
 **Theorem 3.5.4** Let f : D → R be a continuous function. Suppose D is compact. Then f is uniformly continuous on D.
 
 **Theorem 3.5.5** Let a, b ∈ R and a < b. A function f : (a, b) → R is uniformly continuous if and only if f can be extended to a continuous function
f˜: [a, b] → R (that is, there is a continuous
|(a,b)
function f˜: [a, b] → R such that f = f˜ ).
|(a,b)
 
 3.6. LIMIT SUPERIOR AND LIMIT INFERIOR OF FUNCTIONS
 
 **Definition 3.6.1** Let f : E !R and let ¯ x be a limit point of D. Recall that
B0( ¯ x;d) = B􀀀( ¯ x;d)[B+( ¯ x;d) = ( ¯ x􀀀d; ¯ x)[( ¯ x; ¯ x+d):

The limit superior of the function f at ¯ x is defined by
$limsupx!¯ xf (x) = infd>0supx2B0( ¯ x;d)\Df (x):$

Similarly, the limit inferior of the function f at ¯ x is defined by
$liminfx!¯ xf (x) = supd>0infx2B0( ¯ x;d)\Df (x):$
 
 **Theorem 3.6.1** Let f : D → R and let x¯ be a limit point of D. Then £ = lim supx→x¯ f (x) if and only if the following two conditions hold:
  (1) For every ε > 0, there exists δ > 0 such that
f (x) < £ + ε for all x ∈ B0(x¯; δ ) ∩ D;
  (2) For every ε > 0 and for every δ > 0, there exists xδ ∈ B0(x¯; δ ) ∩ D such that
£ − ε < f (xδ ).
 
 **Corollary 3.6.2** Suppose £ = lim supx→x¯ f (x). Then there exists a sequence {xk} in D such that
{xk} converges to x¯, xk /= x¯ for every k, and

lim f (xk) = £.k→∞

Moreover, if {yk} is a sequence in D that converges to x¯, yk /= x¯ for every k, and limk→∞ f (yk) = £1, then £1 ≤ £.
 
 **Remark 3.6.3** Let f : D → R and let x¯ be a limit point of D. Suppose lim supx→x¯ f (x) is a real number. Define
A = {£ ∈ R : ∃{xk} ⊂ D, xk /= x¯ for every k, xk → x¯, f (xk) → £}.
Then the previous corollary shows that A /= 0/ and lim supx→x¯ f (x) = max A.

 **Theorem 3.6.4** Let f : D → R and let x¯ be a limit point of D. Then
lim sup f (x) = ∞x→x¯
if and only if there exists a sequence {xk} in D such that {xk} converges to x¯, xk /= x¯ for every k, and limk→∞ f (xk) = ∞.
 
 **Theorem 3.6.5** Let f : D → R and let x¯ be a limit point of D. Then

lim sup f (x) = −∞x→x¯

if and only if for any sequence {xk} in D such that {xk} converges to x¯, xk /= x¯ for every k, it follows that limk→∞ f (xk) = −∞. The latter is equivalent to limx→x¯ f (x) = −∞.

 **Theorem 3.6.6** Let f : D → R and let x¯ be a limit point of D. Then £ = lim infx→x¯ f (x) if and only if the following two conditions hold:
  (1) For every ε > 0, there exists δ > 0 such that
£ − ε < f (x) for all x ∈ B0(x¯; δ ) ∩ D;

  (2) For every ε > 0 and for every δ > 0, there exists x ∈ B0(x¯; δ ) ∩ D such that
f (x) < £ + ε.

 **Corollary 3.6.7** Suppose £ = lim infx→x¯ f (x). Then there exists a sequence {xk} in D such that xk converges to x¯, xk /= x¯ for every k, and
lim f (xk) = £.k→∞

Moreover, if {yk} is a sequence in D that converges to x¯, yk /= x¯ for every k, and limk→∞ f (yk) = £1, then £1 ≥ £.

 **Remark 3.6.8** Let f : D → R and let x¯ be a limit point of D. Suppose lim infx→x¯ f (x) is a real number. Define
B = {£ ∈ R : ∃{xk} ⊂ D, xk /= x¯ for every k, xk → x¯, f (xk) → £}.

Then B /= 0/ and lim infx→x¯ f (x) = min B.

 **Theorem 3.6.9** Let f : D → R and let x¯ be a limit point of D. Then
−lim inf f (x) = ∞x→x¯
if and only if there exists a sequence {xk} in D such that {xk} converges to x¯, xk /= x¯ for every k, and limk→∞ f (xk) = −∞.

 **Theorem 3.6.10** Let f : D → R and let x¯ be a limit point of D. Then
lim inf f (x) = ∞x→x¯

if and only if for any sequence {xk} in D such that {xk} converges to x¯, xk /= x¯ for every k, it follows that limk→∞ f (xk) = ∞. The latter is equivalent to limx→x¯ f (x) = ∞.

 **Theorem 3.6.11** Let f : D → R and let x¯ be a limit point of D. Then limx→x¯ f (x) = £
if and only if
lim sup f (x) = lim inf f (x) = £.x→x¯x→x¯
 
 3.7. LOWER SEMICONTINUITY AND UPPER SEMICONTINUITY
 
 **Definition 3.7.1** Let f : D → R and let x¯ ∈ D. We say that f is lower semicontinuous (l.s.c.) at x¯ if for every ε > 0, there exists δ > 0 such that
f (x¯) − ε < f (x) for all x ∈ B(x¯; δ ) ∩ D. (3.12)

Similarly, we say that f is upper semicontinuous (u.s.c.) at x¯ if for every ε > 0, there exists δ > 0 such that
f (x) < f (x¯) + ε for all x ∈ B(x¯; δ ) ∩ D.
It is clear that f is continuous at x¯ if and only if f is lower semicontinuous and upper semicontin- uous at this point.
 
 **Theorem 3.7.1** Let f : D → R and let x¯ ∈ D be a limit point of D. Then f is lower semicontinuous at x¯ if and only if

lim inf f (x)≥ f (x¯).x→x¯

Similarly, f is upper semicontinuous at x¯ if and only if
lim sup f (x) ≤ f (x¯).x→x¯
 
 **Theorem 3.7.2** Let f : D → R and let x¯ ∈ D. Then f is l.s.c. at x¯ if and only if for every sequence
{xk} in D that converges to x¯,

lim inf f (xk) ≥ f (x¯).k→∞

Similarly, f is u.s.c. at x¯ if and only if for every sequence {xk} in D that converges to x¯,

lim sup f (xk) ≤ f (x¯).
 
 **Definition 3.7.2** Let f : D → R. We say that f is lower semicontinuous on D (or lower semicontinu- ous if no confusion occurs) if it is lower semicontinuous at every point of D.

 **Theorem 3.7.3** Suppose D is a compact set of R and f : D → R is lower semicontinuous. Then f has an absolute minimum on D. That means there exists x¯ ∈ D such that
f (x) ≥ f (x¯) for all x ∈ D.

Theorem 3.7.4 Suppose D is a compact subset of R and f : D → R is upper semicontinuous. Then f has an absolute maximum on D. That is, there exists x¯ ∈ D such that

f (x) ≤ f (x¯) for all x ∈ D.
For every a ∈ R, define
La( f ) = {x ∈ D : f (x) ≤ a}
and
Ua( f ) = {x ∈ D : f (x) ≥ a}.

 **Theorem 3.7.5** Let f : D → R. Then f is lower semicontinuous if and only if La( f ) is closed in D for every a ∈ R. Similarly, f is upper semicontinuous if and only if Ua( f ) is closed in D for every a ∈ R.
 
 **Corollary 3.7.6** Let f : D → R. Then f is lower semicontinuous if and only if Ua( f ) is open in D for every a ∈ R. Similarly, f is upper semicontinuous if and only if La( f ) is open in D for every a ∈ R.

 **Theorem 3.7.7** Let f : D → R. Then f is continuous if and only if for every a, b ∈ R with a < b, the set
Oa,b = {x ∈ D : a < f (x) < b} = f −1((a, b))
is an open set in D.
 
## 4. DIFFERENTIATION
 4.1 DEFINITION AND BASIC PROPERTIES OF THE DERIVATIVE
 
 Let G be an open subset of R and consider a function f : G!R. For every a 2 G, the function
fa(x) =f (x) f (a)xa
is defined on Gn fag. Since G is an open set, a is a limit point of Gn fag (see Example 2.6.6). Thus, it is possible to discuss the limit
 
 limx!afa(x) = limx!af (x) f (a)xa:
 
 **Definition 4.1.1** Let G be an open subset of R and let a 2 G. We say that the function f defined on G is differentiable at a if the limit
limx!af (x) f (a)xa
exists (as a real number). In this case, the limit is called the derivative of f at a denoted by f 0(a), and f is said to be differentiable at a. Thus, if f is differentiable at a, then

f 0(a) = limx!af (x) f (a)xa:

We say that f is differentiable on G if f is differentiable at every point a 2 G. In this case, the function f 0 : G!R is called the derivative of f on G.
 
 **Theorem 4.1.1** Let G be an open subset of R and let f be defined on G. If f is differentiable at a 2 G, then f is continuous at this point.
 
 **Remark 4.1.2** The converse of Theorem 4.1.1 is not true. For instance, the absolute value function f (x) = jxj is continuous at 0, but it is not differentiable at this point (as shown in the example above).

 **Theorem 4.1.3** Let G be an open subset of R and let f ;g: G ! R. Suppose both f and g are differentiable at a 2 G. Then the following hold.
 
  (a) The function f +g is differentiable at a and
  
( f +g)0(a) = f 0(a)+g0(a):

  (b) For a constant c, the function c f is differentiable at a and
  
(c f )0(a) = c f 0(a):
 
  (c) The function f g is differentiable at a and
  
( f g)0(a) = f 0(a)g(a)+ f (a)g0(a):

  (d) Suppose additionally that g(a) 6= 0. Then the function fg is differentiable at a and
  
fg0(a) =f 0(a)g(a)􀀀 f (a)g0(a)(g(a))2 :
 
 **Lemma 4.1.4** Let G be an open subset of R and let f : G!R. Suppose f is differentiable at a.
Then there exists a function u: G!R satisfying

$f (x) f (a) = [ f 0(a)+u(x)](xa) for all x 2 G$
and limx!a u(x) = 0.

 **Theorem 4.1.5** — Chain rule. Let f : G1 !R and let g: G2 !R, where G1 and G2 are two open subsets of R with f (G1)  G2. Suppose f is differentiable at a and g is differentiable at f (a). Then
the function g  f is differentiable at a and
$(g  f )0(a) = g0( f (a)) f 0(a):$

 **Definition 4.1.2** Let G be an open set and let f : G!R be a differentiable function. If the function
f 0 : G!R is also differentiable, we say that f is twice differentiable (on G). The second derivative
of f is denoted by f 00 or f (2). Thus, f 00 = ( f 0)0. Similarly, we say that f is three times differentiable
if f (2) is differentiable, and ( f (2))0 is called the third derivative of f and is denoted by f 000 or f (3).
We can define in this way n times differentiability and the nth derivative of f for any positive integer
n. As a convention, f (0) = f .

 **Definition 4.1.3** Let I be an open interval in R and let f : I ! R. The function f is said to be
continuously differentiable if f is differentiable on I and f 0 is continuous on I. We denote by C1(I)
the set of all continuously differentiable functions on I. If f is n times differentiable on I and the nth
derivative is continuous, then f is called n times continuously differentiable. We denote by Cn(I) the
set of all n times continuously differentiable functions on I.

 4.2 THE MEAN VALUE THEOREM
 
 **Definition 4.2.1** Let D be a nonempty subset of R and let f : D!R. We say that f has a local (or
relative) minimum at a 2 D if there exists d > 0 such that

$f (x)  f (a) for all x 2 B(a;d)\D:$

Similarly, we say that f has a local (or relative) maximum at a 2 D if there exists d > 0 such that
$f (x)  f (a) for all x 2 B(a;d)\D:$

In January 1638, Pierre de Fermat described his method for finding maxima and minima in a letter written to Marin Mersenne (1588–1648) who was considered as “the center of the world of
science and mathematics during the first half of the 1600s.” His method presented in the theorem below is now known as Fermat’s Rule.
 
 **Theorem 4.2.1** —Fermat’s Rule. Let I be an open interval and f : I!R. If f has a local minimum or maximum at a 2 I and f is differentiable at a, then f 0(a) = 0.
 
 **Theorem 4.2.2** — Rolle’s Theorem. Let a;b 2 R with a < b and f : [a;b] ! R. Suppose f is continuous on [a;b] and differentiable on (a;b) with f (a) = f (b). Then there exists c 2 (a;b) such
that
f 0(c) = 0:
 
 **Theorem 4.2.3** — Mean Value Theorem. Let a;b 2 R with a < b and f : [a;b]!R. Suppose f is continuous on [a;b] and differentiable on (a;b). Then there exists c 2 (a;b) such that
f 0(c) = f (b) f (a)ba:
 
 **Theorem 4.2.4** — Cauchy’s Theorem. Let a;b 2 R with a < b. Suppose f and g are continuous
on [a;b] and differentiable on (a;b). Then there exists c 2 (a;b) such that
[ f (b) f (a)]g0(c) = [g(b)g(a)] f 0(c):

 **Definition 4.2.2** Let a;b 2 R, a < b, and f : [a;b]!R. If the limit
limx!a+f (x) f (a)xa 

exists, we say that f has a right derivative at a and write

f0+(a) = limx!a+f (x) f (a)xa:

If the limit

limx!bf (x) f (b)xb

exists, we say that f has a left derivative at b and write

f0(b) = limx!bf (x) f (b)xb:

We will say that f is differentiable on [a;b] if f 0(x) exists for each x 2 (a;b) and, in addition, both

f0+(a) and f0(b) exist.

 **Theorem 4.2.5** — Intermediate Value Theorem for Derivatives. Let a;b 2 R with a < b. Suppose f is differentiable on [a;b] and
 
f0+ (a) < l < f0(b):

Then there exists c 2 (a;b) such that

f 0(c) = l:
 
 **Remark 4.2.6** The same conclusion follows if f0+(a) > l > f0(b).
 
 4.3 SOME APPLICATIONS OF THE MEAN VALUE THEOREM
 
 **Proposition 4.3.1** Let f be continuous on [a;b] and differentiable on (a;b). If f 0(x) = 0 for all x 2 (a;b), then f is constant on [a;b].
 
 **Proposition 4.3.2** Let f be differentiable on (a;b).
  (i) If f 0(x) > 0 for all x 2 (a;b), then f is strictly increasing on (a;b).
  (ii) If f 0(x) < 0 for all x 2 (a;b), then f is strictly decreasing on (a;b).
 
 **Theorem 4.3.3** — Inverse Function Theorem. Suppose f is differentiable on I = (a;b) and f 0(x) 6= 0 for all x 2 (a;b). Then f is one-to-one, f (I) is an open interval, and the inverse function
f 1 : f (I)!I is differentiable. Moreover,
( f 1)0(y) =1f 0(x);
where f (x) = y.
 
 4.4 L’HOSPITAL’S RULE
 
 **Theorem 4.4.1** Suppose f and g are continuous on [a;b] and differentiable on (a;b). Suppose f ( ¯ x) = g( ¯ x) = 0, where ¯ x 2 [a;b]. Suppose further that there exists d > 0 such that g0(x) 6= 0 for all $x 2 B( ¯ x;d)\[a;b], x 6= ¯ x$.
If
limx!¯ xf 0(x)g0(x)= `;

then
limx!¯ xf (x)g(x)= `:
 
 **Theorem 4.4.2** Let a;b 2 R, a < b, and ¯ x 2 (a;b). Suppose f ;g: (a;b)nf ¯ xg!R are differentiable on (a;b) n f ¯ xg and assume limx!¯ x f (x) = limx!¯ x g(x) = ¥. Suppose further that there exists d > 0 such that g0(x) 6= 0 for all $x 2 B( ¯ x;d)\(a;b), x 6= ¯ x$.
If ` 2 R and

limx!¯ xf 0(x)g0(x)= `; (4.10)

then
limx!¯ xf (x)g(x)= `:

 **Remark 4.4.3** The proofs of Theorem 4.4.1 and Theorem 4.4.2 show that the results in these theorems can be applied for left-hand and right-hand limits. Moreover, the results can also be modified to include the case when ¯ x is an endpoint of the domain of the functions f and g.

 **Theorem 4.4.4** Let f and g be differentiable on (a;¥). Suppose g0(x) 6= 0 for all x 2 (a;¥) and

limx!¥f (x) = limx!¥g(x) = 0:

If ` 2 R and

limx!¥f 0(x)g0(x)= `;

then
limx!¥f (x)g(x)= `:

 **Theorem 4.4.5** Let f and g be differentiable on (a;¥). Suppose g0(x) 6= 0 for all x 2 (a;¥) and
limx!¥f (x) = limx!¥g(x) = ¥:
If ` 2 R and
limx!¥f 0(x)g0(x)= `;
then
limx!¥f (x)g(x)= `:
 
 4.5 TAYLOR’S THEOREM
 
 **Theorem 4.5.1** — Taylor’s Theorem. Let n be a positive integer. Suppose f : [a;b] ! R is a function such that f (n) is continuous on [a;b], and f (n+1)(x) exists for all x 2 (a;b). Let ¯ x 2 [a;b].
Then for any x 2 [a;b] with x 6= ¯ x, there exists a number c in between ¯ x and x such that
f (x) = Pn(x)+f (n+1)(c)(n+1)!(x􀀀 ¯ x)n+1;

where
Pn(x) =nåk=0f (k)( ¯ x)k!(x ¯ x)k:
 
 **Remark 4.5.2** The conclusion of Taylor’s theorem still holds true if x = ¯ x. In this case, c = x = ¯ x.
 
 **Theorem 4.5.3** Let n be an even positive integer. Suppose f (n) exists and continuous on (a;b). Let ¯ x 2 (a;b) satisfy
f 0( ¯ x) = : : : = f (n􀀀1)( ¯ x) = 0 and f (n)( ¯ x) 6= 0:
The following hold:
 
 (a) f (n)( ¯ x) > 0 if and only if f has a local minimum at ¯ x.
 (b) f (n)( ¯ x) < 0 if and only if f has a local maximum at ¯ x.
 
 4.6 CONVEX FUNCTIONS AND DERIVATIVES
 
 **Definition 4.6.1** Let I be an interval of R and let f : I !R. We say that f is convex on I if
f (lu+(1l)v) l f (u)+(1l) f (v)
for all u;v 2 I and for all l 2 (0;1).
 
 **Theorem 4.6.1** Let I be an interval of R. A function f : I !R is convex if and only if for every li  0, i = 1; : : : ;n; with åni=1 li = 1 (n 2) and for every xi 2 I, i = 1; : : : ;n,

fnåi=1lixi!nå i=1 li f (xi):
 
 **Theorem 4.6.2** Let I be an interval and let f : I ! R be a convex function. Then f has a local minimum at ¯ x if and only if f has an absolute minimum at ¯ x.
 
 **Theorem 4.6.3** Let I be an open interval and let f : I ! R be a convex function. Suppose f is differentiable at ¯ x. Then
f 0( ¯ x)(x ¯ x) f (x)􀀀 f ( ¯ x) for all x 2 I:
 
 **Corollary 4.6.4** Let I be an open interval and let f : I ! R be a convex function. Suppose f is differentiable at ¯ x. Then f has an absolute minimum at ¯ x if and only if f 0( ¯ x) = 0.
 
 **Lemma 4.6.5** Let I be an open interval and suppose f : I !R is a convex function. Fix a;b;x 2 I with a < x < b. Then

f (x) f (a)xaf (b) f (a)baf (b) f (x)bx:
 
 **Theorem 4.6.6** Let I be an open interval and let f : I !R be a differentiable function. Then f is convex if and only if f 0 is increasing on I.
 
 **Corollary 4.6.7** Let I be an open interval and let f : I ! R be a function. Suppose f is twice differentiable on I. Then f is convex if and only if f 00(x)  0 for all x 2 I.
 
 **Theorem 4.6.8** Let I be an open interval and let f : I !R be a convex function. Then it is locally Lipschitz continuous in the sense that for any ¯ x 2 I, there exist ` 0 and d > 0 such that
 
 j f (u)􀀀 f (v)j `ju􀀀vj for all u;v 2 B( ¯ x;d):
 
 4.7 NONDIFFERENTIABLE CONVEX FUNCTIONS AND SUBDIFFERENTIALS

 **Definition 4.7.1** Let f : R!R be a convex function. A number u 2 R is called a subderivative of the function f at ¯ x if
u  (x ¯ x) f (x) f ( ¯ x) for all x 2 R:

The set of all subderivatives of f at ¯ x is called the subdifferential of f at ¯ x and is denoted by ¶ f ( ¯ x):

 **Lemma 4.7.1** Let f : R!R be a convex function. Fix a 2 R. Define the slope function fa by
fa(x) =f (x) f (a)xa

for x 2 (¥;a)[(a;¥). Then, for x1;x2 2 (¥;a)[(a;¥) with x1 < x2, we have
fa(x1) fa(x2):

 **Theorem 4.7.2** Let f : R!R be a convex function and let ¯ x 2 R. Then f has left derivative and right derivative at ¯ x. Moreover,
supx<¯ xf¯ x(x) = f0( ¯ x) f0+( ¯ x) = infx>¯ xf¯ x(x);

 **Theorem 4.7.3** Let f : R!R be a convex function and let ¯ x 2 R. Then
 
¶ f ( ¯ x) = [ f0( ¯ x); f0+( ¯ x)]:

 **Corollary 4.7.4** Let f : R!R be a convex function and ¯ x 2 R. Then f is differentiable at ¯ x if and only if ¶ f ( ¯ x) is a singleton. In this case,

¶ f ( ¯ x) = f f 0( ¯ x)g:


 **Definition 4.7.2** Let A and B be two nonempty subsets of R and let a 2 R. Define 
 
 A+B = fa+b : a 2 A;b 2 Bg and aA = faa : a 2 Ag:
 
 **Theorem 4.7.5** Let f ;g: R!R be convex functions and let a > 0. Then f +g and a f are convex functions and
¶ ( f +g)( ¯ x) = ¶ f ( ¯ x)+¶g( ¯ x)
¶ (a f )( ¯ x) = a¶ f ( ¯ x):

 **Theorem 4.7.6** Let fi : R!R, i = 1; : : : ;n, be convex functions. Define f (x) = maxf fi(x) : i = 1; : : : ;ng and I(u) = fi = 1; : : : ;n : fi(u) = f (u)g:

Then f is a convex function. Moreover,

¶ f ( ¯ x) = [m;M];

where

m = mini2I( ¯ x)f 0i( ¯ x) and M = maxi2I( ¯ x)f 0i+( ¯ x):

 **Remark 4.7.7** The product of two convex functions is not a convex function in general. For instance, f (x) = x and g(x) = x2 are convex functions, but h(x) = x3 is not a convex function.
The following result may be considered as a version of the first derivative test for extrema in the case of non differentiable functions.

 **Theorem 4.7.8** Let f : R!R be a convex function. Then f has an absolute minimum at ¯ x if and only if
0 2 ¶ f ( ¯ x) = [ f0( ¯ x); f0+( ¯ x)]:

 **Theorem 4.7.9** Let f : R!R be a convex function and let a < b. Then there exists c 2 (a;b) such that
f (b) f (a)ba2 ¶ f (c):

 **Corollary 4.7.10** Let f : R!R be a convex function. Then f is Lipschitz continuous if and only if there exists `  0 such that
¶ f (x)  [`; `] for all x 2 R: