---
title: 'STAT565 Practise'
author: ""
date: "Winter 2019"
output: html_document
---


### Problem 1 

A partial ANOVA table was found to be

|Source|DF|SS|MS|F|
| ---  | ---  | --- | --- | --- |
|Factor|4 |987.71 |246.9275|33.09488|
|Error |25|186.53 |7.4612|   
|Total |29|1174.24|

(1) Complete the ANOVA table.



1174.24-186.53=987.71

(987.71/4)/(186.53/25)

(2) If it was a balanced design, what was number of levels for the factor in this study?
$df_{Trt}=29-25=4$,$a=5

(3) If it was a balanced design, what was the number of observations for each factor level in this study?
$n=6$

(4) Write the overall hypotheses for this test.
H0: $\mu_1=\mu_2=\mu_3=\mu_4=\mu_5$, or $\tau_1=\tau_2=\tau_3=\tau_4=\tau_5=0$
H1: at least two of $\mu_i$ are different, or at least one of $\tau_i\neq0$

(5) Write the name of probability distribution along with its parameter value(s) used to test the above overall hypotheses.
$F_{(df_{Trt}=4,df_E=25)}=\frac{MS_{Trt}}{MS_{E}}$

(6) Compute the standard error of the difference of two observed treatment means. (that is, compute $se(\bar y _{i.}-\bar y_{j.}))$).

$$se(\bar y _{i.}-\bar y_{j.})=\sqrt{\frac{2MSE}n}=\sqrt{\frac{2\times7.4612}6}=1.577044$$

(7) If you were to compute 95% confidence interval for the difference of two true treatment means, provide the name and its parameter value(s) of the probability distribution.
$T_{(\frac{0.05}2),df_E=25}$

### Problem 2 

A nutrition specialist is measuring the amount of patty acid present in blood when four different diets are used. Initially, forty subjects (uniform with respect to the fatty acid) were obtained and 10 were randomly assigned to each diet. After 3 week period, the fatty acid in their blood was measured. The following table gives numerical summaries for each diet group.

| Diet| A  |  B  | C  | D  |
| ----| ---| --- |--- |--- |
| Mean|21.3|28.6 |25.7|20.4|

|Source of Variance|Sum of Squares(SS)|Degrees of Freedom(df)|Mean Squares(MS)|F test|
| --- | ---  | --- | --- | --- |
|Diet |443   |3 |147.6667||
|Error|11.91 |36|0.3308|   
|Total|454.91|39|

 (1) Complete the ANOVA table. (keep maximum of 4 decimal places)
 
$\bar y_{..}=\frac{1}a\sum^a_{i=1}\bar y_{i.}=\frac{1}4(21.3+28.6+25.7+20.4=96)=24$

$SS_{Trt}=n\sum^a_{i=1}(\bar y_{i.}−\bar y_{..})^2=10*((21.3-24)^2+(28.6-24)^2+(25.7-24)^2+(20.4-24)^210*44.3)=443$; 

$SS_{T}=SS_{Trt}+SS_{E}=443+11.91=454.91$;

$MS_{Trt}=\frac{SS_{Trt}}{a-1}=\frac{443}3=147.6667$; 

$MS_{E}=\frac{SS_{E}}{N-a}=\frac{11.91}{36}=0.3308333$;

 (2) If the diet effect was fixed, then
  (a) Write the overall hypotheses for this test.
  H0: $\mu_A=\mu_B=\mu_C=\mu_D$, or $\tau_A=\tau_B=\tau_C=\tau_D=0$
  H1: at least two of $\mu_i$ are different or at least one $\tau_i=0$.
  
  (b) Write the name of probability distribution along with its parameter value(s) used to test the above overall hypotheses.
  $F_{(df_{Trt}=3,df_E=36)}=\frac{MS_{Trt}}{MS_{E}}$
  
  (c) Compute the estimated variance of observed average fatty acid amount for each diet.
  $\widehat{Var(\bar y_{i.})}=\frac{MS_{E}}n=0.3308/10=0.0331$
  
  (d) If you were to compute 95% confidence interval for the true mean of each treatment, provide the name and its parameter value(s) of the probability distribution.
  $T_{\frac{0.05}2,df_E=36)}$
  
  (e) Write a contrast to test the average fatty acid for diets A, B is same as average fatty acid for diets C, D.
  $\mu_A+\mu_B-\mu_C-\mu_D=0$
  
  (f) Write the probability distribution along with its parameter(s) used to test the above contrast.
  $F_{(df_{C}=1,df_E=36)}=\frac{(\sum_{i=1}^ac_i\bar y_{i.})^2}{\frac{MS_{E}}n\sum_{i=1}^ac_i^2}$
  
  (g) Write a contrast that is orthogonal to the above contrast.
  $\mu_A-\mu_B+\mu_C-\mu_D=0$
  
  (h) Compute the SS for each of the above contrasts. (Final answer is a number).
  $$SS_C=\frac{(\sum_{i=1}^ac_i\bar y_i)^2}{\frac{1}n\sum_{i=1}^ac_i^2}=\frac{(21.3+28.6-25.7-20.4)^2}{\frac{1}{10}4}=36.1$$
  $$SS_D=\frac{(\sum_{i=1}^ad_i\bar y_i)^2}{\frac{1}n\sum_{i=1}^ad_i^2}==\frac{(21.3-28.6+25.7-20.4)^2}{\frac{1}{10}4}=10$$
  
  
 (3) If the diet effect was random, then
  (a) Write the overall hypotheses for this test.
  H0: $\sigma_{\tau}^2=0$, $E[MS_{Trt}]=\sigma^2$
  H1: $\sigma_{\tau}^2>0$.
  
  (b) Write the name of probability distribution along with its parameter value(s) used to test the above overall hypotheses.
    $F_{(df_{Trt}=3,df_E=36)}=\frac{MS_{Trt}}{MS_{E}}$
  
  (c) Compute the estimated variance of observed average fatty acid amount for each diet.
  $\widehat{Var(\bar y_{i.})}=\sigma_{\tau}^2+\frac{\sigma^2}{n}=\frac{MS_{Trt}-MS_E}n+\frac{MS_{E}}n=\frac{MS_{Trt}}n=147.6667/10=14.76667$

 ---

### Problem 3 The partial ANOVA table given below was obtained from a balanced RCBD.

|Source of Variance|Sum of Squares(SS)|Degrees of Freedom(df)|Mean Squares(MS)|F test|
| --- | ---  | --- | --- | --- |
|Trt   | 150 | 4|37.5|3.75|
|Block | 200 | 5|40  |4|
|Error | 200 |20|10  |   
|Total | 550 |29|

 (1) Complete the ANOVA table.
 (2) What was the number of blocks in this study? 6
 (3) What was the total number of observations in this study? 30
 (4) If treatment and block effects were fixed,
  (a) compute the estimated error variance. $\hat\sigma^2=MSE=10$
  
  (b) write the overall hypotheses about treatments for this study. 
  H0: $\mu_1=\mu_2=\mu_3=\mu_4=\mu_5$, or $\tau_1=\tau_2=\tau_3=\tau_4=\tau_5=0$
  H1: at least two of $\mu_i$ are different, or at least one $\tau\neq0$.
  
  (c) write the name of probability distribution along with its parameter value(s) used to test the above hypothesis. $F_{(df_{Trt}=4,df_E=20)}=\frac{SS_{Trt}}{SS_E}$
  (d) write the overall hypothesis about blocks for this study. H0: $\beta_1=\beta_2=\beta_3=\beta_4=\beta_5=\beta_6=0$
  (e) write the name of probability distribution along with its parameter value(s) used to test the above hypothesis. $F_{(df_{Blk}=5,df_E=20)}=\frac{SS_{Blk}}{SS_E}$
  
 (5) If treatment effect was fixed and block effect was random,
  (a) compute the estimated variance for blocks.$\hat\sigma_{Blk}^2=MS_{Blk}=40$
  
  (b) write the overall hypothesis about treatments for this study.
  H0: $\mu_1=\mu_2=\mu_3=\mu_4=\mu_5$, or $\tau_1=\tau_2=\tau_3=\tau_4=\tau_5=0$
  H1: at least two of $\mu_i$ are differentor at least one $\tau\neq0$.
  
  (c) write the name of probability distribution along with its parameter value(s) used to test the above hypothesis.
  $F_{(df_{Trt}=4,df_E=20)}=\frac{SS_{Blk}}{SS_E}$
  
  (d) write the overall hypothesis about blocks for this study.
  H0: $\sigma_{\beta}^2=0$, $E[MS_{Blk}]=\sigma^2$
  H1: $\sigma_{\beta}^2>0$.
  
  (e) write the name of probability distribution along with its parameter value(s) used to test the above hypothesis.
  $F_{(df_{Blk}=5,df_E=20)}=\frac{SS_{Blk}}{SS_E}$
  
 ---

### Problem 4,5,6,7

Note: For the given model in each of the following four problems, be able to derive the normal equations from the least squares parameter estimation method. Using ONLY the above given information and properties of expected value of a function of random variables, compute (DO NOT use any other distribution properties). $ε_{ij}$,$\tau_i$,$\beta_j$ are independent.

|      |$y_{ij}$|$i$|$j$|$ε_{ij}$|$\tau_i$|$\beta_j$|$\bar y_{i.}$|$\bar y_{.j}$|$\bar y_{..}$|
| ---  |   ---  |---|---|   ---  | ---    | ---     | ---         | ---         | ---         |
|f-CRD |$\mu+\tau_{i}+ε_{ij}$|$1,..,a$|$1,..,n$|$N(0,σ^2)$|$\sum_{i=1}^a\tau_i=0$|.|$\frac{\sum_{j=1}^ny_{ij}}n$|.|$\frac{\sum_{i=1}^a\sum_{j=1}^ny_{ij}}{an}$|
|r-CRD |$\mu+\tau_{i}+ε_{ij}$|$1,..,a$|$1,..,n$|$N(0,σ^2)$|$N(0,σ_{\tau}^2)$|.|$\frac{\sum_{j=1}^ny_{ij}}n$|.|$\frac{\sum_{i=1}^a\sum_{j=1}^ny_{ij}}{an}$|
|f-RCBD|$\mu+\tau_{i}+\beta_j+ε_{ij}$|$1,..,a$|$1,..,b$|$N(0,σ^2)$|$\sum_{i=1}^a\tau_i=0$|$\sum_{j=1}^b\beta_j=0$|$\frac{\sum_{j=1}^by_{ij}}b$|$\frac{\sum_{i=1}^ay_{ij}}a$|$\frac{\sum_{i=1}^a\sum_{j=1}^by_{ij}}{ab}$|
|r-RCBD|$\mu+\tau_{i}+\beta_j+ε_{ij}$|$1,..,a$|$1,..,b$|$N(0,σ^2)$|$\sum_{i=1}^a\tau_i=0$|$N(0,σ_{\beta}^2)$|$\frac{\sum_{j=1}^by_{ij}}b$|$\frac{\sum_{i=1}^ay_{ij}}a$|$\frac{\sum_{i=1}^a\sum_{j=1}^by_{ij}}{ab}$|

 ---
 
For a fixed treatment effect CRD, $\mu$ is a constant, $\tau_i$ is a constant of the $i^{th}$ treatment; 

For a random treatment effects CRD, $\mu$ is a constant, $E[\tau_i]=0$, $Var[\tau_i]=\sigma_{\tau}^2$; 

For a fxed Block effects RCBD, $\mu$ and $\tau_i$ are constants, $\beta_j$ is a constant of the $j^{th}$ block; 

For a random Block effects RCBD, $\mu$and $\tau_i$ are constants, $E[\beta_j]=0$, $Var[\beta_j]=\sigma_{\beta}^2$; 

|$y_{ij}-\bar y_{i.}$|||||
| ---                |   ---  |---|---|   ---  |
|FT-CRD |$\mu+\tau_{i}+ε_{ij}-\frac{\sum_{j=1}^n(\mu+\tau_{i}+ε_{ij})}n$|$=\mu+\tau_{i}+ε_{ij}-\mu-\tau_{i}-\frac{\sum_{j=1}^nε_{ij}}n$|$=$|$ε_{ij}-\frac{\sum_{j=1}^nε_{ij}}n$
|RT-CRD | | | | |
|FB-RCBD|$\mu+\tau_{i}+\beta_j+ε_{ij}-\frac{\sum_{j=1}^b(\mu+\tau_{i}+\beta_j+ε_{ij})}b$|$\mu+\tau_{i}+\beta_j+ε_{ij}-\mu-\tau_{i}-0-\frac{ \sum_{j=1}^bε_{ij}}b$|$=\beta_j+$|$ε_{ij}-\frac{\sum_{j=1}^nε_{ij}}n$
|FB-RCBD| |$\mu+\tau_{i}+\beta_j+ε_{ij}-\mu-\tau_{i}-\frac{\sum_{j=1}^b\beta_j}b -\frac{\sum_{j=1}^bε_{ij}}b$|$=\beta_j-\frac1b \sum_{j=1}^b\beta_j+$|$ε_{ij}-\frac{\sum_{j=1}^nε_{ij}}n$

|$y_{ij}-\bar y_{.j}$||||
| ---                |   ---  |---|---|
|FB-RCBD|$\mu+\tau_{i}+\beta_j+ε_{ij}-\frac{\sum_{i=1}^a(\mu+\tau_{i}+\beta_j+ε_{ij})}a$|$=\mu+\tau_{i}+\beta_j+ε_{ij}-\mu-0-\beta_j-\frac{ \sum_{i=1}^aε_{ij}}a$|$=\tau_{i}+ε_{ij}-\frac{\sum_{i=1}^aε_{ij}}a$|
|FB-RCBD| | | |

|$\bar y_{i.}-\bar y_{..}$||||
| ---                |   ---  |---|---|
|FT-CRD |$\frac{\sum_{j=1}^n(\mu+\tau_{i}+ε_{ij})}n-\frac{\sum_{i=1}^a\sum_{j=1}^n(\mu+\tau_{i}+ε_{ij})}{an}$|$=\tau_{i}+$|$\frac{\sum_{j=1}^nε_{ij}}n-\frac{\sum_{i=1}^a\sum_{j=1}^nε_{ij}}{an}$
|RT-CRD | |$=\tau_{i}-\frac1{a}\sum_{i=1}^a\tau_{i}+$|$\frac{\sum_{j=1}^nε_{ij}}n-\frac{\sum_{i=1}^a\sum_{j=1}^nε_{ij}}{an}$
|FB-RCBD|$\frac{\sum_{j=1}^b(\mu+\tau_{i}+\beta_j+ε_{ij})}b-\frac{\sum_{i=1}^a\sum_{j=1}^b(\mu+\tau_{i}+\beta_j+ε_{ij})}{ab}$|$=\tau_{i}+$|$\frac1b\sum_{j=1}^bε_{ij}-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bε_{ij}$
|FB-RCBD| | | |

|$\bar y_{.j}-\bar y_{..}$||||
| ---                |   ---  |---|---|
|FB-RCBD|$\frac{\sum_{i=1}^a(\mu+\tau_{i}+\beta_j+ε_{ij})}a-\frac{\sum_{i=1}^a\sum_{j=1}^b(\mu+\tau_{i}+\beta_j+ε_{ij})}{ab}$|$=\beta_j+$|$\frac{\sum_{i=1}^aε_{ij}}a-\frac{\sum_{i=1}^a\sum_{j=1}^bε_{ij}}{ab}$
|FB-RCBD| |$\beta_j-\frac{\sum_{j=1}^b\beta_j}{b}+$|$\frac{\sum_{i=1}^aε_{ij}}a-\frac{\sum_{i=1}^a\sum_{j=1}^bε_{ij}}{ab}$|


$$\bar y_{.j}-\bar y_{..}=\frac{\sum_{i=1}^a(\mu+\tau_{i}+\beta_j+ε_{ij})}a-\frac{\sum_{i=1}^a\sum_{j=1}^b(\mu+\tau_{i}+\beta_j+ε_{ij})}{ab}=
\begin{cases} &\frac1a\sum_{i=1}^aε_{ij}-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bε_{ij}&\text{FB-RCBD}\\
\beta_j-\frac{\sum_{j=1}^b\beta_j}{b}+&\frac{\sum_{i=1}^aε_{ij}}a-\frac{\sum_{i=1}^a\sum_{j=1}^bε_{ij}}{ab}&\text{RB-RCBD} \end{cases}$$

$$y_{ij}-\bar y_{i.}-\bar y_{.j}+\bar y_{..}=\mu+\tau_{i}+\beta_j+ε_{ij}-\frac1a \sum_{i=1}^a(\mu+\tau_{i}+\beta_j+ε_{ij})-\frac1b \sum_{j=1}^b(\mu+\tau_{i}+\beta_j+ε_{ij})+\frac1{ab}\sum_{i=1}^a\sum_{j=1}^b(\mu+\tau_{i}+\beta_j+ε_{ij})$$
$$=ε_{ij}-\frac1a\sum_{i=1}^aε_{ij}-\frac1b\sum_{j=1}^bε_{ij}+\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bε_{ij}-\frac1a\sum_{i=1}^a\tau_{i}-\frac1b\sum_{j=1}^b\beta_{j}\quad\text{FB-RCBD}$$

 ---

For $ε_{ij}\sim iid\ N(0,σ^2)$, $E[ε_{ij}]=0$

$$E[y_{ij}-\bar y_{i.}]=\begin{cases}E[ε_{ij}]-\frac1{n}\sum_{j=1}^nE[ε_{ij}]=0-0&\text{FT-CRD}\\
E[\tau_{i}]-\frac1n \sum_{j=1}^nE[\tau_{i}]+E[ε_{ij}]-\frac1n \sum_{j=1}^nE[ε_{ij}]=0&\text{RT-CRD}\\
E[ε_{ij}]-\frac1{b}\sum_{j=1}^bE[ε_{ij}]=0-0&\text{FB-RCBD}\\
E[\beta_j]-\frac1b \sum_{j=1}^bE[\beta_j]+E[ε_{ij}]-\frac1b \sum_{j=1}^bE[ε_{ij}]=0&\text{RB-RCBD}
\end{cases}$$

$$E[y_{ij}-\bar y_{.j}]=\begin{cases}
E[ε_{ij}]-\frac1{a}\sum_{j=1}^aE[ε_{ij}]=0&\text{FB-RCBD}\\
E[\beta_j]-\frac1a \sum_{j=1}^aE[\beta_j]+E[ε_{ij}]-\frac1a \sum_{j=1}^aE[ε_{ij}]=0&\text{RB-RCBD}
\end{cases}$$

$$E[\bar y_{i.}-\bar y_{..}]=\begin{cases}\frac1{n}\sum_{j=1}^nE[ε_{ij}]-\frac1{an}\sum_{i=1}^a\sum_{j=1}^nE[ε_{ij}]=0-0&\text{FT-CRD}\\
\frac1n \sum_{j=1}^nE[\tau_{i}]-\frac1{an}\sum_{i=1}^a\sum_{j=1}^nE[\tau_{i}]+\frac1n \sum_{j=1}^nE[ε_{ij}]-\frac1{an}\sum_{i=1}^a\sum_{j=1}^nE[ε_{ij}]=0&\text{RT-CRD}\\
\frac1{b}\sum_{j=1}^bE[ε_{ij}]-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bE[ε_{ij}]=0&\text{FB-RCBD}\\
\frac1b \sum_{j=1}^bE[\beta_j]-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bE[\beta_j]+\frac1b \sum_{j=1}^bE[ε_{ij}]-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bE[ε_{ij}]=0&\text{RB-RCBD}
\end{cases}$$



$$E[\bar y_{.j}-\bar y_{..}]=\begin{cases}
\frac1{a}\sum_{j=1}^aE[ε_{ij}]-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bE[ε_{ij}]=0&\text{FB-RCBD}\\
\frac1a \sum_{j=1}^aE[\beta_j]-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bE[\beta_j]+\frac1a \sum_{j=1}^aE[ε_{ij}]-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bE[ε_{ij}]=0&\text{RB-RCBD}
\end{cases}$$


$$E[y_{ij}-\bar y_{i.}-\bar y_{.j}+\bar y_{..}]=E[ε_{ij}]-\frac1{b}\sum_{j=1}^bE[ε_{ij}]-\frac1{a}\sum_{j=1}^aE[ε_{ij}]+\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bE[ε_{ij}]=0\quad \text{FB-RCBD}$$

 ---

$Var[y_{ij}-\bar y_{i.}]=$

$Var[ε_{ij}-\frac1n \sum_{j=1}^nε_{ij}]=Var[ε_{ij}]+\frac1{n^2}\sum_{j=1}^nVar[ε_{ij}]-\frac2nCov[ε_{ij},\sum_{j=1}^nε_{ij}]\quad \text{FT-CRD}$

$Var[\tau_{i}-\frac1n \sum_{j=1}^n\tau_{i}+ε_{ij}-\frac1n \sum_{j=1}^nε_{ij}]=Var[\tau_{i}]+\frac1{n^2}\sum_{j=1}^nVar[\tau_{i}]-\frac2nCov[\tau_{i},\sum_{j=1}^n\tau_{i}]+Var[ε_{ij}]+\frac1{n^2}\sum_{j=1}^nVar[ε_{ij}]-\frac2nCov[ε_{ij},\sum_{j=1}^nε_{ij}]$

$+Cov[\tau_{i},ε_{ij}]-\frac2nCov[\tau_{i},\sum_{j=1}^nε_{ij}]-\frac2nCov[ε_{ij},\sum_{j=1}^n\tau_{i}]+\frac2{n^2}Cov[\sum_{j=1}^n\tau_{i},\sum_{j=1}^nε_{ij}]\quad\text{RT-CRD}$

$Var[ε_{ij}-\frac1b \sum_{j=1}^bε_{ij}]=Var[ε_{ij}]+\frac1{b^2}\sum_{j=1}^bVar[ε_{ij}]-\frac2bCov[ε_{ij},\sum_{j=1}^bε_{ij}]\quad\text{FB-RCBD}$

$Var[\beta_{j}-\frac1b \sum_{j=1}^b\beta_{j}+ε_{ij}-\frac1b \sum_{j=1}^bε_{ij}]=Var[\beta_{j}]+\frac1{b^2}\sum_{j=1}^bVar[\beta_{j}]-\frac2bCov[\beta_{j},\sum_{j=1}^b\beta_{j}]+Var[ε_{ij}]+\frac1{b^2}\sum_{j=1}^bVar[ε_{ij}]-\frac2bCov[ε_{ij},\sum_{j=1}^bε_{ij}]$

$+Cov[\beta_{j},ε_{ij}]-\frac2bCov[\beta_{j},\sum_{j=1}^bε_{ij}]-\frac2bCov[ε_{ij},\sum_{j=1}^b\beta_{j}]+\frac2{b^2}Cov[\sum_{j=1}^b\beta_{j},\sum_{j=1}^bε_{ij}]\quad\text{RB-RCBD}$

 ---

$Var[\bar y_{i.}-\bar y_{..}]=$

4

$$Var[\frac1n\sum_{j=1}^nε_{ij}-\frac1{an}\sum_{i=1}^a\sum_{j=1}^nε_{ij}]=\frac1nVar[ε_{ij}]+\frac1{a^2n^2}\sum_{i=1}^a\sum_{j=1}^nVar[ε_{ij}]-\frac2{an^2}Cov[\sum_{j=1}^nε_{ij},\sum_{i=1}^a\sum_{j=1}^nε_{ij}]\quad \text{FT-CRD}$$

5

$Var[\frac1n \sum_{j=1}^n\tau_{i}-\frac1{an}\sum_{i=1}^a\sum_{j=1}^n\tau_{i}+\frac1n \sum_{j=1}^nε_{ij}-\frac1{an}\sum_{i=1}^a\sum_{j=1}^nε_{ij}]=\quad \text{RT-CRD}$

6

$$Var[]=\quad \text{FB-RCBD}$$

 ---

6

$Var[y_{ij}-\bar y_{.j}]=$

$$Var[]=\quad \text{FB-RCBD}$$

 ---

$Var[\bar y_{.j}-\bar y_{..}]=$

6

$$Var[\frac1a\sum_{j=1}^aε_{ij}-\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bε_{ij}]=\frac1aVar[ε_{ij}]+\frac1{a^2b^2}\sum_{i=1}^a\sum_{j=1}^bVar[ε_{ij}]-\frac2{ab^2}Cov[\sum_{j=1}^bε_{ij},\sum_{i=1}^a\sum_{j=1}^bε_{ij}]\quad \text{FB-RCBD}$$

7

$$Var[]=\quad \text{RB-RCBD}$$

 ---

6

$Var[y_{ij}-\bar y_{i.}-\bar y_{.j}+\bar y_{..}]=Var[ε_{ij}-\frac1a\sum_{i=1}^aε_{ij}-\frac1b\sum_{j=1}^bε_{ij}+\frac1{ab}\sum_{i=1}^a\sum_{j=1}^bε_{ij}-\frac1a\sum_{i=1}^a\tau_{i}-\frac1b\sum_{j=1}^b\beta_{j}]\quad\text{FB-RCBD}$





 ---

For $ε_{ij}\sim iid\ N(0,σ^2)$, $Var[ε_{ij}]=Cov[ε_{ij},ε_{ij}]=\sigma^2$, $Cov[ε_{ij},ε_{ik}]=0,k\neq j$

For $\tau_{i}\sim iid\ N(0,σ_{\tau}^2)$, $Var[\tau_{i}]=Cov[\tau_{i},\tau_{i}]=σ_{\tau}^2$

For $\beta_{j}\sim iid\ N(0,σ_{\beta}^2)$, $Var[\beta_{j}]=Cov[\beta_{j},\beta_{j}]=σ_{\beta}^2$

For $ε_{ij},\tau_{i},\beta_{j}$ are independent, $Cov[ε_{ij},\tau_{i}]=Cov[ε_{ij},\beta_{j}]=Cov[\tau_{i},\beta_{j}]=0$


$-\frac2nCov[ε_{ij},\sum_{j=1}^nε_{ij}]=-\frac2nCov[ε_{ij},(ε_{i1}+..+ε_{ij}..+ε_{in})]=-\frac2n(Cov[ε_{ij},ε_{i1}]+..+Cov[ε_{ij},ε_{ij}]..+Cov[ε_{ij},ε_{in}])=-\frac2n\sigma^2$

$$Var[y_{ij}-\bar y_{i.}]=\begin{cases}\sigma^2+\frac{\sigma^2}n-\frac2n\sigma^2=\frac{n-1}n\sigma^2&\text{FT-CRD}\\
σ_{\tau}^2+\frac{σ_{\tau}^2}n-\frac2nσ_{\tau}^2+\sigma^2+\frac{\sigma^2}n-\frac2n\sigma^2=\frac{n-1}n(σ_{\tau}^2+\sigma^2)&\text{RT-CRD}\\
\sigma^2+\frac{\sigma^2}b-\frac2b\sigma^2=\frac{b-1}b\sigma^2&\text{FB-RCBD}\\
σ_{\beta}^2+\frac{σ_{\beta}^2}b-\frac2bσ_{\beta}^2+\sigma^2+\frac{\sigma^2}b-\frac2b\sigma^2=\frac{b-1}b(σ_{\beta}^2+\sigma^2)&\text{RB-RCBD}
\end{cases}$$

$$Var[\bar y_{i.}-\bar y_{..}]=\begin{cases}\sigma^2+\frac{\sigma^2}n-\frac2n\sigma^2=\frac{n-1}n\sigma^2&\text{FT-CRD}\\
σ_{\tau}^2+\frac{σ_{\tau}^2}n-\frac2nσ_{\tau}^2+\sigma^2+\frac{\sigma^2}n-\frac2n\sigma^2=\frac{n-1}n(σ_{\tau}^2+\sigma^2)&\text{RT-CRD}\\
\sigma^2+\frac{\sigma^2}b-\frac2b\sigma^2=\frac{b-1}b\sigma^2&\text{FB-RCBD}\\
σ_{\beta}^2+\frac{σ_{\beta}^2}b-\frac2bσ_{\beta}^2+\sigma^2+\frac{\sigma^2}b-\frac2b\sigma^2=\frac{b-1}b(σ_{\beta}^2+\sigma^2)&\text{RB-RCBD}
\end{cases}$$




 ---


$$E[(y_{ij}-\bar y_{i.})^2]=\begin{cases}E[ε_{ij}^2+\frac1{n^2}(\sum_{j=1}^nε_{ij})^2-\frac2nε_{ij}\sum_{j=1}^nε_{ij}]=\frac{n-1}n\sigma^2&\text{FT-CRD;FB-RCBD}\\
E[\tau_{i}-\frac1n \sum_{j=1}^n\tau_{i}+ε_{ij}-\frac1n \sum_{j=1}^nε_{ij}]^2=&\text{RT-CRD}\\
E[\beta_j-\frac1b \sum_{j=1}^b\beta_j+ε_{ij}-\frac1b \sum_{j=1}^bε_{ij}]^2=&\text{RB-RCBD}
\end{cases}$$


$$E[(y_{ij}-\bar y_{i.})^2]=Var[y_{ij}-\bar y_{i.}]+E[y_{ij}-\bar y_{i.}]^2=\frac{n-1}n\sigma^2$$
$$E[(\bar y_{i.}-\bar y_{..})^2]=Var[\bar y_{i.}-\bar y_{..}]+E[\bar y_{i.}-\bar y_{..}]^2=$$
$$E[(\bar y_{.j}-\bar y_{..})^2]=Var[\bar y_{.j}-\bar y_{..}]+E[\bar y_{.j}-\bar y_{..}]^2=$$
$$E[(y_{ij}-\bar y_{i.}-\bar y_{.j}+\bar y_{..})^2]=Var[y_{ij}-\bar y_{i.}-\bar y_{.j}+\bar y_{..}]+E[y_{ij}-\bar y_{i.}-\bar y_{.j}+\bar y_{..}]^2=$$



 ---

 
|     |$y_{ij}$  |$\bar y_{..}$|$\bar y_{i.}$|$\bar y_{.j}$|$MS_{Trt}$|$MS_{Blk}$|$MS_{E}$|
| --- |   ---    |  ---        |  ---        |   ---       | ---      | ---      | ---    |
|E[f.]  |  $\mu$   |  $\mu$      |$\mu+\tau_i$ |$\mu+\beta_j$|$\sigma^2+\frac{n}{a-1}\sum_{i=1}^a\tau_i^2$||$\sigma^2$|
|V[f.]  |$\sigma^2$|$\frac{\sigma^2}{na}$|$\frac{\sigma^2}{n}$|
|E[f.^2]|$\mu^2+\sigma^2$|$\mu^2+\frac{\sigma^2}{na}$|$\mu_i^2+\frac{\sigma^2}{n}$|
|E[r.]|  $\mu$   |  $\mu$      |$\mu+\tau_i$ |             |$\sigma^2+\frac{b}{a-1}\sum_{i=1}^a\tau_i^2$|$\sigma^2+\frac{a}{b-1}\sum_{j=1}^b\beta_j^2$|
|V[r.]|$\sigma^2+\sigma_\tau^2$|$\frac{\sigma_\tau^2}{a}+\frac{\sigma^2}{na}$|$\frac{\sigma^2}{n}+\sigma_\tau^2$|
|E[r.^2]|$\mu^2+\sigma^2+\sigma_\tau^2$|$\mu^2+\frac{\sigma_\tau^2}{a}+\frac{\sigma^2}{na}$|$\mu_i^2+\frac{\sigma^2}{n}+\sigma_\tau^2$|


$\hat\tau_i=\bar y_{i.}-\bar y_{..}$|$\hat\beta_j=\bar y_{.j}-\bar y_{..}$|