---
title: "STAT 572: Bayesian Statistics" 
subtitle: "Homework 3"
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---

\vspace{-0.5cm}
\begin{center}
(to be submitted online in D2L before October 29th before noon)
\end{center}

\vspace{1cm}


## Part 1

Let $Y_1,Y_2,\ldots,Y_n | \mu,\lambda\stackrel{iid}{\sim}N(\mu,\lambda^{-1})$, and **assume that $\lambda>0$ is fixed and known**.

@1. Derive the exponential family form for the generating distribution (the likelihood) of $Y_1,Y_2,\ldots,Y_n$. 

@2. Use the likelihood derived above in exponential family form to show that the conjugate family of priors for $\boldsymbol{\mu}$ corresponds to

$$\Big\{N(\mu_0,(\nu\lambda)^{-1}): \mu_0\in\mathbb{R}, \nu >0\Big\},$$ 

@3. Use the results from the two parts above to find the posterior distribution for $\mu$.

@4. Now, assume that $\lambda$ is not known, and show that the collection of $N(\mu,\lambda^{-1})$ distributions, with $\mu\in\mathbb{R}$ and $\lambda > 0$, is a two-parameter exponential family, and identify the sufficient statistics function $t(y_{1:n}) = (t_1(y_{1:n}), t_2(y_{1:n}))^T$ for your parametrization.

## Part 2

Two competitors for the snowiest city in the world are Aomori City in Japan, and Valdez in the state of Alaska. Here are annual snowfall records, in inches/year, for the two cities:
```{r}

#Aomori, 1954–2014: 
Aomori <- c(188.6, 244.9, 255.9, 329.1, 244.5, 167.7, 298.4, 274.0, 241.3, 288.2,208.3, 
           311.4,273.2, 395.3, 353.5, 365.7, 420.5, 303.1, 183.9, 229.9, 359.1, 355.5, 
           294.5, 423.6, 339.8, 210.2, 318.5, 320.1, 366.5, 305.9, 434.3, 382.3, 497.2, 
           319.3, 398.0, 183.9, 201.6, 240.6, 209.4, 174.4, 279.5, 278.7, 301.6, 196.9, 
           224.0, 406.7, 300.4, 404.3, 284.3, 312.6, 203.9, 410.6, 233.1, 131.9, 167.7, 
           174.8, 205.1, 251.6, 299.6, 274.4, 248.0)
#Valdez, 1976–2013: 
Valdez <- c(351.0, 379.3, 196.1, 312.3, 301.4, 240.6, 257.6, 304.5, 296.0, 338.8, 299.9, 
            384.7, 353.5, 312.8, 550.7, 327.1, 515.8, 343.4, 341.6, 396.9, 267.3, 230.6, 
            277.4, 341.0, 377.0, 391.3, 337.0, 250.4, 353.7, 307.7, 237.5, 275.2, 271.4, 
            266.5, 318.7, 215.5, 438.3, 404.6) 
```

Assume that for each city independently, the data is i.i.d. normal.

@1. Do you think an iid normal model is appropriate here? Why or why not?

@2. Is the mean annual snowfall for Valdez higher than that of Aomori? To address this question, perform an analysis like the one for the Pygmalion effect in the class notes assuming normality. In particular, your analysis should involve computing the posterior probability that the mean annual snowfall for Valdez is higher than that of Aomori. Choose suitable prior parameters (hyperparameters) that reflect your prior knowledge (or lack thereof).

@3. Try different values for the hyperparameters, to see what effect they have on the results. Report your results for three different settings of the hyperparameters.