---
title: "STAT562 Final Exam"
author: "Shen Qu 918881147"
date: 'Winter 2019'
output:
  pdf_document: 
geometry: margin=0.25in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=FALSE, size="tiny",results="markup", tidy=T)

# theme: default, cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti

# highlight: default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, and textmate

#    includes:
#      in_header: preamble.tex
#      before_body: doc-prefix.tex
#      after_body: doc-suffix.tex

#    df_print: default, kable, tibble

#    citation_package: natbib, biblatex

# size = c("normalsize", "tiny", "scriptsize", "footnotesize", "small", "large", "Large", "LARGE", "huge", "Huge")
```


```{r eval=FALSE, include=FALSE}
install.packages("ggplot2")
install.packages("ggpubr")
install.packages("mosaic")
install.packages("agricolae")
install.packages("DescTools")
install.packages("emmeans")
```

```{r include=FALSE}
library(readxl)
library(ggplot2)
library(ggpubr)
library(mosaic)
library(agricolae)
library(DescTools)
library(dplyr)
library(car)
library(pander)
library(emmeans)

```


(a)  \textcolor[rgb]{0.5,0.5,0.5}{$X_1,X_2,..X_n$ is a random sample from a distribution having a p.d.f of the form.}

$$f(x)=\begin{cases}\lambda x^{\lambda-1}&0<x<1\\0&\text{otherwise}\end{cases}$$

(a)  \textcolor[rgb]{0.5,0.5,0.5}{Find a complete sufficient statistic for $\lambda$. Justify your answer}