---
title: "lab_stat565_1"
author: "Shen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
geometry: margin=0.25in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, size="small", results="markup",highlight=T)
```

(a) Plot the data and report the plot here (A plot with data and means of treatment combinations). Do not report code here. Describe the observed relationship between two factors.

```{r eval=FALSE, include=FALSE}
install.packages("ggplot2")
install.packages("ggpubr")
install.packages("mosaic")
install.packages("agricolae")
install.packages("DescTools")
```

```{r include=FALSE}
library(readxl)
library(ggplot2)
library(ggpubr)
library(mosaic)
library(agricolae)
library(DescTools)
library(dplyr)
```

```{r echo=FALSE}
table_protein <- read_excel("Protein.xlsx")
glimpse(table_protein)
```


```{r pressure, echo=F, out.width='25%', collapse=T}
table_protein <- read_excel("Protein.xlsx")
glimpse(table_protein)

# Install and load ggplot2 package before using ggplot function #
ggplot(data = table_protein, aes(x = Amount, y = Gain, colour=Source, group=Source))+ 
  geom_point(aes(shape = Source,color = Source),size = 2) + 
  labs(y = "Weight Gained", x="Amount of table_protein", color ="Source of table_protein", shape ="Source of table_protein")

#Plots the Mean and 1SD error bars for each treatment group #
ggplot(data = table_protein, aes(x = Amount, y = Gain, colour=Source,shape = Source, group=Source)) +
  stat_summary() + labs(y= "Weight Gained", x="Amount of table_protein", color="Source", shape="Source")

# Install and load ggpubr package before using ggline function # 
ggline(data = table_protein, x = "Amount", y = "Gain", add = c("mean", "jitter"),shape= "Source",  color = "Source", linetype = "Source", ylab= "Weight Gained", xlab="Amount of table_protein")

#Load mosaic package before using favstats function#
favstats(Gain ~ Source, data=table_protein)
favstats(Gain ~ Amount , data=table_protein)
favstats(Gain ~ Source|Amount, data=table_protein)
#favstats(Gain ~ Source+Amount, data=table_protein)

#Create Categorical variables so that plot of residuals versus each treatment combination can be obtained using plot function with the fitted model later #
table_protein$Trt1 = as.factor(table_protein$Source)
table_protein$Trt2 = as.factor(table_protein$Amount)

model_protein <- aov(Gain ~ Trt1*Trt2, data=table_protein)
summary(model_protein)
plot(model_protein, pch=16)

# Pairwise comparisons using t tests with pooled Standard Deviation #
# The output gives a matrix of p values for each pair of treatments #
pairwise.t.test(table_protein$Gain, table_protein$Trt2, p.adj = "none") 

# Pairwise comparisons using t tests with pooled Standard Deviation and Bonferroni adjustment #
# The output gives a matrix of p values for each pair of treatments #
pairwise.t.test(table_protein$Gain, table_protein$Trt2, p.adj = "bonf")

#Install and load the agricolae package before running the LSD.test function below #
#p.adj option in the LSD.test function can be used to apply different adjustments to control error rates#
plot(LSD.test(model_protein, trt = "Trt2", alpha = 0.05))
#The treatments sharing the same letter on the plot are not different#

(LSD.test(model_protein, trt = "Trt2", alpha = 0.05)) # Using outer parentheses prints the output#

#Tukey's test to get observed difference in means, CI and p value#
TukeyHSD(model_protein, conf.level = 0.95)

# Scheffe's test to get observed difference in means, CI and p value #
# Install and load the DescTools package before using the ScheffeTest function #
ScheffeTest(model_protein, conf.level = 0.95)

```

