---
title: "HW2"
subtitle: STAT561 Fall 2018
author: 'Shen Qu'
date: "10/11/2018"
output: html_document
---

1 .37 Some variations of Example 1.3.4.
(a) In the warden's calculation it was assumed that if A were to be pardoned, then with equal probability the warden would tell A that either B or C would die. However, this need not be the case. The warden can assign probabilities Y and 1-Y to these events, as shown here:


Prisoner pardoned | Warden tells A |
---|---|---
A | B dies | with probability Y
A | C dies | with probability 1-Y
B | C dies | 
C | B dies | 


Calculate P(A|W) as a function of Y. For what values of Y is P(A|W) less than,equal to, or greater than 1/3?  

 > A, B, c is a partitions of sample space. According the Beyes' rule
 
$$P(A|W)=\frac{P(W|A)P(A)}{P(W|A)P(A)+P(W|B)P(B)+P(W|C)P(C)}=\frac{\gamma\frac13}{\gamma\frac13+0\frac13+\frac13}=\frac{\gamma}{\gamma+1}$$

$$P(A|W)=\frac{\gamma}{\gamma+1}=\begin{cases}<\frac13&\gamma<\frac12\\=\frac13&\gamma=\frac12\\>\frac13&\gamma>\frac12\end{cases}$$

(b) Suppose again that Y = 1/2. After the warden tells A that B will die, A thinks for a while and realizes that his original calculation was false. However, A then gets a bright idea. A asks the warden if he can swap fates with C. The warden, thinking that no information has been passed, agrees to this. Prove that A's reasoning is now correct and that his probability of survival has jumped to 2/3!

$$P(C|W)=\frac{P(W|C)P(C)}{P(W|A)P(A)+P(W|B)P(B)+P(W|C)P(C)}=\frac{\frac13}{\frac12\frac13+0\frac13+\frac13}=\frac23$$

 > Therefore, if A swap fates with C, his probability of survival is 2/3.

1 .39 A pair of events A and B cannot be simultaneously mutually exclusive and independent. Prove that if P(A) > 0 and P(B) > 0, then:

(a) If A and B are mutually exclusive, they cannot be independent.

 > When A and B are pairwise disjoint, $P(A\cap{B})=0$. 

$$\because\quad P(A)P(B)>0\quad \therefore\quad P(A)P(B)\ne P(A\cap{B})$$

 > Therefore, A and B does not satisfy the definition of **statistically independent**

(b) If A and B are independent, they cannot be mutually exclusive.

 > Acrroding the definition of statistically independent, When A and B are independent, $P(A\cap{B})=P(A)P(B)>0$, which means $A\cap B\ne\emptyset$. Therefore, A and B does not satisfy the definition of **paiwise disjoint**$

1.47 Prove that the following functions are cdfs.

 > According the Theorem 1.5.3 about **cumulative distribution function**, A cdf F(x) should satisfy 3 conditions:   
a. $\lim_{x\to-\infty}F(x)=0\ \& \lim_{x\to\infty}F(x)=1$
b. F is non-decreasing，which means for any a>b $ f(a)>f(b) $
c. F is right-continuous, which means $\lim_(x\to c)f(x)=f(c) $

(a) $\frac12+\frac1\pi\tan^{-1}(x), x\in-(\infty,\infty)$

$$\lim_{x\to-\infty}F(x)=\lim_{x\to-\infty}[\frac12+\frac1\pi\tan^{-1}(x)]=\frac12+\frac1\pi(-\frac\pi2)=0$$

$$\lim_{x\to\infty}F(x)=\frac12+\frac1\pi(\frac\pi2)=1$$

$$f(x)'=\frac\partial{\partial{x}}[\frac12+\frac1\pi\tan^{-1}(x)]=\frac1{\pi(1+x^2)}>0$$


(b) $(1+e^{-x})^{-1} , x\in(-\infty,\infty)$

 > This is a Continuous cdf.

$$\because\quad \lim_{x\to-\infty}e^x=0,\quad\lim_{x\to-\infty}e^{-x}=\infty,\quad \lim_{x\to-\infty}\frac1{1+e^{-x}}=0\quad \therefore\lim_{x\to-\infty}F(x)=0$$

$$\text{in the same way, }\lim_{x\to\infty}F(x)=\lim_{x\to\infty}\frac1{1+e^{-x}}=\lim_{x\to\infty}\frac1{1+0}=1$$

$$f(x)'=\frac\partial{\partial{x}}\frac1{1+e^{-x}}=\frac{e^{-x}}{(1+e^{-x})^2}>0$$

(c) $e^{-e^{-x}}, x\in(-\infty,\infty)$

$$\because\quad \lim_{x\to-\infty}e^x=0,\quad\lim_{x\to-\infty}e^{-x}=\infty,\quad\lim_{x\to-\infty}e^{e^{-x}}=\infty,\quad \therefore\lim_{x\to-\infty}e^{-e^{-x}}=0$$

$$\text{in the same way, }\lim_{x\to\infty}F(x)=\lim_{x\to\infty}e^{-e^{-x}}=e^0=1$$

$$f(x)'=\frac\partial{\partial{x}}e^{-e^{-x}}=e^{-e^{-x}}\frac\partial{\partial{x}}(-e^{-x})=e^{-e^{-x}}(-e^{-x})\frac\partial{\partial{x}}(-x)=e^{-e^{-x}}e^{-x}>0$$


(d) $1-e^{-x}, x\in(0,\infty)$

$$\because\quad \lim_{x\to-\infty}e^x=1,\quad\lim_{x\to-\infty}e^{-x}=1,\quad \therefore\lim_{x\to-\infty}(1-e^{-x})=0$$

$$\text{in the same way, }\lim_{x\to\infty}F(x)=\lim_{x\to\infty}(1-e^{-x})=1-e^0=1$$

$$f(x)'=\frac\partial{\partial{x}}(1-e^{-x})=-e^{-x}\frac\partial{\partial{x}}(-x)=e^{-x}>0$$

(e) the function defined in (1.5.6)   
$F_Y(y)=\begin{cases}\frac{1-\epsilon}{1+e^{-y}}，& y<0\\\epsilon+\frac{1-\epsilon}{1+e^{-y}}，& y\ge0\end{cases} $

 > This is a cdf with jumps.
 
 $$\lim_{y\to-\infty}F_Y(y)=\lim_{y\to-\infty}\frac{1-\epsilon}{1+e^{-y}}=0$$

 $$\lim_{y\to\infty}F_Y(y)=\epsilon+\frac{1-\epsilon}{1+e^{-y}}=\epsilon+1-\epsilon=1$$

 $$\lim_{y\to0}F_Y(y)=\epsilon+\frac{1-\epsilon}{1+e^{-y}}=1=F(0)$$

 > The limit point is 0. No jump occurs when F(y) approaches 0 from the right. And $0<\epsilon<1$


$$f(y)'=\frac\partial{\partial{y}}(\epsilon+\frac{1-\epsilon}{1+e^{-y}})=(1-\epsilon)\frac{1+e^{-y}+\frac\partial{\partial{y}}(e^{-y})}{(1+e^{-y})^2}=\frac{1-\epsilon}{(1+e^{-y})^2}>0$$

1 .54 For each of the following, determine the value of c that makes F(x) a pdf.

 > According to the theorem 1.6.5, A function fx(x) is a pdf (or pmf ) of a random variable X if and only if  
a. $fx(x)\ge 0$  for all x.  
b. $\sum_xfx (x) = 1 (pmf)\ or \int_{-\infty}^{\infty}fx (x) dx=1\ (pdf)$

(a) $f(x)=c\sin{x}, 0<x<\pi/2$

$$\because 0<x<\pi/2,\ \sin{x}\in[0,1],\quad \therefore when\ c\ge0,\quad fx(x)\ge0$$

$$\because \int_{0}^{\frac\pi2}sin(x)dx=1,\quad \therefore c=\frac11=1$$

(b) $f(x)=ce^{-|x|}, -\infty< x < \infty$
    
$$\because -\infty<-|x|\le0,\ e^{-|x|}\in(0,1],\quad \therefore when\ c\ge0,\quad fx(x)\ge0$$

$$\because \int_{-\infty}^{\infty}e^{-|x|}dx=\int_{-\infty}^{0}e^{x}dx+\int_{0}^{\infty}e^{-x}dx=2,\quad \therefore c=\frac12$$


1 .55 An electronic device has lifetime denoted by T. The device has value V=5 if it fails before time t = 3; otherwise, it has value V = 2T. Find the cdf of V, if T has pdf

$$f_T(t)=\frac1{1.5}e^{-\frac{t}{1.5}},\ t>0$$

$$\because -\infty<-\frac{t}{1.5}<0,\quad \therefore  \frac1{1.5}e^{-\frac{t}{1.5}}\in(0,\frac23)$$

$$And\quad \int_{0}^{\infty}\frac1{1.5}e^{-\frac{t}{1.5}}dx=1$$

 > According the theorem 1.5.10 of **identically distributed**

$$F_V(v)=P(V\le v)=P(T\le t)=F_T(t)$$

 > According the definition 1.6.3 of **probability density function**  
When 0<t<3, V=5, then

$$P(V\le 5)=P(T<3)=\int_{0}^{3}f_T(t)dt=\int_{0}^{3}\frac1{1.5}e^{-\frac{t}{1.5}}dt=\int_{0}^{3}-e^{-\frac{t}{1.5}}d\frac {-t}{1.5}=-e^{-\frac{3}{1.5}}+e^{-\frac{0}{1.5}}=1-e^{-2}$$

 > When $t\ge3,\ V\ge6$, then
 
$$P(V\le v)=P(2T<v)=P(T<\frac{v}2)=\int_{0}^{\frac{v}2}f_T(v)dv=\int_{0}^{\frac{v}2}\frac1{1.5}e^{-\frac{v}{1.5}}dv=\int_{0}^{\frac{v}2}-e^{-\frac{v}{1.5}}d\frac {-v}{1.5}=-e^{-\frac{v}{3}}+e^{-\frac{0}{3}}=1-e^{-\frac{v}3}$$

$$\therefore  F_V(v)=\begin{cases}1-e^{-2}&6\le v\\1-e^{-\frac{v}3}&0<v<6\\0&-\infty<v<0\end{cases}$$

