---
title: "STAT561 Fall 2018 HW5"
author: 'Shen Qu'
date: "11/1/2018"
output: html_document
---

**3.2** A manufacturer receives a lot of 100 parts from a vendor. The lot will be unacceptable if more than five of the parts are defective. The manufacturer is going to select randomly K parts from the lot for inspection and the lot will be accepted if no defective parts are found in the sample.

(a) How large does K have to be to ensure that the probability that the manufacturer accepts an unacceptable lot is less than . 10?

The probability of accepting the unacceptable lot is

$$P(X=0|N=100,M=6,k)=\frac{\binom{6}{0}\binom{100-6}{k}}{\binom{100}{k}}<0.10$$

$$P(X=0|N=100,5<M<(100-k),k)=\sum_{M=6}^{100-k}\frac{\binom{M}{0}\binom{100-M}{k}}{\binom{100}{k}}=1-\sum_{M=0}^{5}\frac{\binom{M}{0}\binom{100-M}{k}}{\binom{100}{k}}<0.10$$
 By trail and error?

****
(b) Suppose the manufacturer decides to accept the lot if there is at most one defective in the sample. How large does K have to be to ensure that the probability that the manufacturer accepts an unacceptable lot is less than . 10?

$$P(X=0 or 1|N=100,M=6,k)=\frac{\binom{M}{0}\binom{100-M}{k-0}}{\binom{100}{k}}+\frac{\binom{M}{1}\binom{100-M}{k-1}}{\binom{100}{k}}<0.10$$

$$P(X=0 or 1|N=100,M>5,k)=\sum_{M=6}^{100-k}\frac{\binom{M}{0}\binom{100-M}{k-0}+\binom{M}{1}\binom{100-M}{k-1}}{\binom{100}{k}}<0.10$$

****
**3.7** Let the number of chocolate chips i n a certain type of cookie have a Poisson distribution. We want the probability that a randomly chosen cookie has at least two chocolate chips to be greater than .99. Find the smallest value of the mean of the distribution that ensures this probability.

****
**3.13** A truncated discrete distribution is one in which a. particular class cannot be observed and is eliminated from the sample space. In particular, if X has range 0, 1, 2, . . . and the 0 class cannot be observed (as is usually the case), the O-truncated random variable $X_T$ has pmf

$$P(X_T = x) = \frac{P(X=x)}{P(X>0)},\ x=1,2,..$$

Find the pmf, mean, and variance of the O-truncated random varia.ble starting from

(a) $X\sim Poisson(\lambda)$

$$e^{-\lambda}\sum_{i=0}^k\frac{\lambda^i}{i!}, P(X=k) = \frac{e^{-\lambda}\lambda^k}{k!}; k \in \{0, 1, 2, \dots \}, \lambda, \lambda, e^{\lambda(e^t-1)}$$

****
(b) $X\sim negative binomial(r, p)$, as in (3.2.10)

$$(3.2.10)\quad P(Y=y)=(-1)^y\binom{-r}{y}p^r(1-p)^y $$

****
**3.17** Establish a formula similar to (3.3.18) for the gamma distribution. If $X \sim gamma(\alpha, \beta)$, then for any positive constant $\nu$,

$$f(x|\alpha,\beta)=\frac1{B(\alpha,\beta)}x^{\alpha-1}(1-x)^{\beta-1}, x \in (0, 1), \beta>0, \alpha>0$$

$$B(\alpha,\beta)=\int_0^1x^{\alpha-1}(1-x)^{\beta-1}dx =\frac{\Gamma(\alpha)\Gamma(\beta)}{\Gamma(\alpha+\beta)}; x \in (0, 1), \beta>0, \alpha>0$$


$$(3.3.18)\quad EX^n=\frac{1}{B(\alpha,\beta)}\int_0^1x^nx^{\alpha-1}(1-x)^{\beta-1}dx=\frac{B(a+n,\beta)}{B(\alpha,\beta)}=\frac{\Gamma(\alpha+n)\Gamma(\alpha+\beta)}{\Gamma(\alpha+\beta+n)\Gamma(\alpha)} $$

***
$$\Gamma(\alpha)= \int_0^{\infty}t^{\alpha-1}e^{-t}dx$$



$$f(x|\alpha,\beta) = \frac{1}{\Gamma(a)\beta^{\alpha}}x)^{a-1}e^{-x/\beta}; x \in (0, \infty), \beta>0, \alpha>0$$

$$EX= \frac{1}{\Gamma(a)\beta^{\alpha}}\int_0^{\infty}xx^{a-1}e^{-x/\beta}dx=\frac{1}{\Gamma(a)\beta^{\alpha}}\int_0^{\infty}x^ae^{-x/\beta}dx=\frac{\Gamma(a+1)\beta^{\alpha+1}}{\Gamma(a)\beta^{\alpha}}=\alpha\beta$$

$$VarX= \alpha^2\beta;\ M_X(t)=\left(\frac{1}{1 - \beta t}\right)^a, t < \frac1\beta$$

$$(\Gamma (a, \lambda); f(x) = \frac{1}{\Gamma(a)}(\lambda x)^ae^{-\lambda x}\frac{1}{x}; x \in (0, \infty) \frac{a}{\lambda} \frac{a}{\lambda^2} \left(\frac{\lambda}{\lambda - t}\right)^a, t < \lambda)$$

$$EX^{\nu}= \frac{\beta^{\nu}\Gamma(\nu+\alpha)}{\Gamma(\alpha)}$$