---
title: "STAT561 Fall 2018 HW7"
author: 'Shen Qu'
date: "11/22/2018"
output: html_document
---




**3.28** Show that each of the following families is an exponential family.

(a) normal family with either parameter $\mu$ or $\sigma$ known

$$\frac{h(x)}{c(\sigma^2)}e^{w_1(\sigma^2)t_1(x)}$$

When $\mu$ is known,

$$f(x|\sigma^2)=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac1{2\sigma^2}(x-\mu)^2}=\frac{h(x)}{c(\sigma^2)}e^{w_1(\sigma^2)t_1(x)}$$

$h(x)$ | $c(\sigma^2)$ | $w_(\sigma^2)$ | t_1(x)
------ | ------------- | -------------- | ------
 1 | $\frac{1}{\sqrt{2\pi\sigma^2}}I_{(0,\infty)}(\sigma^2)$ | $-\frac1{2\sigma^2}$ | $(x-\mu)^2$


$$h(x)=1,\quad c(\sigma^2)=\frac{1}{\sqrt{2\pi\sigma^2}}I_{(0,\infty)}(\sigma^2),\quad w_1(\sigma^2)=-\frac1{2\sigma^2},\quad t_1(x)=(x-\mu)^2$$

When $\sigma$ is known,

$$f(x|\mu)=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac1{2\sigma^2}(x-\mu)^2}=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{x^2}{2\sigma^2}+\frac{x^2}{\sigma^2}-\frac{\mu^2}{2\sigma^2}}$$

$h(x)$ | $c(\mu)$ | $w_(\mu)$ | t_1(x)
------ | -------- | --------- | ------
 $e^{-\frac{\mu^2}{2\sigma^2}}$ | $\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{\mu^2}{2\sigma^2}}$ | $\mu$ | $\frac{x}{\sigma^2}$

****
(b) gamma family with either parameter $\alpha$ or $\beta$ known or both unknown

****
(c) beta family with either parameter $\alpha$ or $\beta$ known or both unknown

****
(d) Poisson family

****
(e) negative binomial family with r known, 0<p<1

**3.33** For each of the following families:

(i) Verify that it is an exponential family.

(ii) Describe the curve on which the 9 parameter vector lies.

(iii) Sketch a graph of the curved parameter space.

(a) $n(\theta, \theta)$

****
(b) $n(\theta, a\theta)$, a known

****
(c) gamma($\alpha, 1/\alpha$)

****
(d) $f(x|\theta) = C exp (-(x-\theta)^4)$ , C a normalizing constant

**3.38** Let Z be a random variable with pdf f(z). Define $z_{\alpha}$ to be a number that satisfies this relationship:
$$\alpha= P ( Z > z_{\alpha}) =\int_{z_{\alpha}}^{\infty}f(z)dz.$$
Show that if X is a random variable with pdf ($l/\sigma)f((x-\mu)/\sigma$) and $x_{\alpha}=\sigma z_{\alpha}+\mu$, then $P(X>x_{\alpha})=\alpha$. (Thus if a table of $z_{\alpha}$ values were available, then values of $x_{\alpha}$ could be easily computed for any member of the location-scale family.)

According to Theorem 3.5.6, f(x) is pdf, $\mu,\sigma\in\mathbf{R}$, $\sigma>0$. X is a random variable with pdf ($1/\sigma)f((x-\mu)/\sigma$) when and only when Z is a random variable with pdf f(z) and $X=\sigma Z+\mu$

$$\therefore P(X>x_{\alpha})=P(\sigma Z+\mu>\sigma z_{\alpha}+\mu)= P(Z>z_{\alpha})=\alpha $$