---
title: "1.6 pdf & 2.1 Transformation"
subtitle: "STAT 561 Week 3,4"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
     toc: true
     css: "ninjutsu.css"
     seal: yes
     nature:
      highlightStyle: github

---

## {.tabset .tabset-fade .tabset-pills}

### 1.6 Density and Mass Functions 

`2018.10.9`

#### 1. cdf conditions
Theorem 1.5.3 

>A cdf F(x) should satisfy 3 conditions:   
a. $\lim_{x\to-\infty}F(x)=0\ \& \lim_{x\to\infty}F(x)=1$;  
b. F is non-decreasing; and   
c. F is right-continuous, which means $\lim_{x\to\infty}f(x)=f(x)$

#### 2-6. proof condition c.

> let $C_1,C_2$,...be a sequance of events such that $C1\subset C_2\subset$... 

> let $A_1=C_1$ and for $n\ge2,\ A_n=C_n\setminus C_{n-1}$, then

$$\bigcup_{i=1}^\infty A_i=\bigcup_{i=1}^\infty C_i$$

$$P[\lim_{n\to\infty}C_n]=P[\lim_{n\to\infty}\bigcup_{i=1}^nC_i]=P[\bigcup_{i=1}^{\infty}C_i]=P[\bigcup_{i=1}^{\infty}A_i]=\sum_{i=1}^{\infty}P(A_i)=\lim_{n\to\infty}\sum_{i=1}^nP(A_i)$$

$$=\lim_{n\to\infty}\Big[P(A_1)+\sum_{i=2}^nP(A_i)\Big]=\lim_{n\to\infty}\Bigg[P(C_1)+\sum_{i=2}^n\Big[P(C_i)-P(C_i\cap C_{i-1})\Big]\Bigg]$$

$$=\lim_{n\to\infty}\Bigg[P(C_1)+\sum_{i=2}^n\Big[P(C_i)-P(C_{i-1})\Big]\Bigg]=\lim_{n\to\infty}P(C_n)$$

$$So\quad P(\lim_{n\to\infty}C_n)=\lim_{n\to\infty}P(C_n)$$

> Now let $B_1,B_2$,...be a sequance of events such that $B1\supset B_2\supset$... 

$$Then\ B_1^c\subset B_2^c\subset...$$

$$So\quad P(\lim_{n\to\infty}B_n^c)=\lim_{n\to\infty}P(B_n^c)$$

$$left\quad P(\lim_{n\to\infty}B_n^c)=P\left(\lim_{n\to\infty}\bigcup_{i=1}^nB_i^c\right)=P\left(\bigcup_{i=1}^{\infty}B_i^c\right)=P\left({\bigcap_{i=1}^{\infty}B_i}^c\right)$$

$$=1-P\left(\bigcap_{i=1}^{\infty}B_i\right)=1-P\left(\lim_{n\to\infty}\bigcap_{i=1}^nB_i\right)=1-P\left(\lim_{n\to\infty}B_n\right)\quad $$

$$right\quad \lim_{n\to\infty}P(B_n^c)=\lim_{n\to\infty}(1-P(B_n))=1-\lim_{n\to\infty}P(B_n)$$

$$So\quad \lim_{n\to\infty}P(B_n)=P(\lim_{n\to\infty}B_n)$$

> let $B_n=(-\infty,\ x+\frac1n]$, n=1,2,3,...
> Note: $B_i\supset B_2\supset$...

$$\lim_{n\to\infty}B_n=(-\infty,\ x]$$

$$P\left(\lim_{n\to\infty}B_n\right)=P\left((-\infty,\ x]\right)=F_X(x)$$

$$left\quad \lim_{n\to\infty}P(B_n)=\lim_{n\to\infty}P\left((-\infty,\ x+\frac1n]\right)=\lim_{n\to\infty}F_X(x+\frac1n)$$

$$\therefore \lim_{n\to\infty}F_X(x+\frac1n)=F_X(x)$$

#### 7. Probability Density Function
Definition 1.6.3




#### 8. Example


### 2.1 Distribution of Functions of a Random Variable  

`2018.10.11`

#### 1-3. Example

$$F_X(x)=\begin{cases}0 &x\le-1\\ \frac12(x+1) &-1\le x\le1\\1 &x\ge1\end{cases}$$

Let $Y=X^2$, find its cdf

$$F_Y(y)=P(Y\le y)=P(X^2\le y)=P(-\sqrt y\le X\le\sqrt y)=P(X\le\sqrt y)-P(X\le-\sqrt y)=F_X(\sqrt y)-F_X(-\sqrt y)$$

$$(X\le\sqrt y)\cap (X\le-\sqrt y)$$

> Note: remember that our F was continuous

$$F_Y(y)=\begin{cases}0 &y<0\\ \frac12(\sqrt y+1)-\frac12(-\sqrt y+1) &0\le x\le1\\1 &x>1\end{cases}=\begin{cases}0 &y<0\\ \sqrt y &0\le x\le1\\1 &x>1\end{cases}$$

Find the pdf for Y.

Since $F_Y(y)$ was continuous, find 

$$f_Y(y)=\frac{d}{dy}F_Y(y)=\begin{cases}\frac1{2\sqrt y} &0< y\le1\\0 &elsewhere\end{cases}$$

#### 4-7. Special cases

Assume the cdf is  continuous. Let Y=g(X) be a tranformation of X

Suppose g increase (monotone increasing)

$$F_Y(y)=P(Y\le y)=P(g(X)\le y)=P(X\le g^{-1}(y))=F_X(g^{-1}(y))$$

$$Now,\ f_Y(y)=\frac{d}{dy}F_Y(y)=\frac{d}{dy}F_X(g^{-1}(y))=f_X(g^{-1}(y))\frac{d}{dy}g^{-1}(y)=f_X(x)\frac{dx}{dy}$$

$$But\ y=g(x),\quad so x=g^{-1}(y)$$

Suppose g decrease

$$F_Y(y)=P(Y\le y)=P(g(X)\le y)=P(X\ge g^{-1}(y))=1-F_X(g^{-1}(y))$$

works since F was continuous.

$$f_Y(y)=\frac{d}{dy}F_Y(y)=\frac{d}{dy}(1-F_X(g^{-1}(y)))=-f_X(g^{-1}(y))\frac{d}{dy}g^{-1}(y)=-f_X(x)\frac{dx}{dy}$$

> Summary: Case 1 g increase, Case 2 g decrease

$$f_Y(y)=f_X(x)|\frac{dx}{dy}|$$

#### 8-9. Example

let X be a continuous rv with pdf

$$f_x(x)=\begin{cases}1 &0<x<1\\0 &elsewhere\end{cases}$$


$$f_Y(y)=\begin{cases}\frac12e^{\frac{y}2} &0<y<\infty\\0 &elsewhere\end{cases}$$

#### 10-12. Example

$$f_x(x)=\frac1{\sqrt{2\pi}}e^{-\frac{x^2}2}\quad -\infty<x<\infty$$

Let $Y=X^2$, not monotone, so no shortcut

$$F_Y(y)=P(Y\le y)=P(X^2\le y)=P(-\sqrt y\le X\le\sqrt y)=P(X\le\sqrt y)-P(X\le-\sqrt y)$$

> Unfortunately, there is no closed form for $F_X(x)$


$$f_Y(y)=\frac{d}{dy}F_Y(y)=\frac{d}{dy}[F_X(\sqrt y)-F_X(-\sqrt y)]=f_x(\sqrt y)\frac1{2\sqrt y}-f_x(-\sqrt y)\frac{-1}{2\sqrt y}$$

$$=\frac1{\sqrt{2\pi}}e^{-\frac{y}2}\frac1{2\sqrt y}+\frac1{\sqrt{2\pi}}e^{-\frac{y}2}\frac1{2\sqrt y}=\frac1{\sqrt{2\pi}}e^{-\frac{y}2}\frac1{\sqrt y}\quad for\ y>0,\ -\infty<x<\infty$$

$$f_Y(y)=\begin{cases}\frac1{\sqrt{2\pi y}}e^{-\frac{y}2} &y>0\\0 &elsewhere\end{cases}$$

`2018.10.16`

#### 1.2. Another transformation example

Let X have cdf $F_X(x)$ and assume that F is continuous and monotone increasing. define Y=F(X). Find the pdf for Y

$$f_Y(y)=f_X(x)|\frac{dx}{dy}|\quad and\quad \frac{dx}{dy}=\frac1{\frac{dy}{dx}}=\frac1{f_X(x)}$$

$$So\quad f_Y(y)=f_X(x)\frac1{f_X(x)}=1\quad for\ 0\le y\le1$$

