---
title: 'USP537 Problem Sets'
author: ""
date: "Winter 2019"
output: html_document
---

#  {.tabset .tabset-fade .tabset-pills}

## Problem Set 1

 1. Portland’s transit agency TriMet wants to increase transit usage by 15%. They expect no changes in the demand for transit and will lower the fare to attract the additional riders. The estimated price elasticity of demand is 0.3(actual elasticity used by TriMet).

 a. Calculate the percentage change necessary in fares to achieve the increased transit usage and the change in fare box revenue (use simple percentages rather than the midpoint elasticities). 

When no changes in the demand for transit, the value of usage moves along the MD curve, then 

$$\frac{\Delta Q/Q}{\Delta P/P}=E\implies\Delta P/P=\frac{\Delta Q/Q}{E}=\frac{0.15}{0.3}=50\%$$
$$TR=50\%P(1+15\%)Q=57.5\%PQ$$

50% decrease in fares could achive the increase transit usage by 15%. The new revenue will be 57.5% of previously revenue.

 ---
 
 b. Would you expect the long-run price elasticity of demand to be larger or smaller? Explain why?

Demand tends to be more elastic in the long rung rather than in the short run, because when prices change consumers often need more time to respond and change their shopping habits such as househould or firms' location, vehicle ownership, further change travel behaviors. (Mankiw, 2004).

 ---
 
 c. Do you expect that costs will rise? Consider total cost, fixed cost, and variable cost. Explain why it would or would not.

If the extra riderships don't exceed current transit capacity, fixed cost would not change. The variable cost will rise for the addtional operation cost such as energy consumption and labor cost. Thus, the total cost would increase. If current transit is underload, the change would be tiny.

 ---
 
 2. In “The Urban Transportation Problem: A Reexamination and Update”, by JohnF. Kain([GTW] Chap11), the author concludes the paper with a recommendation: “There remains a strong, if not compelling, case to begin charging road users the full social cost of their road use, for reversing the public ownership and operation of transit services, and for stopping wasteful expenditures on ineffective rail systems.” Please write a short analysis (approximately1 page, single-spaced, typed) highlighting your arguments either in support of or against this recommendation.


 ---
 
 3. Rail City operates a train service on weekdays only. The fixed cost is $120,000 per day. The operating cost is $100 per train-hour, with service adjusted to provide 200 rides per train-hour. This yields a marginal cost of $0.50 per rider. Use this where information on marginal cost is needed. The following information is available regarding cost and demand on a daily basis.

|        |Cost|Revenue|Demand
|---     | ---|--- | ---
|Fixed   |$FC=\$120000$| |
|Marginal|$MC=0.5$|$MR=10-0.0002Q$|$P=\$10-0.0001Q$|
|Total   |$TC=FC+VC=\$120000+0.5Q$|$TR=P\times Q=10Q-0.0001Q^2$|

 a. What number of riders will use the system if the price is set equal to marginal cost(This is essentially equivalent to assuming that a benevolent social planner sets the price so that maximum efficiency is reached)? How much service will be provided (Q*)? What are the subsidies or profits at this level of cost and price? What is the consumer surplus?

Let $P=MC$, then $10-0.0001Q=0.5\implies Q=95000$ riders.

There will be 95000 riders and same service will be provided.

The subsidies/profits is $TR-TC=(10Q-0.0001Q^2)–(120000+0.5Q)=47500-167500=-\$120000$

The consumer surplus is $CS= 0.5\times 9.5\times95000=\$451250$

 ---
 
 b. If the price is raised to $2.00, how many people will use the train, and what happens to total revenue? What subsidy is required? Calculate any efficiency loss or gain associated with this change. Compare the change in subsidy with the change in consumer surplus.

When $P=\$2.00$, there will be $Q=\frac{10 - 2}{0.0001}=80000$ riders.

The total revenue is $TR= 10Q–0.0001Q^2=800000–640000=\$160000$.

The subsidies/profits is $TR-TC=(10Q-0.0001Q^2)–(120000+0.5Q)=160000–160000=\$0$

The efficiency loss or gain:
The deadweight loss is $DWL = 0.5\times\Delta P\times\Delta Q=0.5\times(2.0-1.5)\times(95000-80000)=\$11250$

The change in subsidies are $120000-0=\$120000$, which is less than the change in consumer surplus $\Delta{CS}=451250-0.5\times 2\times80000=451250-320000=\$131250$

 ---
 
 c. Suppose that a monopolist is allowed to run the system and set price. What quantity ($Q_m$) and price ($P_m$) will be set and what profits or losses will be generated if the monopolist wants to maximize profits? Calculate any efficiency loss associated with this level of service.

When $MR=MC$, the monopolist maximizes profits.

$10–0.0002Q_m=0.5\implies Q_m=47500$ riders, then

The price is $P_m=10–0.0001Q=10–4.75=\$5.25$

The maximum profit is $TR-TC=9.5\times47500-0.0001\times47500^2–120000=\$105625$

The deadweight loss is $DWL=\times\Delta P\times\Delta Q=0.5\times(5.25-0.5)\times(95000-47500)=\$112812.5$

 ---
 
 d. Could the monopolist make a profit if fixed costs are $250,000 per day?  Does this mean that it would be a mistake to build the train based on economic benefits and costs for this level of fixed cost? Explain why you think it would or would not be from an economic efficiency perspective and include appropriate calculations.

Let $FC=\$250000$, the maximum profit is $TR-TC=(10Q-0.0001Q^2)–(250000+0.5Q)=-\$24375$.

The monopolist won't make a profit. To examine the efficiency, we should compare total cost with total revenue and consumer surplus. 

For $P=10-0.0001\times Q$, $CS=0.5*(10-P)*Q=0.5\times[10-(10-0.0001\times Q)]\times Q=0.00005Q^2$

$$CS+TR–TC=0.00005Q^2+(10Q-0.0001Q^2)–(250000+0.5Q)=9.5Q-0.00005Q^2–250000$$

Take the derivative with respect to $Q$ and suppose the result $9.5-0.00005Q=0$. When $Q=95000$, the maximum profit is $9.5\times95000-0.00005\times95000^2–250000=\$652500$

The reult shows that the train is worth to be bulit because total revenue and consumer surplus are larger than total cost.

 * Reference

_Mankiw (2004) “Principals of Macroeconomics”,South-WesternCollegePub,UK_

 