---
title: "Case Study Discussion"
subtitle: "USP 537"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  xaringan::moon_reader:
    css: "example.css"
    seal: yes
    nature:
      highlightStyle: github

---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
options(width = 2000)
options(repos="https://cran.rstudio.com")
```


### 01/31	Bus Rapid Transit

Cervero, R. (2013). Bus Rapid Transit (BRT): An Efficient and Competitive Mode of Public Transport. IURD Working Paper 2013-01.
Nelson, A. C., Appleyard, B., Kannan, S., Ewing, R., Miller, M., & Eskic, D. (2013). Bus Rapid Transit and Economic Development: Case Study of the Eugene-Springfield BRT System. Journal of Public Transportation, 16(3).
Ortegon-Sanchez, A., & Tyler, N. (2016). Towards multi-modal integrated mobility systems: Views from Panama City and Barranquilla. Research in Transportation Economics, 59, 204-217.
Deng, T., & Nelson, J. D. (2013). Bus Rapid Transit implementation in Beijing: An evaluation of performance and impacts. Research in Transportation Economics, 39(1), 108-113.

---

### 02/07	Parking

Pierce, G., & Shoup, D. (2013). SFpark: Pricing Parking by Demand. ACCESS Magazine, 43.
Arnott, R., & Inci, E. (2006). An integrated model of downtown parking and traffic congestion. Journal of Urban Economics, 60(3), 418-442.
Anderson, S. P., & de Palma, A. (2004). The economics of pricing parking. Journal of Urban Economics, 55(1), 1-20.
Inci, E. (2015). A review of the economics of parking. Economics of Transportation, 4(1), 50-63.
---

### 02/14	Fuel Economy Standards

Anderson, S. T., Parry, I. W., Sallee, J. M., & Fischer, C. (2011). Automobile fuel economy standards: Impacts, efficiency, and alternatives. Review of Environmental Economics and Policy, 5(1), 89-108. Portney, P. R., Parry, I. W., Gruenspecht, H. K., & Harrington, W. (2003). Policy Watch: The Economics of Fuel Economy Standards. The Journal of Economic Perspectives, 17(4), 203-217.
West, J., Hoekstra, M., Meer, J., & Puller, S. L. (2017). Vehicle miles (not) traveled: Fuel economy requirements, vehicle characteristics, and household driving. Journal of Public Economics, 145, 65-81.

---

### 02/28	Congestion Charge

Leape, J. (2006). The London congestion charge. The Journal of Economic Perspectives, 20(4), 157-176.
Albalate, D., & Bel, G. (2009). What local policy makers should know about urban road charging: Lessons from worldwide experience. Public administration review, 69(5), 962-974.
Vonk Noordegraaf, D., Annema, J. A., & Van Wee, B. (2014). Policy implementation lessons from six road pricing cases. Transportation Research Part A: Policy and Practice, 59, 172-191.
---

### 03/14	Financing Transportation

Ardila-Gomez, A., & Ortegon-Sanchez, A. (2016). Sustainable Urban Transport Financing from the Sidewalk to the Subway: Capital, Operations, and Maintenance Financing. World Bank Publications.

[Council of State Governments - Transportation Finance](http://knowledgecenter.csg.org/kc/category/policy-area/transportation/administration-and-finance)

Rall, J., National Conference of State Legislatures, & American Association of State Highway and Transportation Officials (Eds.). (2011). Transportation governance and finance: a 50-state review of state legislatures and departments of transportation. Washington, DC: National Conference of State Legislature.

---


