---
title: 'USP537 Notes'
author: ""
date: "Winter 2019"
output: html_document
---

#  {.tabset .tabset-fade .tabset-pills}

## I. Introduction to Transportation Economics

### Economics problems

 - How to allocating scarce resources  
 - Between transportation and other uses  
 - Between different transportation modes  
 - Scarcity Choice Opportunity Costs  

### Transport Problems and Economic Theory

 - Consumer surplus  
 - Cost allocation models  
 - Marginal cost pricing principle  
 - Discrete choice models  

### History of Transit

 - Prior to mid-1800s: Walk
 - Mid-1800s to 1900: Horse-drawn rail
 - 1900: Electric railways
 - 1910s: Motor buses
 - 1970s: Decline of LRT
 - 1970s: Congress approves capital grants for new rail starts

### History of the Road System

1890s: interest by railroads, farmers, autos pushed for roads
1916: Federal Aid System started with $75 million for highway improvements over 5 years
1919: First state gas tax implemented
1930s: Highway improvements accelerated increased technology in trucks & buses
1944: State Interstate Highway System
1945: State highway system (90% Federally financed)

Trends in VMT per capita

Mode Share Trends

Mode Share

### Transportation Public Policy

 - Subsidies
   * Urban Transit (capital & operating)
   * Highway Distortions lead to
   * Problems: shifted land use
     + Opportunity cost patterns
     + Cost-effectiveness
     + Underestimation of capital cost of building and maintenance
Distortions lead to shifted land use patterns

 - Public ownership
   * Potential problems:
   * Reduced productivity and cost-effectiveness
   * Regulated high supply

Criteria for economic evaluation

 - Efficiency
 
 - Cost-effectiveness
 
 - Equity
 
## Microeconomic Foundations

### Microeconomics review

 - Supply & Demand
 - Efficiency
MC = MR
TC = FC + VC
TR = P x Q
Profit = TR – TC
Monopolist profit-maximization; deadweight loss

 - Elasticities:
Price elasticity of demand
Income elasticity of demand
Cross-price elasticity of demand

 - Demand
 
   * Law of demand: the quantity demanded of a good falls when the price of the good rises, other things equal;  downward sloping
   
   * Derived from consumer utility maximization theory
   
   * Demand curve represents MB (marginal benefit)
   
   * Shifts in demand
   
   * Transportation demand
   
     + Derived demand
     
     + Time-specific

 - Supply
 
  * Law of supply: an increase in price results in an increase in quantity supplied, all else equal
  
  * Derived from producer profit maximization theory
  
  * Supply curve represents MC (marginal cost)
  
  * Shifts in supply
  
 - Elasticities:
 
  * Price elasticity of demand: percentage change of quantity demanded in response to a 1% change in price; price sensitivity of consumer demand
  
$$E=\frac{\text{Percentage change in }Qd}{\text{Percentage change in }P}=\frac{\frac{\Delta Q}Q}{\frac{\Delta P}P}$$
  
  * Income elasticity of demand
  
  * Cross-price elasticity of demand

 - Demand: MB = 10 – Q
 - Supply: MC = Q
 - Equilibrium occurs at MB = MC
 - Q* = 5 (PS) 
 - P* (market clearing price) = $5
 - What is consumer surplus (CS), producer surplus (PS) and total surplus (net benefit)?

 - Efficiency & Market Equilibrium for Monopolist
  * Demand: $P=5–\frac{Q}{1000}$
  * Fixed cost: $FC=\$5000$ (each day)
  * Operating cost is $\$50$ per hour, and can provide 100 rides
  * What is the MC? $MC=\$\frac{50}{100} = \$0.50$
  * Total cost: $TC=FC+VC=5000+0.5Q$
  * Total Revenue: $TR=P\times Q=(5–\frac{Q}{1000})Q=5Q–\frac{Q^2}{1000}$

### Critical Issues in Transportation

 - Congestion
 - Energy, environment and climate change
 - Infrastructure
 - Finance
 - Equity
 - Emergency preparedness, response and mitigation
 - Safety
 - Institutions
 - Human and intellectual capital
 - Reliability & resilience of transportation systems
 - Safety
 - Energy, environment and climate
 - Infrastructure funding

### Microeconomics Review

 - Demand: shifts caused by income, price of other goods and services (complements and substitutes), tastes/trends, expectation of future price changes
  * Demand for transport is a derived demand

  * It is time-specific

  * Follows peaks and troughs throughout day, season, week, etc.

 - Supply: 
 
shifts caused by cost of production, government policy, price of related goods, natural shocks, technology


 - Elasticities: 

Effects of changes in tolls, transit fares, congestion pricing, fuel price
On VMT, # of cars, # of trips, trips on public transit, fuel consumption, vehicle fuel economy



 - Example:
 
Demand: $P=5–\frac{Q}{1000}$

Fixed cost: $FC = \$5000$ (each day)

Operating cost is $\$50$ per hour, and can provide 100 rides  what is the MC? $MC = \$\frac{50}{100}=\$0.50$

Total cost: $TC = FC + VC = 5000 + 0.5Q$

Total Revenue: $TR=P\times Q=(5–\frac{Q}{1000})Q=5Q–\frac{Q^2}{1000}$

  a). What is the equilibrium number of rides if price is set at MC? MR = MC (marginal revenue is P in perfect competition!)
  
$5–\frac{Q}{1000}=0.50$

$Q^*=500$

What is the TC? TR? Profit?

$TC=5000+0.5(4500)=5000+2250=7250$

$TR=0.50\times 4500=2250$

$Profit=2250–7250=-\$5000$ (negative!! Which equates to a subsidy for a publicly owned agency)

  b). Elasticity between (P,Q) = (1,4000) to (2, 3000)? How to interpret it?

  c). If the operator is a monopolist, what is the P, Q, profit and deadweight loss?

MR = derivative of $TR=5–\frac{Q}{500}$ (law of demand)

MR = MC to decide profit-maximizing quantity ; $5–\frac{Q}{500}=0.50$ ; $Q_m=2250$

P is determined with demand function; $P = 5 – \frac{2250}{1000} = \$2.75$

$DWL=0.5\times2.25\times1750=\$1968.75$

$Profit=(2.75\times2250)-(5000+0.5\times2250)=\$62.50$



## II. Demand for Transportation

#### Types of Demand

 - When to travel
 - To what destination
 - What mode of transportation
 - What route to take

#### Choices impacting transportation demand

 - Decisions made by organizations
 - Decisions made by households or individuals
 - Complexities
  * Interrelated decisions
  * Spatial and temporal
  * Quality of service
  * Derived demand
  * Supply and demand interactions via congestion
  * Heterogeneity

#### Transportation demand and Economic Development

 - “Chicken or the egg”?
 - Supply led view transportation; economic development
 - Demand led view Economic development; transportation

#### Theory of Consumer Choice

https://en.wikipedia.org/wiki/Consumer_choice

 - Continuous utility function (X1=VMT; X2=other goods) –increasing & quasi-concave
 - Consumer utility maximization problem
 - Derivation of income elasticity of demand
 - Derivation of demand curve
 - Price changes; substitution & income effect

### Aggregate Demand Models

#### Income elasticities of motor vehicle ownership
`p.331-336 Income Elasticities of Motor Vehicle Ownership and Use`


 - Table 10-2. Income Elasticities of Motor Vehicle Ownership and Usage
 
Four stylized facts emerge in the estimates shown in table 10-2. 
  + First, income elasticities from time-series data are typically smaller than those from cross-section data. That is because cross-section analyses produce long run elasticities, and long-run behavior is generally more responsive to income changes than short-run behavior. Roughly speaking, long-run income elasticities of motor vehicle (especially car) ownership are greater than 1.0, while short-run income elasticities are less than 1.0. 
  + Second, income elasticities from urban-level data are similar to or smaller than those from country-level data, largely because there are more competing modes of transportation and greater congestion in urban areas, both of which reduce the attraction of motor vehicles. In fact, the long-run elasticities from urban-level data are closer to those from country-level data than are the shortrun elasticities.
  + Third, income elasticities are generally larger for automobiles than for commercial vehicles, supporting the economic hypothesis that the share of passenger cars in the motor vehicle fleet increases with income. 
  + Finally, income elasticities of motor vehicle use are less than unity, smaller than long-run income elasticities of motor vehicle ownership, and smaller for households with one vehicle than for those with two, indicating that motor vehicle use increases less rapidly than motor vehicle ownership. 

These findings also support the earlier economic hypotheses.

 - Figure 10-1. Per Capita Income and Motor Vehicle Ownership in Fifty Countries and Thirty-Five Cities

figure 10-1 indicates that motor vehicle ownership increases somewhat more rapidly with income at the national level than at the urban level.

 - Vehicle ownership
  * Population density elasticity of vehicle ownership= -0.4 (urban) & -0.1 (national)
  * Spatial spread of economic activity
  * Urban: density ↔ motorization
  * National: urbanization ↔ income
  
#### Income elasticities of road length

 - Road length
  * F(size of economy, geographical area, population, income per capital, population density)
  * Population density elasticity of road length
  
`p.339-344 Road Provision`

 - Figure 10-2. Per Capita Income and Per Capita Road Length, Fifty Countries and Thirty-Five Cities
 
 The size of the national road network is associated with the size of the economy, geographical area, population, income per capita, and population density. 
 
 Per capita income is a major determinant of road length at the national level. 
 
 Both paved and total road length increase at a constant rate with per capita income, as can be seen in figure 10-2.
 
 Estimates at the national level (using the techniques employed for vehicle ownership) find no saturation level for road density with respect to per capita income. 
 
  - Table 10-4. Estimated Effects of Population, Per Capita Income, and Population Density on Road Length
 
 Paved road length has an elasticity of 1.0 with respect to income (when income increases by 1 percent, paved road length increases by 1 percent), while overall road length increases only about half as fast as income (table 10-4).
 
 Population is a significant determinant of national total and paved road length, whereas population density affects only total road length.
 
 The major implication of these findings is that at the national level, paved road length increases with per capita income at roughly the same rate as vehicle ownership. As a result, congestion does not appear to be a current or growing problem for the national road network in most countries.
 

#### Case Study 1 Demand for gas and automobile travel
  
 - Gt = f(Real Gas Price, Real Personal Income, Population, Season, Gasoline Crisis)
Hypotheses:

  * Law of demand
  * Opportunity cost = real gas price + queuing cost
  * Gasoline is normal good
  * Market demand is horizontal sum of individual demands
  
#### Case Study #2 – Demand for urban rail rapid transit
  
 - Estimation results
  
### Disaggregate Demand Models

#### Random Utility Model (RUM)  

 - Systematic component
 - Random component

`p.15 The Random Utility Framework`

$$U_j = V(X_j, S;\beta) + \varepsilon_j $$


 - Example:
Two choices – auto or bus

If $U_{bus} > U_{auto}$, choose bus
If $U_{bus} < U_{auto}$, choose auto

#### Binomial Probit

`p.17 Binary Probit and the Value of Travel Time`

 - Lave (1969) estimation on Chicago commuters:

$$V=-2.08D^T-0.00759w\cdot t-0.0186c-0.0254(Inc\cdot Dist\cdot D^T)+ 0.0255(Age\cdot D^T)-0.057(Female\cdot D^T)$$

where DT is an alternative-specific dummy variable equal to 1 for transit and 0 for auto. It enters the model independently (in the first term) and also interacts with the traveler's income (Inc), trip distance (Dist), age, and a dummy variable indicating whether the traveler is female. The traveler's wage rate is denoted by w, travel time by t, and travel cost by c. Note that $D^T$, t, and c all vary from one mode to the other, whereas w, Inc, Dist, Age, and Female do not. Lave's more detailed results show that all estimated parameters are statistically significant except the last. The model indicates that travelers are less likely to take transit if their income or trip distance increases, but more likely to take transit as they become older. 

This utility function is linear in travel time and cost. The value of travel time (VOT), defined as the marginal rate of substitution between time and cost, is just the ratio of the time and cost coefficients of that linear relation:

$$VOT =\frac{\delta V}{\delta t}\frac{\delta c}{\delta V}=\frac{-0.00759w}{-0.0186} = 0.41w$$

Lave's finding, which is representative of other estimates in the literature, is that time is valued at 41 percent of the average wage rate. Note that the variables in this model were specified so that VOT is proportional to the wage rate. This approach is consistent with models of time allocation, which suggest that a person's trade-off between travel time and money is strongly related to his or her possibilities for earning money in the labor market.

#### Logit

`p.19 Multinomial Logit and Urban Mode Choice`

 - McFadden et al. (1977)
 
multinomial logit for urban work trips

auto, bus/walk, bus/auto, carpool

$$V = -0.0412c/w – 0.0201t – 0.0531t^0 – 0.89 D^1 – 1.78 D^3 – 2.15 D^4$$

  * What is the probability of each mode (mode share)?

$$P_i=\frac{e^{V_i}}{\sum_{j=1}^Je^{V_j}}$$

  * Assumption: Independence from irrelevant alternatives (IIA)

#### Logit Example

$$V = -0.0412c/w – 0.0201t – 0.0531t^0 – 0.89 D^1 – 1.78 D^3 – 2.15 D^4$$

What are the mode splits estimated by this model?

#### Nested Logit

 - Lam and Small (2001)
 
  * Choices not hierarchical
  * Simultaneous
  * Allows correlation between choices in same nest

$$V = -0.874 D^{tag}+ 0.0239 IncD^{tag}–0.767 ForLangD^{tag}–0.785 D^{lane}–0.356c –0.150t –0.217R + \text{other terms}$$
  

## Accessibility and Economic Opportunity

“post-war changes in urban structure and urban transportation systems have conferred significant improvements and greater satisfactions on the majority, [but] they almost certainly have caused a relative deterioration in the access to opportunities, if not in the actual mobility of a significant fraction of the poor.”
–Meyer (1968)

### Spatial Mismatch Hypothesis

 - Kain(1968): 
 
 Employment opportunities; Workers
 
 - Concentration of jobs increased in suburbs 

white households dispersed to suburban areas while black households remained in central cities

black households are now located far away from suburban jobs

 - Suburbanization of jobs (Fujita and Thisse2002; Cerveroet al. 2002; Iceland and Harris 1998)

 - Disconnection of black households from jobs (Martin 2001; Raphael and Stoll 2002; Stoll 2006)

### Factors of Spatial Mismatch Hypothesis

 - Gobillonet al (2007)
  * Commuting costs are high
  * Job search efficiency decreases with distance to jobs (information)
  * Distant workers search less intensively
  * High search costs cause workers to restrict spatial search
  * Employer discrimination: redlining or statistical discrimination
  * Employer refuse to hire distant workers
  * Customer discrimination

### Policy Directions

 - Bring jobs to people
 - Bring people to jobs
 - Connecting people to jobs

## III. Transportation and Land Use

#### General concepts

 - R = annual rental payment for land (reflecting highest private use value of land)
 - Market Value = R / interest rate
 - Land rent is input cost of production

#### Transportation & Land Use

 - Bid-rent function: the willingness-to-pay (WTP) for a piece of land for a given level of profit (per acre)
 
 - Firm location choice
 
 - Household location choice

#### Location equilibrium in monocentriccity

### Application: Streetcar

#### Relative locations before streetcar

#### Effect #1: Reduced commute cost

#### Effect #2-1: Reduced wage effects on residential bid rents

#### Effect #2-2: Reduced wage effects on business bid rents

#### Transportation ; Land use

`p. 412-413 Residential Development`

Figure 12-1. Density of New Residential Development by Decade for Selected Cities

#### Technologies and their effects on travel speeds and times

Table 12-1. Effects of Technological Innovations on Travel Speeds and Times

#### International comparisons

## IV. Project Evaluation

 - Cost-benefit analysis (CBA)
  * Pareto improvements?
  * Potential Pareto improvements (Kaldor-Hicks Criteria)
 - Why perform CBA for transportation choices?
  * Limited funding for transportation investments
  * Linkages between transportation investments and land use, economic, environmental and energy policy concerns

 - Net Social Benefit
  * NSB = Benefit – Cost
   1. Specify alternatives/define situation
   2. Decide whose benefits and costs count (standing)
   3. Identify the impact categories (benefits or costs) & measurement indicators
   4. Predict the quantitative impacts over the life
   5. Monetize impacts
   6. Discount benefits & costs to obtain present values
   7. Compute NPV of each alternative
   8. Perform sensitivity analysis
   9. Make recommendation

#### #1-#2: Define the situation & scope

 - Changes in resource allocation
 - Comparing between alternatives
  * What resources are at stake?
  * What jurisdiction should CBA be done for?

#### #3: Costs

 - Survey Approach
 - Engineering Approach
 - Combined Approach

#### #3: Evaluating Costs

 - Price mechanism  true social value/cost
 - Shadow price: estimated value of an input or output to the economy or society as a whole
  * Marginal opportunity cost – value of the best alternative use of the input
  * Related to market price, but not exactly the same

#### #3: Costs vs Transfers

 - When resources are not used up nor created, but just shifted from one set of individuals to another, we say the resources are transferred.
 - Transfers
  * Do not change total resources in the community
  * Changes distribution of the resources

#### #3: Benifits

 - Types of benefits
  * Resources measurable in monetary terms: goods and services sold in the market places  Price
  * Resources measurable in physical units, but not in monetary terms.
  * Resources valued by the community, but not measurable by any means.

#### #3: Benifits vs Transfers

 - [EX] Are jobs a benefit?
  * If the economy is at full-employment (which is often the assumption of CBA), the opportunity cost of using workers is that they are not used somewhere else.
  * Thus, the new jobs are simply a transfer of workers from one sector to another.
  * Locally: net gains in local employment?

#### #3: Valuing Benefits

 - Types of Values
  * Use Value
   + Passive use value
  * Option Value
  * Nonuse Value
   + Existence value
   + Bequest value

#### #3: Valuing Benefits - Methods

 - Revealed Preference Method – valuing based on actual observable choices
  * Market Prices: Market demand reflects the consumer’s WTP, so prices can be used to evaluate loss of value
  * Benefits Transfer
  * Meta-analysis
  * Indirect:
   + Travel cost method
   + hedonic property values / hedonic wages

#### Revealed Preference – Benefits Transfer

 - Benefits Transfer Approach
  * The application of existing information & knowledge to new contexts
  * Useful when collecting primary data and analysis is impractical (cost or time)
  * 3 important features
   + Policy context must be well-defined
   + Data must meet certain criteria
   + Study site and new site should correspond
  * Limitations

#### Indirect Revealed Preference – Hedonic Analysis

 - Hedonic Analysis – Uses the changes in prices of related goods to infer a WTP for a healthier environment or less risky environment (with multiple regression analysis)
  * Hedonic Property Value
  * Hedonic Wage Method

#### Indirect Revealed Preference – Hedonic Property Value
 - Hedonic Property Value Example (Mendelsohn et al. 1992)
  * PCB contamination in New Bedford, MA
  * Compare change in prices for houses sold before and after contamination became public. Control for all other factors affecting home costs.
  * Houses closest to the contaminated area: price declines of \$9,000; in area of secondary pollution, declines of \$7,000. Total damages to home-owners: \$36 million
  * Firms paid out at least $20 million in natural resource damage claims

#### Indirect Revealed Preference – Hedonic Wage Method

 - Hedonic Wage Method – similar to hedonic property value, but attempts to isolate the component of wages that serve to compensate workers in risky occupations for taking on the risk

|Occupation|Wage (hourly)|Risk of Death (statistically)
|-------|---|---
Backhoe operator|$15|.0001
Bulldozer       |$16|.00015
Grader operator |$17|.0002
Lawnmower       |$18|.00025

Plot expected earnings over lifetime of workers for various occupations and then extrapolate from the estimated line to get VSL

 - Problems
  * Accurate information?
  * Sample selection bias
  * Involuntary nature of risk
  * Are labor market choices to accept higher risk really “choices”?
  * Unpaid workers

#### Value of a Statistical Life (VSL)

 - EPA: \$7.8 million (2008) \$6.9 million
 - Water Division (EPA): $8.7 million
 - Viscusi meta-analysis study: $3 – 7 million
 
 - EX: Suppose there is regulation costing $18 billion to enforce but will prevent 2,500 deaths. How much is spent to save every life?

\$18 billion / 2500 = \$7.2 million per life saved

Would it have passed EPA’s CBA in 2006 or 2008?

#### VSL - Policy Implications

 - Cost per life saved ranges from \$100,000 for unvented space heaters to \$72 billion for a proposed standard to reduce occupational exposure to formaldehyde.
 
 - Assuming that the figures are estimated correctly, how is economic efficiency maximized? (first equimarginal principle)
  * Policies only when MB > MC
 - Should the government strive to maximize economic efficiency?

#### #3: Valuing Benefits - Methods
 - Stated Preference Method – valuing based on a survey where the respondents state their value
  * Contingent Valuation: Asking through a survey, what value respondents place on preserving a species, for example.

 - Problems involved with Stated Preference
  * Strategic bias
  * Information bias
  * Starting-point bias
  * Hypothetical bias
  * WTP vs WTA
  * “warm glow” effect
  * Embedding bias – context of problem

#### Stated Preference – Contingent Valuation

 - Economists disagree about the reliability of CV analysis. But doing a ‘state of the art’ job can be very expensive
  * Analyses of Exxon Valdez oil spill: $3 million
  * Estimated lost passive use value: $2.8 billion
 - CVs provide the only available means for estimating nonmarket benefits based primarily on existence value, so they are widely used

#### #6-#7: Discounting and NPV

 - Office of Management & Budget 10-year (whitehouse.gov/omb/) 10%  (1992) 7%  (2013) 2%
 - Congressional Budget Office: 2%
 - EPA: 5.875%
 - EPA Analysis of Waxman-Markey Bill: 5%
 - Stern Review: 1.4%

$$NPV=\sum_{n=0}^N\frac{NB_n}{(1+n)^n}= \frac{NB}i$$

#### An Alternative – Cost-Effectiveness Analysis

 - Establish objective (i.e. how much pollution control?)
 - Optimize (i.e. choose the most cost-effective options given the objective)

## V. Supply of Transportation

#### LR vs SR Costs

 - Short-run (SR) costs
  * Some inputs are fixed – machinery, land, infrastructure
  * Other inputs are variable – labor, materials
 - Long-run (LR) costs: all inputs are variable

#### Average Costs & Economies of Scale

 - LR average cost (LAC) is the envelop of SR average costs
 
Economies of scale occurs when MC < AC; AC is falling

#### Firm Theory
`p.64-67`
 - Inputs: K (capital), L (labor)
 - Output: y = f(K,L)
 - Costs: C = rK + wL, where w is wage and r is rent
 - Production isoquants: increasing in inputs, quasi-concave
 - Firms are profitmaximizing
  * In other words, they are also cost-minimizing given a production level (and prices for inputs)

#### Firm production function

- Cobb-Douglas Production Function
$$y = f(K,L) = AK^αL^βF^e (α, β > 0)\begin{cases}\text{increasing returns to scale, if}&α+β > 1\\ \text{constant returns to scale, if}&α+β = 1 \\ \text{decreasing returns to scale, if}&α+β < 1 \end{cases}$$
where y measures the amount of electricity produced, K measures capital input, L measures labor, and F measures fuel, and where A, a, b, and e are constants.

 - Corresponding cost function:
 
$$C = By^\frac{1}{(a + b + e)} (P_K)^\frac{a}{(a+b+e)} (P_L)^\frac{b}{(a + b + e)} (P_F)^\frac{e}{(a+b+e)}$$

#### Firm Cost Function

 - Taking natural log of both sides:

$$\ln C = d_0 + d_1 \ln y + d_2\ln{P_K} + d_3\ln{P_L} + d_4\ln{P_F}$$

, where $d_0 =\ln B, d_1 =\frac{1}{(a + b + e)}, d_2 =\frac{a}{(a + b + e)}, d_3 =\frac{b}{(a + b + e)}, d_4 = \frac{e}{(a+b+e)}= (1-d_2-d_3)$. The coefficient d1 is the elasticity of cost with respect to output. It shows the percentage change in total cost that will be incurred if the level of output is increased by 1 percent.

 - Constant elasticity of cost for each input
 - Elasticity of substitution = 1
 - Constant share of inputs

#### Example -Caves, Christensen and Tretheway(1983)

`p.78 An Illustration of Economies of Density and Size`
**Long-run Cost Function**

$$\ln C=\text{constance}+0.836\ln Y+0.131\ln N-0.135\ln D-0.277\ln G+0.356\ln w+0.166\ln f+0.478\ln r+\text{time and firm dummies below}$$

 - How do factor prices affect cost?

|   |   | Y | N | D | G | w | f | r |
|---|---|---|---|---|---|---|---|---|
| | |output|# of points|stage length|load factor| wage rate|fuel price|cost of capital material|

 - What are shares of total cost for each factor?
 - Economies of scale (output)
 - Economies of density
  * Increase in output (Y), but not # of points (N)
 - Economies of size
  * Increase in both output (Y) and # of points (N)
 - Economies of scope?
  * If y1 is passenger and y2 is freight, then economies of scope occur when: C(y1,y2) < C(y1,0) + C(0,y2).
 - Cost-reducing technological change over time?

Finding 1: How will increases in factor prices affect total costs?

Finding 2: What does the cost study indicate about the share of total costs expended on the various factors of production? 

Finding 3: What does the study indicate about economies of density? 

Finding 4: What does the study indicate about economies of size?

Finding 5: Is there evidence of cost-reducing technical change over time?