---
title: "Reading reflections"
subtitle: "USP 570"
author: 'Shen Qu'
date: "Week 4"
output:
  word_document: null
  pdf_document: default
bibliography: bib_usp570.bib
mainfont: Times New Roman
geometry: margin=1in
spacing: double
fontsize: 12pt
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
knitr::kable
options(width = 2000)
options(repos="https://cran.rstudio.com")

# install.packages("citr")
```


 - Balance and imbalance, the theories of location selection
 
@levinson2018metropolitan introduce how the networks within economies dictate the current lay of land use. The networks include public and non-public entities. The firms as the non-public entities, including developers and locators (non-retailers [Chapter.8] and retailers [Chapter.9]), always try to reduce transaction costs taking place within firms while market-saving transaction costs by the gains from specialization and economies of scale. Developers provide space for producing/consuming, exchanging, and connecting.

Suppliers, competitors, complementors, and customers are four basic factors of firms' location selection in metropolitan areas @levinson2018metropolitan [Chapter.8]. The four factors also form an economic network, which dominates a business's location related to the proximity of both labor and material, which is called the supply chain.
The supply chain is "a network of facilities and distribution options that procures materials, transforms the materials into intermediate and finished products, and distributes the finished products to customers."[@ganeshan2005introduction]

Most of the location-related theories based on the assumption of minimizing transportation cost and maximizing externalities. From Alfred Weber's Industrial Location Theory to @alonso1960theory's bid-rent curve in a monocentric city, @christaller1966central's central place theory, @zipf1949human's Law about the hierarchy of places, and @losch1967economics's theory about firms' location decisions and the spatial competition between them, explain how locators compete for the sites with higher accessibility.

As a model of New Economic Geography (NEG), agglomeration economies [@fujita2001spatial] provide another type of explanation. Some positive inter-firm externalities, information spillovers, local non-traded inputs, and a local skilled labor pool, explain clusters of employment such as edge cities, suburban activity centers, secondary business districts, and polynucleated city.

Accessibility works for both types of theory. Spatial proximity to the workforce, supplier, or consumer can reduce transaction costs. @levinson2018metropolitan list ten factors[^1] which affect the location decision and rate of development. In the authors' words, all relate to accessibility in some ways.

Economies of agglomeration are also the driving force to break the jobs-housing balance. Residences and firms are competing for the same land. Although job and workers are largely in balance at the metropolitan level, they are always imbalanced inside metropolitan. Even jobs-worker are balanced in number by some policy or design; the workforce may not be compatible with local jobs, which is called spatial mismatch.

 - Gentrification and displacement
 
Gentrification and displacement are the consequences of this imbalance. @zuk2015gentrification's literature review analyses the definitions of gentrification and replacement. The authors also examine the approaches to measuring gentrification and displacement. In the end, the authors emphasize the role of public investments in transportation infrastructure on neighborhood change.

In hedonic models, increasing housing price is a positive signal responding the infrastructure improvement. In another perspective, some scholars find higher housing price is a causal factor associated with the gentrification. The distinction in three types of displacement pressure can explain the phenomenon in some way. Disinvestment, Reinvestment, and enhanced market competition result in the involuntary displacement, which can occur even in the absence of gentrification. Previous studies cannot establish a relationship between gentrification and displacement. The authors suggest that future research should examine more aspects except for home price increases, and should explore the impact of public investment on commercial change, employment partners, affordability of goods and services, and change in clientele.

Since violence has plummeted dramatically since the 1990s, @sharkey2018uneasy argues that gentrification has brought unrecognized benefits to the poor in many cities. Sharkey also says that "the relative lack of income mobility at the neighborhood level across the USA challenges the narrative of rampant gentrification." @sampson2019neighborhood's study shows that, rather than public investment, neighborhood inequality is an important driver and mediator of urban transformation. The discussion should focus on neighborhood structure which is "a persistent feature of urban systems that exert causal effects on a wide variety of everyday life." The research of transportation and land use should not only observe where people live, but also observe where they travel throughout a city and to whom they are exposed by visits from others.


[^1]: The ten factors that affect the location and rate of development:
1. market velocity (the general level of activity in a specified market);
2. price of land;
3. availability of hard infrastructure (capabilities related to roads, water, sewers);
4. access choices (intersections, frequency of existing transit services, parking);
5. human infrastructure (education of workforce, nearby school quality, housing, daycare);
6. physical character (quality surrounding district, vitality, views and vistas);
7. environmental quality (healthy air and water);
8. predictability (no dramatic changes in zoning or character, appropriate capital improvement plan);
9. amenities (parks, restaurants);
10. available financing.



Notes {#notes}
==========

---
nocite: | 
  @litman2017evaluating
...


References {#references .unnumbered}
==========
