---
title: "Reading reflections"
subtitle: "USP 570"
author: 'Shen Qu'
date: "Week 6"
output:
  word_document: null
  pdf_document: default
bibliography: bib_usp570.bib
mainfont: Times New Roman
geometry: margin=1in
spacing: double
fontsize: 12pt
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
knitr::kable
options(width = 2000)
options(repos="https://cran.rstudio.com")

# install.packages("citr")
```


 - 'Diamond of Evaluation'
 
@levinson2018metropolitan [Chapter.10] introduced five criteria for evaluating transportation and land use planning, which are called the Diamond of Evaluation comprising the five "Es." Efficiency and equity are the classic perspectives of analysis. Environmental impacts are also a widely accepted perspective. The measures of experience involves some comprehensive factors. The last criterion, expediency, is more like a mechanism for decision-making and weighing the options. The five points of view reflect the complexity of urban transportation and land use system and then result in differing claims or proposed solutions. The author also mentioned another evaluation paradigm, which including four types of architecture (functional, physical, technical, and dynamic operational) and four attributes (robustness, adaptability, flexibility, and scalability).




 - Replacing LOS with VMT

Senate Bill 743 in California is a meaningful change in environmental impact assessment. It replaced the previous measure of auto congestion, level of service (LOS), with vehicle miles traveled (VMT). From the perspective of efficiency, policy-makers and public realized relying on LOS is not the solution but reinforces the traffic problems. Road supplement will never catch up the growth of demand, enforce the auto dependency, and "trap cities in an endless cycle of road-widening projects." The evaluation of efficiency also should focus on people's needs and activities, consider the regional effects, long-term goals of transportation and land use as a whole, not limit in road network itself. The VMT metric relies on fewer assumptions and is cheaper. Moreover, VMT can better reflect the outcomes in regional scale, can capture a variety of widely recognized negative social, environmental, and land-use impacts.

 - Discussion: Diamond or Onion?
 
Thinking of the relationship between the five 'Es', I find an onion structure may better describe the relationship among them. The five 'Es' don't play equal roles. Efficiency is the primary power of running, the core value of evaluation. Other outlayers such as equity, environment, and expediency are adjustment tools to make the assessment more complete. We know a single perspective of efficiency is imperfect. However, a single perspective of environment or expediency doesn't work. In the process of decision-making, efficiency is step one. We first need to prove the benefits and then consider the options for improving equity and other issues. If putting equity or environment on the central place and treating efficiency as an ancillary position, the whole system will slow down even break up. In the case of SB 743 in California, GHG emissions reduction, human health, and economic growth are the primary reason, which all belong to the generalized range of efficiency. Less VMT responses the modal equity but doesn't help other equity issues like "the last ones in are the ones who pay." 

It is necessary to clarify that using partial or short-term efficiency to evaluate a project is a misunderstanding. The case of SB 743 shows that we admit the one-sided traffic efficiency doesn't represent social efficiency and even hurt the overall and long-term efficiency. This is the primary reason for the change. Coming back to the five attributes of good measures of effectiveness, VMT is clear, calculable, and comparable. But it is more like an indicator that less is better. It can't tell us the whole gain and loss. The utility by economists is still the best measure for the transport–land use system. Some economic concepts and methods, such as the value of a statistical life (VSL) and the cost of climate change, try to integrate the different perspectives and provide a uniform metric as wide as possible. Expediency says that, currently, VMT is the best criteria among the available tools in determining the transportation impacts of projects at the local level.


References {#references .unnumbered}
==========
