---
title: "Reading reflections"
author: ""
date: 'Due April 11'
output:
  word_document: 
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: double
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
options(width = 2000)
options(repos="https://cran.rstudio.com")
```

### \textcolor[rgb]{0.7,0.7,0.7}{Week 2}



1. Levinson & Krizek - Chapters 1 & 2

 - Action

 - Access: The Fundamental Force
 
 
2. OECD, International Transport Forum, Linking People and Places, 2017 https://www.itf-oecd.org/linking-people-and-places



3. Susan Handy, "Enough with the “Ds” Already — Let’s Get Back to “A” Transfers Magazine, Spring 2018
https://transfersmagazine.org/enough-with-the-ds-already-lets-get-back-to-a/





4. One article from the list on the first tab of the shared Google sheet for this course:

https://docs.google.com/spreadsheets/d/1G83Ar37TttNj6MD6Hj13-2HMaXgjqvQwauKjrYWlqDU/

For the article, pay particular attention to the theories being use to guide the research. You will be expected to discuss your article in class, explaining the theory or theories used and how land use/built environment was measured and incorporated into the analysis. Refer to pages 4-5 in Levinson & Krizek for a brief overview of some of the relevant theories.

\pagebreak

2. 本报告探讨了不同的人和群体在城市中如何体验可访问性。它回顾了有关城市可访问性的最新研究成果，方法和数据来源，并讨论了更好的数据和计算能力如何增强可访问性分析和映射。调查结果为政策制定者提供了如何使公民更容易实现对他们而言至关重要的服务和机会，以及帮助建立更公平，可持续和经济上可行的城市的指导。 
本报告的工作是在国际运输论坛企业合作委员会（CPB）发起和资助的项目范围内进行的。CPB项目旨在从业务角度丰富政策讨论。在ITF的带领下，工作由CPB成员公司，外部专家和ITF研究人员组成的工作组以协作方式进行。

3. 当Robert Cervero和Kara Kockelman在1997年发表他们被高度引用的文章“旅行需求和3D：密度，多样性和设计”时，他们似乎永远地改变了交通规划的话语。使用恰好以字母D开头的三种措施来表征建筑环境的想法很吸引人，并且抓住了它。

到2010年，3D已经增长到7，增加了“目的地可访问性”（我称之为区域可访问性），“距离传输”，“需求管理”和“人口统计”（一类控制变量，而不是建筑环境的特征）。从那时起，我听说有一两个D或两个传闻。

Ds现在在学术文献中占据了建筑环境对旅行行为的影响。我认为这不是一件好事。

该术语至少令人困惑。“多样性”是指特定区域内土地利用的混合，但人们可能很容易将其误认为是该地区居民的社会人口组合，而不是“人口统计数据”。“设计”通常被视为连通性街道网络，而不是这个词通常所暗示的街道环境的审美品质。Ds是一个引人注目的速记，但不是特别清楚。

另一个问题是研究人员将D特征视为独立的，而实际上它们是相互依赖的。研究人员通常会仔细测试“多重共线性”，即变量高度相互关联的情况，因此难以估计其中任何一个变量对另一个变量的影响。大多数研究表明D特征并不像人们想象的那样相关。例如，有可能在街道连通性较低的地区拥有良好的土地利用组合。

但是，D特征的某些值经常在一起，反映了特定邻域形成的时代。例如，二战前的社区更有可能同时拥有网格街道网络（“设计”）和步行距离内的社区规模购物（“多样性”）。

Ds也倾向于一起，因为它们相互影响。密度尤其对其他D特征具有强烈影响：更高的密度支持更好的运输服务（“距离运输”）以及更接近零售和服务（“多样性”）。更大的土地利用“多样性”，加上更好的街道连通性（“设计”），可以缩短到目的地的距离，从而提高“目的地可达性”。

将Ds视为彼此独立处理会产生过高估计其影响力的风险。它还会造成低估其影响力的风险。如果两个或多个特征一起具有协同效应，则它们产生的总效应大于每个独立效应的总和。

研究人员很少讨论这些关系，更不用说在他们的分析中对它们进行说明了。特别令人不安的是使用密度作为旅行行为的预测因子，而没有解释  密度如何 影响行为。密度影响其他D特征，更直接地决定旅行者可用的选择，从而更直接地塑造他们的旅行选择。研究人员通常引用其他研究人员对相同措施的依赖来证明他们对密度和其他Ds的依赖。即使是基于行为理论而非公认实践来证明Ds合理性的最小尝试也是一种改进。

如果我们完全改变了框架怎么办？

让我们从旅行者的角度出发，以及她如何看待自己的旅行选择。旅行行为研究人员通常认为，个人可以选择日常旅行，最大限度地发挥其效用，提供最大的成本效益，或者更简单地说，使个人最有意义。

建筑环境在确定个人可用选择方面发挥着作用。最根本的是，建筑环境特征，如密度，土地使用组合和街道连通性决定了个人离目的地的距离，克服这个距离的成本会影响她可以去哪里，通过什么模式，以及如何经常。如果目标是了解旅行者做出的选择，那么有什么更好的方式来表征建筑环境而不是它提供的选择？

可访问性的概念提供了完美的方法。如通常所定义的，来自给定地点的可访问性水平反映了其周围的目的地的分布，各种模式可以容易地达到这些目的地，以及在那里发现的活动的数量和特征。它告诉我们建筑环境为旅行者提供的选择。

研究表明，可达性和旅行行为之间存在密切联系。在一项研究中，我们发现到最近的商店的距离是在那里散步的强烈预测。另一方面，在半英里范围内拥有更多商店与更频繁地步行到商店有关。在第三项研究中，我们发现进入一个步行距离内有商店的街区和良好的交通导致车辆行驶里程减少。这些结果在行为上都是完美的。

从研究的角度来看，可访问性不仅是一个更好的衡量标准。从实践的角度来看，这也是一个更好的衡量标准。对人们来说最重要的是他们到达他们需要的地方是多么容易，以及访问他们需要或想要的服务是多么容易。

城市本身不会提高密度 - 它们会提高密度以增加可达性。使用可访问性作为衡量当前条件和拟议政策的绩效衡量标准，可能会使公众辩论摆脱密度的可怕想法，而密度往往引发敌对的反应。

为了实现良好的可达性目标，德国人有一个简单的（虽然难以发音）短语：  ein stadt de kuerzen wegen，一个短距离的城市。这是一个几乎每个人都可以达成共识的目标，它为一系列可以减少自身依赖和提高生活质量的策略打开了大门。

可访问性可能不如Ds那么吸引人，但它对于研究人员，从业者和公众来说更有意义。现在是时候完成Ds并回到A.

4. 本文提出的研究研究了行人和骑自行车者环境，旅行行为以及社会网络的特定子集之间的相互关系，其特征在于他们是常旅行或活动伴侣。为此目的，404名个人参加了基于网络的调查，并提供了与行人和骑自行车者特定环境（人行道，自行车道和人行横道）特定要素的感知有关的数据，社会人口统计数据以及他们通常活动的特征和旅行伙伴。与会者还完成了为期两天的活动旅行日记。通过探索性和验证性因子分析（EFA和CFA）评估测量的有效性和构建体的可靠性，并使用结构方程模型（SEM）确定五个模型以鉴定研究变量之间的关系。结果强调了旅行行为如何影响与行人和骑车者特定环境相关的元素感知形成的重要性。
关键词：
 旅行行为; 观念; 行人和骑车人的环境; 社交网络; SEM
1.简介
在城市地区推广使用可持续旅行模式正成为当前交通政策中的一个关键问题。减少汽车使用和增加步行和骑自行车有助于减少污染，改善人们的健康，并为绿色区域和人行道更好地利用城市空间。
设计和实施鼓励在城市地区使用可持续旅行模式的有效行动和措施需要确定影响步行和骑车决策的因素。心理社会因素在解释旅行行为决策中很重要[ 1 ]。在这些因素中，在可持续旅行行为研究的背景下，几乎没有研究与步行和骑自行车相关的建筑环境的特定元素的感知。
个人的旅行行为决定受到与他们互动的人的影响[ 2 ]。在这种情况下，活动旅行同伴的特征尤为重要。
在以下部分中，提出了心理学理论和文献综述，它们支持了本研究的研究重点和概念框架的定义。
2。文献综述
2.1。心理背景
感知是生物体解释和组织感觉以产生有意义的世界体验的过程[ 3 ]。人类感知刺激的方式是有选择性的，并且会受到一个人现有的信念，态度，观念，动机和个性的影响[ 4 ]。由于人类处理信息的能力有限，因此存在感知防御，这些防御会产生内部障碍，阻止刺激与人的当前态度和信念不一致而传递感知过程。这个过程叫做选择性感知[ 5 ]。任何行动都需要选择一些刺激而不是其他与行动相关的环境，因此这种选择是目标导向的[ 6]。
研究了对便于步行和骑自行车的城市建筑环境的特定元素的认识：人行道，自行车道和行人过路处。它们一起被称为对行人和骑车者特定环境（PPCE）的看法。
通过对社交网络的分析，目前正在考虑社交互动。Axhausen [ 2 ]将社交网络定义为成对链接的一组人，这样每个人都可以通过积极的联系到达任何其他人。有人认为，在旅行者的社交网络中，成员的地理位置以及相关活动地点的地理位置决定了旅行的数量和方式。
一些心理学理论支持PPCE，社交网络和旅行行为之间的潜在关系。下面介绍这些理论的简要说明。
布朗芬布伦纳的生态系统理论[ 7，8 ]假设，有些情况下个体的行为是由社会环境（如社会规范，价值观，态度等）大多是确定的组织和人际交往文化，社会之间的相互关系。因此，一个人的行动和决策能力（例如，决定前往活动将要去哪里），与其他人（亲戚，朋友和同事）的关系以及物理环境之间会有相互作用。 （例如，人行道或自行车道的可达性）。这三个因素导致意图以具体方式行事，并影响实际行为。
社会认知理论[ 9 ]强调通过认知或个体因素，行为能力（做什么以及如何做）和环境因素的互惠因果关系，考虑观察学习（“建模”行为），增援（积极或消极，和内部或外部），期望（一个人行为的预期后果）和自我效能的概念，这是指对成功执行行为的能力的自信。
阿杰恩的（TPB）计划行为理论[ 10，11 ]的理论是一个给定的行为将通过一个人对行为态度来决定，主观规范（包括显著别人的期望），并在该特定行为知觉行为控制。在这个理论中，态度指的是对给定行为的正面或负面评价。主观规范包括一个人对重要他人关于是否应该执行该行为的想法的看法。感知到的行为控制指的是具有执行某种行为所必需的技能或能力的信念。TPB已被用于许多不同的场景，试图预测行人的行为; 例如，Barton等人。[ 12]研究了成年人在分散注意力的情况下穿越街道的意图，发现感知到的行为控制成为最重要的预测因素。
以前的理论提出，有许多因素（个人，社会和环境）导致了行为的意图。但是，意图不一定会导致所有场合的行为。以同样的方式，有时候，在人们当前的行为之前没有任何意图。这些情况已经被认知不协调理论研究[ 13]]。当一个人相信思想，执行行动或消费与他或她的态度，信仰或行为相冲突的新信息时，就会发生认知失调。人类有避免矛盾的愿望，因此当个体经历不一致时，心理上是不舒服的。因此，有必要实施减少这种不一致的行动。因此，减少了相互冲突的思想，态度，信仰或行为以恢复平衡。通过改变他们的想法，个人接受他或她的原始观念是错误的，这些新的想法加强了新的情况。此外，可以改变或减少价值观和自我形象的重要性，并且可以忽略或否定与先前信念冲突的新信息。整套感知，包括那些关于他们自己，环境，环境和经验的现状的人，可以相互协商并变得一致。例如，增加汽车使用的人可能会对行人和骑车者特定的环境采取越来越多的负面看法，以加强他们自己的汽车使用。
最后，虽然不是心理学理论，但值得一提的是Hagerstrand [ 14 ] 提出的时空棱镜概念，他将棱镜体积作为可达性的指示，其概述体现了能力，耦合和权威约束。个人活动和旅行模式。时空可达性模型认识到联合活动可能会限制空间和时间活动的表现。
2.2。之前的学习
与其他心理社会因素相反，很少研究与各种交通方式和旅行行为相关的特定建筑环境的感知之间的相互关系。Dill和Voros [ 15 ]发现，靠近自行车道和骑自行车的客观测量之间的关联并不显着，而自行车道的感知可用性与骑自行车有正相关关系。Hull和O'Holleran [ 16 ]比较了六个欧洲城市中与自行车基础设施的舒适性，速度和安全性有关的不同用户感知。他们发现，一个城市设计良好的自行车基础设施将鼓励更多人使用自行车。Ma等人。[ 17]研究了客观测量和感知建筑环境之间的关系，以及它们与骑自行车行为的关系。他们发现，对波特兰（俄勒冈州）自行车路线的轻松，安全和方便的看法对骑自行车的行为产生了直接和显着的影响。使用刺激 - 生物 - 反应框架，Ma和Cao [ 18 ]发现，客观建造环境通过影响感知来影响旅行行为，同时考虑交通系统的属性。
人们越来越关注社交网络的研究及其对家庭[ 19 ]和外部家庭[ 20 ]的个人旅行行为，旅行决策和联合调度的影响。例如，Neutens等。[ 21 ]侧重于参与联合活动，并建议时间和同步效应显着影响从联合活动机会中获得的利益。Silvis等人。[ 22]发现目的地的非直系亲属数量影响了受访者的旅行时间。此外，他们发现，受访者的总出行次数和受访者访问的不同地点的数量与他或她的社交网络的大小以及重复联系的数量密切相关。范登伯格等人。[ 23 ]发现社交网络规模直接或间接地通过不同模式和社交旅行距离积极地影响社交旅行的数量，表明社交网络产生社交活动和旅行。Sadri等人。[ 24]断言个人网络测量，例如网络密度，同质性，异质性和自我改变关系属性对个体参与的每周共享旅行的数量产生显着影响。
3.研究重点和概念框架
我们研究了PPCE，周末旅行行为和同伴特征之间的相互关系。
与大多数现有的旅行行为文献不同，这些文献集中于建筑环境的一般特征，我们研究了与人行道，自行车道和人行横道相关的特定行人和骑车人特定环境的感知。此外，我们只考虑社交网络的一个子集，其中仅包括那些经常与自我共享活动和旅行的人。我们假设这些活动旅行同伴对这个人的旅行行为有相当大的影响。我们明确考虑了旅行行为和PPCE之间双向影响。
虽然在工作日和周末分析同伴的存在以处理与旅行相关的城市问题很重要，但在本研究中，考虑周末旅行行为。周末，当伴侣的存在是常见的时候，社交和娱乐活动更频繁。因此，更有可能在周末找到伴侣特征的关联。
基于前面和之前研究的心理学理论，我们构建了图1所示的概念框架。我们假设PPCE和旅行行为相互影响。我们还假设活动旅行伙伴的特征，建筑环境的客观测量和社会人口统计特征直接影响旅行行为以及行人和骑车者特定环境的感知。此外，我们假设旅行行为在行人和骑车者特定环境的感知与其他解释变量之间具有中介作用。
 
图1. 概念模型。
4.材料和方法
4.1。调查描述和数据收集
用于该研究的数据集是2016年至2019年由西班牙经济部资助的MINERVA项目（“运输规划的创新旅行数据收集方法”）的一部分。该项目特别开发了一项基于网络的调查。收集有关个人价值观，活动旅行相关行为，态度，观念和同伴特征的信息[ 25 ]。
基于网络的调查是在线分发的。与公立和私立大学，公司，当地政府和活动组织者签署了几项协议，所有这些协议都与分发合作。
数据收集于2017年5月至10月期间（8月除外）进行，以避免在暑假期间执行非经常性流动和长途旅行。该研究的主要领域是瓦伦西亚（西班牙）及其大都市区，但其他住宅区的参与者也被接受。
为了参与研究，受访者被要求创建一个帐户并登录该平台。调查时间约为50分钟，可在10天的截止日期内的不同时间完成。正确完成调查的参与者将获得奖励彩票（四个电子平板电脑）。那些提供其社交网络成员联系方式的人获得了额外的门票。
基于网络的调查是根据用户体验，灵活性和响应性进行设计的，因此受访者可以通过互联网连接从任何设备轻松访问和完成调查。此外，异步验证提供了实时反馈，并准备了一组电子邮件，以根据用户的进度设置提醒。
基于网络的调查由五部分组成。首先，简要问卷要求提供有关受访者居住地区的人口统计和社会经济特征以及交通可达性和建筑环境属性的信息。
其次，提供了为期两天的活动旅行日记，以收集在一周的一天和周末的一天中进行的所有活动和旅行。需要每个活动 - 旅行剧集的以下属性：旅行的起点和终点，活动地点，时间和持续时间，旅行模式或活动类型，大多数字段是预定义和可选择的。此外，还显示了一个文本框输入，并要求参与者提供他们在每集中执行的同伴的姓名。
第三部分收集了有关同伴特征的信息。为此目的，显示已经定义的同伴列表，并且需要关于每个人的简要问卷，包括以下信息：性别，年龄，关系类型，社会接近度，自我居住地和改变之间的距离，频率面对面的会议，沟通的频率和同伴在受访者的流动性中的影响程度。
第四部分使用Schwartz价值调查（SVS）收集有关个人价值的信息，该调查基于Schwartz人类价值理论[ 26 ]。第五部分包括关于态度和观念的调查。态度部分使用李克特量表来评估当前的旅行模式，使用旅行模式的意图，创新的旅行解决方案，语义差异，对环境的看法，ICT的使用和个人移动性。
特别是，考虑到宽度，长度和连续性，维护，障碍物，城市家具，位置和交通灯调度等因素，评估了对行人和骑车者特定环境的看法。为此目的，包括19项：对人行道的看法（5项）; 对自行车道的看法（7项）; 和行人过路处的感知（7项）。
4.2。分析和测量
本节包括变量和测量的定义。
变量和测量
•	人口统计学和社会经济特征
在个人和家庭层面都考虑了基本的人口和社会经济特征（表1）。
表1. 变量的定义。
•	同伴
在这项研究中，社交网络由旅行和活动的同伴定义的子集组成，从两天的活动旅行日记中获得。通过要求受访者包括他们通常与之共享活动和旅行的社交网络的其他成员来扩大此列表。该子集的定义前提是它影响了他们的旅行行为以及他们的感知。
如表1所示，根据每个受访者的同伴数据建立了若干指标。因此，为每个参与者定义了同伴的主要特征。
•	建立环境特色
从调查响应中获得关于建筑环境特征和可访问性属性的信息，例如：到下一个火车站和公共汽车站的距离（以分钟为单位）以及居住区域中自行车道的可用性。此外，根据受访者提供的地址创建了两个指标：
（一个）
运输可持续性程度。该指标的范围为1到6，它是3个相等加权因子的总和：
公共交通可用性（如果电车，地铁或火车站距离步行距离不到10分钟，则= 2;如果这些站点中的任何一个位于10到20分钟步行距离之间，则= 1.5;如果没有铁路，则为1.0）交通可用，但至少有一个巴士站在10分钟步行距离内）。
自行车基础设施的可用性（= 2，自行车道安全，方便，并且沿整个区域连续; = 1.5如果自行车道在主要道路上或沿着主要道路，或者这些车道几乎不存在，但是低交通流量允许安全骑车;如果城市设计对自行车不方便或安全，则= 1。
行人条件（如果步行区域较宽且连通或城市设计主要集中在行人上，则为= 2;如果步行区域连接较少或城市设计目的混合，则= 1.5;如果城市结构是以车辆为导向且行人设施较差，则为1 ）。
在自行车和行人导向区域中应用了0.5点的校正因子，这些区域缺乏足够的设施以使其有用。
（b）中
中心度。此变量表示个人住所离市中心的距离。它的范围从1到5（如果它位于隔离或连接不良的区域，则= 1;如果它位于离市中心15公里以内的大都市区域，则= 2;如果位于大都市区域，则为3;距市中心1公里;如果在市中心，则= 4;如果在市中心，则= 5;）
•	对行人和自行车特定环境的看法
包括19项以衡量对人行道（5项），自行车道（7项）和行人过路处（7项）的态度。为此，考虑了几个属性：宽度，长度和连续性，维护，障碍物，城市家具，位置和交通灯调度（见第5节）。基于这些数据，创建了三个潜在构造，如第5节所述。
5.结果
本节包括样本特征，社会人口统计学和旅行特征。接下来，介绍描述性分析以及结构的尺度和可靠性的验证。最后，描述了结构方程模型（SEM）的发展。SPSS软件用于描述性分析，而MPlus被选择用于验证性因子分析和模型估计。
5.1。样品特征
超过3000人提供了参与和在网络调查中注册的最低信息。在数据清理和验证之后，1683名个人至少完成了基于网络的调查的态度和看法，1382还填写了价值问卷。对于这项研究，使用了该数据集的子样本，其中包括404名参与者，他们也正确完成了为期两天的活动旅行，并提供了有关其同伴的信息。
根据性别分析样本是合理平衡的（表2）。然而，正如预期的那样，50岁以上的人在样本中的代表性不足。参与者主要是学生，尽管在就业人员中也占很大比例。
表2. 样本分布。
每人每天的平均活动和旅行次数分别为11.4和3.9。对于主动运输，步行占主导地位（45.2％），而骑行比例则低得多（6.8％）。在机动旅行模式中，私人车辆的使用是最主要的（35.6％），公共交通占旅行的11.7％。总体而言，44.2％的旅行是在工作日进行的，55.8％是在周末进行的。总共有54.3％的旅行是与同伴一起进行的（表3）。
表3. 模态拆分和随附数。
宣布的同伴平均数为每位受访者10.18人。但是，只考虑那些填写了调查问卷的修改者，将这一比例降低到9.12个同伴。其中百分之七十六被列入日记，其余的后来加入，与任何活动旅行事件无关。31％的同伴是家庭成员，37.4％是朋友，6.4％是伴侣，剩下的人是熟人或同事。最后，80.2％的受访者认为至少有50％的同伴是相互关联的。
5.2。描述性，探索性和验证性因子分析
进行了描述性分析，获得了与感知有关的信息的基本统计和正态性，对称性和峰度的度量。一些项目呈现出不对称和非正常的迹象，这使我们选择了更强大的模型来将这种偏差考虑在内以进行模型估计。
Cronbach的alpha用于衡量内部一致性，这表明一组项目与一组有多密切相关。在第一次分析之后，观察到与照明条件有关的三个项目显示与构建体的低相关性因此被删除（每个潜在构建体一个缺失）。获得的三个潜在构造的Cronbach's alpha测量值（人行道= 0.837;自行车道= 0.920;行人过路点= 0.885）落在可接受值的范围内。因此，可以假设规模可靠性。
Kaiser-Meyer-Olkin抽样充分性测量（KMO）用于确定可能由潜在因素引起的变量的方差比例。获得高值（> 0.9），这表明因子分析技术可能是合适的。巴特利特对球形度的检验评估了相关矩阵是一个单位矩阵的假设，这表明变量是不相关的，因此不适合结构检测。获得空值，这也支持使用因子分析。
Pearson的相关矩阵显示了三个潜在变量（人行道，自行车道和人行横道的感知）之间的高度相关性。这可能是因为一些项目与每个潜在构造的相同属性（例如，宽度或维护）相关。因此，这些相关性后来包含在模型的表述中。
之后，进行了探索性和验证性因子分析。因子分析不仅提供获得对数据的清晰视图的可能性，而且还使用在随后的分析[输出的可能性27，28 ]。
探索性因子分析（EFA）用于探索一组观察到的变量的潜在因素结构，而不对结果强加先入为主的结构[ 29 ]。通过执行全民教育，确定了潜在的因素结构。为了评估量表并评估制定的概念框架，基于代表包含16个项目的PPCE的理论构造进行了探索性因子分析（EFA）。使用Varimax旋转和因子载荷0.40作为维持项目因子的阈值的EFA结果如表4所示。
表4. 探索性和验证性因子分析。对人行道，自行车道和人行横道的分类看法。
在EFA程序之后，进行验证性因子分析（CFA），其指定观察指标与潜在变量的假定关系。CFA用于验证一组观察变量的因子结构，并检验观察到的变量与其潜在潜在构造之间存在关系的假设。
得到以下拟合度指数：Chi square / df = 1.57; 比较拟合指数（CFI）= 0.984; Tucker-Lewis指数（TLI）= 0.977; 标准化均方根残差（SRMR）= 0.038; 和均方根近似误差（RMSEA）= 0.038。这些统计数据支持构建量表的有效性。所有系数均超过0.6，表明所有语句都与定义的潜在变量密切相关（图2）。
 
图2. 验证性因子分析。
5.3。模型估计和结果
结构方程模型（SEM）是一个非常强大的工具，它在行驶行为的研究[越来越多地使用30，31，32，33，34，35 ]。在SEM中，理论构造之间的关系由因子之间的回归或路径系数表示[ 36 ]。通过绘制路径图来分析SEM，所述路径图由用于观察变量的框和用于潜在因子的圆组成，通过箭头连接。单头箭头或“路径”用于定义模型中的因果关系，箭头尾部的变量导致该点处的变量。双头箭头表示协方差或相关性，没有因果解释[36 ]。
完整的SEM由三组方程组成：结构方程，内生变量的测量方程，以及外部变量的测量方程。结构方程用于捕捉因果关系，外生变量对内生变量的加权影响。如果使用测量模型，则将一组潜在（未观察到的）变量测量为其他观察到的外部或内源变量的线性函数。在具有潜在变量的完全指定的模型中，包括所有这三组方程。然而，SEM的大多数应用仅包括一个或两个。在这项研究中，旅行行为与行人和骑车者环境感知之间的随意关系在两个方向上进行了测试。为了处理这种互惠关系，需要两个结构方程和一个测量方程。因此，最初使用以下等式定义模型：
结构方程式：
PPCE = B PPCE + C + TRAVELΓ 1 X 1 +Γ 2 X 2 +ς（1）
TRAVEL = d PPCE + E + TRAVELΠ 1 X 1 +Π 2 X 3 +μ（2）
测量方程：
Y =ΛPPCE+ε（3）
PPCE：代表行人和骑车者特定环境感知的潜在变量; 旅行：周末使用每辆私家车/公共交通/主动交通工具; X 1：影响PPCE和TRAVEL的外生变量的向量; X 2：仅影响PPCE的外生变量的向量; X 3：只影响TRAVEL的外生变量向量; B：从其他PPCE预测PPCE的权重系数向量; C：从TRAVEL中预测PPCE的权重系数向量; D：预测来自PPCE的TRAVEL的权重系数向量; E：从其他TRAVEL中预测TRAVEL的权重系数向量; Γ：权重系数向量，用于从外部变量预测PPCE; Π：权重系数向量，用于预测来自外部变量的TRAVEL; ς：残差的向量，表示影响PPCE的未观察到的因变量以及误差和随机扰动; μ：表示影响TRAVEL和误差以及随机扰动的未观察到的因变量的残差向量; Y：内源变量的向量（表4中的变量A111至A128）测量潜在变量PPCE）; Λ：反映Y和PPCE之间因果关系的系数矩阵; 和ε：反映Y中测量误差的矢量。
结构方程涉及两个内生变量（PPCE和TRAVEL），外生变量（X），残差向量（ζ和μ），以及要估计的几个系数向量。测量方程包括测量潜在变量PPCE的内生变量（Y），反映测量误差的矢量ε和要估计的系数矩阵（Λ）。关于结构方程，要识别的方程需要至少一个排除的外生变量（X）。也就是说，它必须具有对内生变量TRAVEL没有影响的X2变量和对内生变量PPCE没有影响的X3变量。这些X2和X3变量被称为因果系统的工具变量，很难找到。在我们的例子中，找不到这些变量是不可能的。因此，两个单独的非互易模型适合模拟PPCE和TRAVEL之间的每个关系。其余变量的系数估计值和两个模型的全局拟合指数之间的差异是最小的，因此结果在下面的同一图中表示。
在本研究中，使用Huber-White协方差调整（MLR）的最大似然值用于参数估计[ 37 ]。该估算器使用White的基于夹心的方法来产生在非正态性（来自下方的删失数据）和非独立性（由单个受访者提供的多个数据）时存在的稳健的测试统计数据[ 38 ]。虽然当输入数据是非正态时，这种稳健的估计器产生了优异的结果（与标准最大似然相比），但绝对模型拟合的卡方检验仍然可以对模型结构中的琐碎错误指定敏感。此外，我们还评估了以下模型拟合的描述性度量：标准化均值残留量（SRMR）[ 39 ]，比较拟合指数（CFI）[ 40]]和均方根逼近（RMSEA）[ 41 ]使用推荐的CFI和相关增量拟合指数的截断值90，RMSEA为08，SRMR为10 [ 42 ]。
基于概念框架和全民教育和终审法院的结果，估计了五个完整的SEM模型用于周末旅行行为。型号1a和1b包括在周末使用PV（％PV TRIPS WEEK-END）。模型2包括在周末使用PT（％PT TRIPS WEEK-END）。模型3a和3b包括在周末使用AT（％AT TRIPS WEEK-END）。表示人行道，自行车道和人行横道的感知的三个潜在变量也包含在模型中。然而，间接影响仅在使用行人和骑车者特定环境（PPCE）的聚合感知时才显着（模型1a和3a）。结果将在下一小节中介绍。
5.3.1。型号1a和1b：周末使用私人车辆（PV）
图3包括模型1a结果，显示其他变量与PPCE之间的直接影响。
 
图3. 模型1a。直接影响。
正如预期的那样，行人和骑车者特定环境的感知与周末使用PV呈负相关（图3），表明两个变量之间存在反比关系。该关联呈现低统计学显着性。更有趣的是，周末使用PV与行人和骑车者特定环境的感知之间存在强烈的统计显着和负相关，这再次表明存在反比关系。
邻里自行车道的存在与行人和骑车者特定环境的感知有着正相关关系。一些社会经济特征也与行人和骑车者特定环境的感知有关。性别和年龄与感知有显着的负相关，而交通传递的所有权与感知有正相关关系。
在自行车主要用于运动的情况下，与行人和骑车者特定环境的感知存在负面关联。没有重要的统计证据表明同伴的特征直接影响了受访者对行人和骑车者特定环境的看法。
相反，运输可持续性的程度和居住区的中心性与周末使用PV成反比。从逻辑上讲，当自行车主要用于运输时，周末使用PV会产生负面关联。相比之下，汽车可用性与周末使用PV正相关。
伴侣的某些特征与周末使用PV显着相关。同伴中非家庭成员的比例与周末使用PV呈负相关。改变住宅和自我住宅之间的距离与周末使用PV正相关。
图4包括模型1a结果，显示其他变量与PPCE之间的间接影响。所有确定的效果都是由周末使用私人车辆调节的。
 
图4. 模型1a。间接影响。
与PPCE呈正相关的变量是：受访者家庭地点的中心地位，主要用于交通的自行车，以及同伴中非家庭成员的比例。与PPCE负相关的变量是汽车所有权以及同伴和受访者住所之间的距离。
图5显示了模型1b的结果，显示了所有其他变量与三种分解感知（人行道，自行车道和行人过路处）之间的直接影响。
 
图5. 模型1b。直接影响。
对人行道，自行车道和人行横道的看法与周末使用PV无关。相比之下，周末使用PV与三种分解观念之间存在负面的统计显着关联。
与行人和骑车人特定环境（模型1a）的总体感知相关的所有变量也被发现与人行道，自行车道和人行横道（模型1b）的感知显着相关，除了拥有运输通行证。
5.3.2。模型2：周末使用公共交通（PT）
图6报告模型2，其包括周末使用PT的直接效应结果。由于间接影响不显着，因此可将这些结果视为总效应。在这种情况下，周末使用PT与行人和骑车者特定环境的总体感知之间没有发现显着影响。因此，图4仅包括对人行道，自行车道和行人过路处的分解感知。然而，周末使用PT确实仅对人行道的感知产生积极影响。
 
图6. 模型2.总效应。
与之前车型的结果类似，自行车道的存在与人行道，自行车道和人行横道的感知正相关。
模型2还表明年龄对人行道，自行车道和人行横道的感知有负面影响。使用自行车进行运动会对人行道的感知产生负面影响。性别和汽车可用性与周末使用PT有负相关。
5.3.3。型号3a和3b：在周末使用主动运输（AT）
图7报告了周末AT使用的模型3a直接效应结果，其中包括行人和骑车者特定环境的总体感知。行人和骑车者特定环境的感知与周末使用AT（p > 0.1）无关。相反，周末使用AT与行人和骑车者特定环境的感知之间存在积极的统计学显着关联。
 
图7. 模型3a。直接影响。
自行车道的可用性与行人和骑车者特定环境的感知正相关。年龄，性别以及在较小程度上使用主要用于运动的自行车也与该感知负相关。同伴的特征不会直接影响行人和骑车者特定环境的感知。
住宅区，性别和自行车的运输可持续性主要用于运输，与周末使用AT正相关。汽车可用性与周末使用AT负相关。
同伴的某些特征也与周末使用AT显着相关。与使用PV（模型1a）相反，同伴中非家庭成员的比例与周末使用AT呈正相关。同伴和受访者住所之间的距离与周末使用AT呈负相关。在这种情况下，与同伴面对面接触的频率与周末期间AT的使用负相关。
图8包括模型3a结果，显示其他变量与PPCE之间的间接影响。所有确定的效果都是由周末使用AT介导的。
 
图8. 模型3a。间接影响。
唯一具有正相关关系的变量是使用自行车主要用于运输。具有负关联的变量是汽车所有权以及同伴和受访者住所之间的距离。
图9显示了模型3b的结果，显示了所有其他变量和三种分解的感知（人行道，自行车道和人行横道）之间的直接影响。与公共交通模型（模型2）类似，间接影响并不显着。因此，这些结果可视为总效应。
 
图9. 模型3b。总效果。
对人行道，自行车道和人行横道的看法与周末使用AT无关。然而，在周末使用AT与自行车道和人行横道的看法之间存在统计上显着和积极的关联。令人惊讶的是，AT的使用与人行道的感知之间没有显着关联。
在模型3a中发现的包括聚合PPCE的所有关联也在模型3b中找到，其中考虑了三种分解的感知。根据重要程度的差异出现在年龄和人行道的感知之间。
6.讨论
第5节中描述的模型的结果表明，并非所有概念框架中的假设关系都得到确认。建筑环境特征和社会人口统计学以及旅行特征都与PPCE和旅行行为相关联。然而，同伴的特征只会直接影响周末使用PV和AT。然而，我们发现间接影响将同伴的特征与旅行行为所介导的感知联系起来。
6.1。旅行行为和PPCE以及分解的观念
PPCE和周末使用PV，PT和AT在概念模型中相互影响。然而，在周末期间，只发现了PPCE与PV的使用之间的弱关联。马和曹[18]也发现在公民/宗教和商店旅行的背景下，观念和旅行行为之间存在显着的联系。这也符合生态系统理论。
相反，周末使用PV和AT对PPCE的影响以及人行道，自行车道和人行横道的分解感觉是显着的。这些结果与Kroesen等人一致。[ 43 ]，他们发现旅行行为对态度的影响比反之亦然。同样，De Vos等人。[44]发现步行和骑车旅行的评估积极影响受访者对各自模式的态度，这反过来对选择该模式产生积极影响。根据Goldstein的说法[45]，影响人类感知的变量之一是与感知对象相关的经验。换句话说，使用的PV越多，对其积极特征的认识就越强。因此，对PV有更好的认识。此外，这些结果可以通过认知不协调理论[13] 来解释。个人可以根据他们当前的行为调整他们的感知，以减少可能的不和谐并保持他们的心理一致性。
在这项研究中，周末使用PV与PPCE以及人行道，自行车道和人行横道的分类感知呈负相关。相比之下，周末使用AT与这些看法正相关。有趣的是，周末使用PT只影响人行道的正面感知。往返PT站和站点的出入口位移主要使用人行道进行，这可以帮助公共交通用户形成对这部分行人环境的积极看法。

6.2. 社交网络和感知

尽管同伴的特征与PPCE之间没有直接的影响关联，但我们通过旅行行为发现了间接影响。通过周末使用PV，非家庭成员在同伴中的比例与PPCE正相关。与非家庭伴侣的活动旅行行为不那么常规，访问更多的非习惯性地点，这可能有助于更多地了解行人和骑车者特定的环境。通过周末使用PV和AT，参与者和他们同伴的住所之间的距离与PPCE负相关。长位移增加了遇到不良行人或骑车人特定环境的可能性。

6.3. 建筑环境，社会人口统计学，旅行特征和感知

正如所料，自行车道的存在与PPCE和分解的观念正相关。考虑到建筑环境的其他元素并未提供与任何特定观念的重要关系，我们可以得出结论，自行车基础设施对全球对行人和骑车人相关的建筑环境的看法比该地区的其他属性具有更广泛的影响。 。
女性和老年人与PPCE和分解的观念有更多负面联系。可以解释这一结果，因为女性和老年人对人行道和自行车道上的障碍物的存在更敏感。
使用自行车进行运动的受访者与PPCE有负面联系，特别是自行车道和较低程度的人行道。这可以通过特定于自行车的环境的设计来解释，由于它们的不同要求，这些环境对于体育活动可能不方便。

6.4. 社交网络和旅行行为

活动旅行伴侣的几个特征与旅行行为有关。同伴中非家庭成员的比例与周末使用PV呈负相关，与周末使用AT呈正相关。如前所述，与家人一起进行的活动旅行更为常规，包括维修行程，这些行程往往通过汽车比骑自行车或步行更多。
正如预期的那样，参与者和他们同伴的住所之间的距离与周末使用PV呈负相关，并且与周末使用AT呈正相关。这一发现证实，距离是行走和骑车的威慑[ 46 ]。
与同伴面对面会面的频率与周末使用AT呈负相关。骑自行车和特别是步行用于执行通常单人旅行的短位移，其被执行以主要完成不需要陪伴的维护活动。

6.5. 建筑环境，社会人口统计学，旅行特征和旅行行为

正如预期的那样，受访者居住区的交通可持续性和中心性与周末使用PV呈负相关，并且与AT的使用呈正相关。提供高质量的公共交通和行人路线对于促进可持续的旅行行为至关重要。
女性与周末使用PT呈负相关，与周末使用AT呈正相关。在考虑平日通勤旅行时，女性通常通过PT旅行的次数多于男性。相反，在周末，PT的使用在很大程度上减少，特别是在女性中。关于AT的使用，女性通常在一周中的任何一天比男性走路更多。这不适用于自行车使用。然而，步行的次数远远多于自行车旅行。
从逻辑上讲，汽车可用性与周末使用PV呈正相关，与周末使用AT负相关。使用自行车运输与周末使用PV负相关，并与周末使用AT呈正相关。这一结果表明PV和自行车是替代旅行模式。

7.结论

本文介绍了对行人和骑车者特定环境，旅行行为以及社交网络的特定子集的感知之间的相互关系的研究，其特征在于他们是通常的旅行或活动伴侣。为此，使用结构方程模型分析了基于网络的调查收集的数据。
在与行人和骑车者特定环境的感知有重要关联的变量中，旅行行为特征是最突出的。这一结果表明，人们倾向于使他们的观念适应他们当前的旅行行为，以减少可能的不和谐并保持他们的心理一致性。换句话说，越走路和使用自行车的人越多，这些旅行模式就越有吸引力。在执行非强制性活动时，更容易说服人们使用AT。因此，应通过更好的基础设施，充分的土地利用开发和信息宣传来鼓励使用AT。
另一项重要发现是活动旅行伴侣的几个特征与周末使用PV和AT之间的关联。我们的假设与个人社交网络子集对其旅行行为的影响有关。这一发现的一个重要应用是，运输调查应包括收集同伴基本特征的问题，这将有助于改进旅行研究和建模工作。
在这项研究中，使用了社交网络的子样本，其中包括活动和旅行伴侣的放大列表。我们的假设与个人社交网络子集对其旅行行为的影响有关。与旅行行为文献中提供的社交网络详尽研究相比，可以以昂贵有效的方式获得有关活动旅行伴侣的信息。运输调查和活动研究应包括收集同伴基本特征的问题，这将有助于改进活动旅行研究和建模工作。
这项研究的局限性包括可能的住宅自我选择偏差，以至于参与者的旅行偏好和观念也可能影响住在哪里。然而，这种限制可能并不重要，因为只考虑对行人和骑车者环境的特定要素的看法，而不是全球对建筑环境的看法。

检查公共交通使用与主动通勤之间的联系
Melissa Bopp 1，*，Vikash V. Gayah 2和Matthew E. Campbell 1


背景：公共交通（PT）使用与身体活动之间存在已建立的关系。然而，有限的文献研究了PT使用和主动通勤（AC）行为之间的联系。本研究检查此链接以确定PT用户是否通过活动模式进行更多通信。方法：成人志愿者，便利样本（n = 748）完成了关于AC / PT模式，人口统计学，社会心理学，社区和环境因素的在线调查。t -test比较了PT车手和非PT车手之间的差异。二元逻辑回归分析检查了多因素对AC的影响，并进行了完整的逻辑回归模型来检验AC。结果：非PT车手（n= 596）报告的AC比PT车手少。在考虑PT使用时，人口统计学，人际关系，工作场所，社区和环境因素与AC有几个显着的关系。包括年龄，儿童数量和感知工作距离的逻辑多变量分析作为负面预测因子和PT使用，恶劣天气的感觉以及作为AC，感知行为控制和配偶AC障碍的街头自行车道缺乏是积极的预测因素。结论：本研究揭示了AC与PT使用之间的复杂关系。进一步的研究应该调查AC和公共交通的使用是如何相关的。

关键词：
 积极运输; 公共交通; 体力活动; 健康; 上下班
 
1.简介

参与定期体育活动与许多益处相关，包括降低心血管疾病，肥胖症，糖尿病，某些癌症和精神疾病的发病率和死亡率[1]。尽管这些已知的好处，在有规律的体力活动的参与一直在下降[2]，和国家的自我报告的数据表明，人口不到50％，目前达到身体活动的建议[34]。这是美国肥胖和代谢相关疾病发病率上升的潜在因素[5]]。由于身体活动对健康人群至关重要，因此必须考虑所有可能的身体活动领域 -包括休闲时间（自由裁量或娱乐），职业（工作相关），家庭（家务/码头工作），以及交通（步行或骑自行车旅行） - 确定哪些区域可以改善[6]。目前关于健康结果的大多数文献主要涉及休闲活动[1]; 然而，由于参与率低于最低水平，因此有必要对所有类型的活动进行检查，以解决人口水平的健康问题。
运输中涉及的身体活动水平特别令人感兴趣，因为大多数人必须每天旅行。在活动模式下进行部分或全部旅行 - 例如步行或骑自行车 - 可以导致日常的身体活动，这可以带来显着的健康益处。例如，从全国调查的数据发现活跃旅游和自我报告肥胖之间的负相关关系[ 7，8，9]，但应注意的是，其他的证据表明没有很好地建立的关系[ 10 ]。积极通勤（AC）的其他证明健康益处包括心血管疾病的风险降低和全因死亡率[ 11，12，13]和改善精神健康[ 14，15，16 ]。积极的通勤也被认为是增加整个人口体育活动的有希望的措施; 例如，健康人2020年的体育活动目标包括提高主动交通出行比例的举措，作为实现长寿和健康公平的总体目标的一部分[17]。除了身体和精神健康的好处，也有增加AC [相关的显着的生态/环境效益和经济效益18，19，20 ]。例子包括减少碳排放，减少燃料消耗和增加对社区的参与。
然而，旅行数据表明，主动通勤代表了一小部分旅行。在考虑最常见的旅行之一 - 每日工作之旅 -活动模式是美国最不常见的旅行方式之一。虽然主动通勤模式在一些规模较小，人口较少的大都市区（例如伊萨卡，科瓦利斯，艾姆斯步行，科瓦利斯，尤金，柯林斯堡，戴维斯骑自行车）成功[21]，但他们在一个国家的成功率较低水平。来自综合家庭调查的数据表明，美国大多数上班族（约86％）使用私人车辆上下班，而只有极少数人口走路或骑车上班（3％） [22]。

另一种感兴趣的旅行模式是公共交通（即公共交通-PT），近期似乎在增加，可能是由于多种因素造成的：美国燃料成本增加，拥堵和城市化，服务改善，价值观念不断变化。美国公共交通协会的数据显示，从1995年到2010年，公共交通的出行次数增加了30％[ 23 ]。与主动旅行模式相比，更多的人也使用公交去上班; 根据综合家庭调查，全国大约5％的工作旅行是通过公交进行的，而只有3％是通过步行或骑自行车制作的[ 22]]。在纽约市，华盛顿特区，芝加哥，波士顿和旧金山等人口众多的大都市区，公共交通使用率特别高（高达12％-30％）。美国人口普查数据还表明，在非西班牙裔黑人，亚洲人，西班牙裔美国人或在美国以外出生的人中，PT的使用率往往特别高[ 21 ]。

由于PT用户通常必须步行或自行车来访问他们的中转站，它是不奇怪的PT使用已被链接到在物理活性增加参与24，25，26，27，28 ]。因此，人们会期望公共交通用户享受到重大的健康益处。这已在文献中得到证实。例如，对2001年美国全国家庭旅行调查的分析表明，公共交通的使用与减少肥胖相关[ 29 ]，最近的一项研究也证实了这一点[ 30]。]。公共交通使用从更大的活性分开的其他显着的健康益处包括降低乘客死亡率，较低的应力水平和改善空气质量[ 31，32，33 ]。澳大利亚一项针对大学生的研究还发现，与报告私人机动车使用率较高的学生相比，那些使用公共交通工具的人更有可能达到计步器测量的10,000步/天的公共卫生目标[ 34 ]。Lachapelle及其同事用美国样本同意这些发现，同时注意到，无论邻居的步行能力如何，社会心理因素也会影响公共交通和身体活动之间的关系[ 35]。与公共交通相关的健康益处也可以具有重大的货币价值; 例如，斯托克斯和其他人[36]估计，在北卡罗来纳州夏洛特（美国）安装轻轨交通系统将导致9年累计公共卫生成本节省1260万美元，原因是体育活动增加和减少肥胖。使用欧洲数据，Rabi和de Nazelle [37]也注意到与汽车旅行减少相关的显着成本节约和健康改善。
尽管公共交通与体育活动之间已建立起关系，但有限的文献研究了公共交通使用与主动通勤行为之间的联系。类似于使用健康行为理论来检查一般身体活动参与的研究，使用理论基础可以帮助解释行为[ 38 ]。目前的研究中，建立在其他研究[ 39，40，41，42，43，44 ]，使用构建体从计划行为[理论45 ]（感知行为控制，主观规范）和社会认知理论[46]（自我效能 -一个人相信他/她执行特定任务的能力）以更好地理解主动通勤行为。因此，本研究的目的之一是检查公共交通乘客是否会影响个人的积极通勤行为; 也就是说那些使用过境车的人比非过境旅行更有可能使用主动模式吗？如果属实，我们会寻求确定个人，社会，工地社区或环境因素如何影响这种关系。最后，该研究旨在确定影响活动方差的最重要因素[ 32在控制公共交通使用时的通勤行为，因为后者被发现是前者的重要预测因素。这项研究的结果将揭示可能有助于增加个人之间积极通勤的潜在战略或政策的见解。

2。材料和方法

为了研究公共交通使用与主动通勤行为之间的联系，使用了对美国中大西洋地区通勤者的调查结果。以下部分详细介绍了此数据收集工作，调查问题以及用于分析调查结果的方法。

2.1。学习规划

该横断面调查于2011年6月至12月使用Qualtrics软件程序（Provo，UT，USA）在线提供。该研究由宾夕法尼亚州立大学机构审查委员会批准。
参与者和招聘18岁或以上，在家外全职或兼职并且能够步行或骑自行车的成年人都有资格参加调查。招募主要发生在美国中大西洋地区（PA，OH，WV，MD，NJ，DE）。对大中城市的大型雇主（例如，K-12学区，地方/县政府，私营企业，大学/学院）的网站进行了员工电子邮件地址的检查，并通过电子邮件直接联系了个人。这些参与者收到了“ 关闭“使用唯一能够访问一次的唯一URL进行调查。当个别员工的电子邮件地址是不可用的，用人单位进行了联系，并要求分发的电子邀请参加在通过邮件列表，电子通讯，或群发电子邮件的调查，并链接到一个开放的URL。在这种情况下，注意到收到邀请的员工人数。在联系发出电子邮件邀请的雇主中，只有两名雇主拒绝这样做，而84名雇主没有回应任何未经联系的联系，56名雇主发出邀请。电子联系人邀请人们参加“通勤调查””。要求参与者自我报告他们是否可以在他们的社区中使用公共交通工具，只有那些报告是的人才被纳入分析。参与者的招募如图1所示。
 
图1. 参与者招募。

2.2. 措施

2.2.1. 通勤模式

要求与会者反思上个月的情况，并平均报告他们每周行走，骑车，驾驶私家车的次数，以及上下班的公共交通（如有）（例如，个人报告行走）往返工作将算作两次旅行）。通过步行和骑自行车的个人旅行的数量被总计为活动的通勤旅行的总数。个人被分为活跃的通勤者（> 1次AC旅行/周）或非活跃的通勤者（0次AC旅行/周）。另外，公共交通出行的数量相加，个人被划分为公共交通车手（> 1次/周）或非公共交通车手（0次/周）。这包括使用公共交通工具的任何人，无论用于访问公交的模式如何（例如，

2.2.2. 公共交通使用模式

公共交通工具被要求报告他们在公共交通工具上骑自行车的频率以及他们在早些时候下车的公共交通的频率，以便步行或骑自行车进入目的地，使用1（从不）到4（经常）规模。参与者使用一个明确的问题自我报告他们的过境站距离他们的家和工作场所有多远。家庭/工作距离中转站（编码为0英里）不到0.5英里，家庭/工作距离中转站（编码为0.5英里）超过0.5英里，确定了到中转站的总距离（0,0.5）和1英里的可能值）。使用半英里，因为它将是大约10分钟的步行，这将是一个有意义的体育活动。

2.2.3. 人口统计学和医疗

与会者报告了他们的年龄，种族/族裔群体，婚姻状况，子女人数，教育程度，收入水平，性别，就业年限和类型。参与者从列表中指出他们患有多少种慢性疾病并报告他们的体重指数（BMI）计算的身高和体重。

2.2.4. 自我效能感

使用4分李克特量表（1 =完全没有信心4 =对自行车技能非常有信心），参与者对他们在城市地区的自行车技能进行了评分。

2.2.5. 积极的通勤行为信念

向受访者提交了八项与AC的身体或心理健康有关的陈述（例如，AC帮助我控制体重，可以帮助我减轻压力），五份陈述涉及其他AC益处（例如AC对环境有益，有帮助我省钱，帮助我提高工作效率，让我成为更好的员工，让我更专注。）受访者表示他们同意13项关于AC的陈述，使用7分李克特量表（1=完全不同意，7=完全同意）。计算所有13个项目的总分。基于先前测试的量表[ 47 ]，该测量显示出极好的可靠性（α= 0.91）。

2.2.6. 对主动通勤的感知行为控制

使用7分李克特量表（1 =完全不同意，7 =完全同意），参与者表示同意六个关于为什么AC很难的陈述（例如，AC很难，因为我没有承诺;因为我太累了）[ 47 ]。计算了六个项目的总分，并且是可靠的（α= 0.84）。

2.2.7. 同事和配偶主动通勤行为

使用5分李克特量表（1 =非常不同意，5 =强烈同意）参与者回答了关于他们的同事的AC行为的问题：“我的大多数同事步行或骑自行车上下班”。与会者还报告了他们的配偶走路，骑车或使用公共交通工具上下班的次数/周。步行和自行车旅行的总和被总计为配偶AC。

2.2.8. 工地

参与者表示他们认为他们的雇主支持AC使用5分李克特量表（1=非常不同意，5=强烈同意）。受访者报告其雇主的规模并指出（是/否）雇主支持AC的数量（例如，为AC提供的奖励，与AC相关的活动，灵活的工作时间，自行车存放政策，自行车停放，更衣室，灵活的着装要求），总结。在工作中停车的感知问题被评估为三个项目：缺乏可用性，高成本和难以停车，具有相同的1-5李克特量表（更高的分数=更多的工作停车问题）。

2.2.9. 社区

参与者报告了在他们的社区中有三种骑自行车支持的可用性（是/否）（即公共汽车上的自行车架，有盖自行车停放，“ 分享道路“标志”，总结。使用5分李克特量表评估对步行和骑自行车的感知支持（1=非常不同意，5=强烈同意），要求参与者表明他们同意五个陈述（例如，城镇/城市支持行人或骑车人的问题，看到其他人在他们的社区散步或骑自行车，以及维护人行道或自行车道）。通过对得分求和来计算感知社区支持。行人和自行车友好感受分别评估; 与个人评价他们的社区使用1（该区域不是步行/自行车友好）到5（该区域是非常行人/自行车）规模。参与者表示他们认为需要多长时间才能走路或骑自行车上班，这被分为≤20分钟和20分钟以上。

2.2.10. 环境障碍

通过5分的李克特量表（1 =非常不同意，5=强烈同意），参与者表明了感知的环境障碍如何阻止他们步行或骑自行车上班。项目包括：缺乏街道自行车道，缺乏街道步行/自行车道，缺乏人行道，沿途的交通速度和交通量，沿路线感知犯罪，地形复杂和恶劣天气。

2.3. 分析

基本描述性统计和频率用于描述样本。t -test比较了公共交通车手（PTR）和非公共交通车手（非PTR）之间的差异。t检验和方差分析（ANOVA）用于检查组间的差异。必要时Tukey 事后测试与ANOVA一起用于检查组间的显着差异。交流次数/周的次数被划分为0次旅行/超过一次旅行，并且以公共交通旅行作为常数变量进行二元逻辑回归分析，以检查公共交通使用对AC的影响。还进行了完整的逻辑回归模型以检查影响AC行为的因素。在考虑共线性之后包括显着相关的变量，最终模型包括个人，人际关系，工作场所，社区和环境变量。所有分析均使用IBM SPSS 20.0（Armonk，NY，USA）进行，显着性水平设定为p <0.05。

3.结果

按公共交通使用细分的样本汇总统计数据见表1。非公共交通车手（n=596）报告开车上班8.36±3.37次/周并积极减少1.57±3.37次/周。
这与报告开车上班2.71±3.54次/周（t=18.28，p<0.001）并积极通勤4.26±4.55次/周（t=8.16，p<0.001）的公共交通车手有显着差异。PTR报道公共交通每周有4.43±3.51次旅行。每户平均车数（2.98）高于2012年美国全国平均2.08辆/家庭[ 48]。

3.1. 公共交通车手与非公共交通车手之间的差异

与NPTR相比，PTR更可能是男性，报告收入较低，非白人和兼职。非公共交通车手更有可能变老，报告家中有更多儿童，家中有更多车辆。PTR报告说自行车技能的自我效能更强，对主动通勤的行为控制更强。与PTR相比，NPTR更有可能报告被雇用超过两年，而PTR更有可能报告更短的就业时间。PTR中的配偶AC行为和公共交通乘客以及同事AC行为也更大。NPTR更有可能报告他们的职业是K-12教育（31.8％），高等教育/研究（21.2％）或白领专业人士（16.8％），而PTR更有可能报告高等教育/研究（36。

与NPTR相比，PTR更有可能在更大的雇主（超过100名员工）工作，并报告更多的感知停车问题。此外，PTR更有可能感受到雇主对AC的支持，报告了更多的雇主支持AC和社区支持AC与NPTR相比。PTR不太可能报告缺乏街道自行车道，缺乏街道步行/自行车道，缺乏人行道，沿途的交通速度和交通量，以及与NPTR相比AC的障碍。
表1. 样品的特征（n = 748）。

3.2. 公共交通车手的距离和习惯

在PTR中，观察到以下报告的距离：59.6％（n=99）报告距离他们的公交站点不到0.5英里，26.5％（n=44）报告距离他们的公交站点0.5-1英里和13.9公里％（n = 23）报告距离他们的中转站1英里以上。在过境车手中，78.1％（n=125）从未在运输车辆上骑自行车，16.9％（n=27）报告偶尔将公共交通工具带上自行车，1.9％（n=3）报告有时或经常这样做。骑手没有报告提早下车行走或骑自行车; 60.1％（n=95）的报告从未在公共交通中提前步行/骑自行车，25.3％（n据报道偶尔会报告这一情况，并且14.6％（n=23）报告有时或经常这样做。

3.3. 与积极通勤相关的因素

表2列出了显示出作为主动通勤者相对于个体变量同时控制公共交通乘客的可能性的比值比。根据以前的工作和直觉，结果如预期。年龄较小，孩子较少，体重指数较低，汽车较少，慢性病较少，这些都与积极的通勤者有关。与女性相比，男性更有可能成为活跃的通勤者。
表2. 作为主动通勤者的控制公共交通使用的奇数比率（n=748）。

结婚，在当前工作岗位工作超过2年的人和报告家庭收入超过60,000美元/年的人不太可能报告AC，而那些属于“其他人”的人“种族/族裔群体更有可能成为活跃的上班族。正如预期的那样，那些对自行车有更大自我效能，对AC有正面信念和感知行为控制的人更有可能成为活跃的上班族。配偶和同事AC参与与活跃的通勤者相关，以及更多的工作场所支持和更多的停车问题。那些为大公司工作的人（>100名员工）在控制PT使用时不太可能成为活跃的上班族。报告AC较少的社区支持与活跃的通勤者相关联，报告更多的自行车和行人友好社区也与AC有关。报告行走时间和骑行时间较短的人更有可能成为活跃的上班族。报告环境障碍较少的人（缺乏路边自行车道，

3.4. 主动通勤的预测因子
AC的逻辑多变量分析（参见表3）产生Nagelkerke R 2 = 0.776，表明对数据的良好拟合。年龄，儿童人数和感知工作距离是负面预测因素，而恶劣天气和缺乏街道自行车道作为主动通勤，感知行为控制和配偶AC的障碍是积极的预测因素。公共交通乘客拥有所有变量的最大比值比（OR =12.29 95％CI = 3.59-42.10，p<0.001），这意味着PT使用是所有变量的AC行为的最重要预测因子。
表3. 主动通勤的逻辑回归（是/否）（n = 748）。

4.讨论和结论
虽然有限，但这项研究有助于揭示公共交通使用与主动通勤之间的联系。以往的研究表明，使用公共交通与步行活性量增加有关29，30 ]，这很可能是由于这样的事实，公共交通使用者必须步行或骑自行车进入公交线路。这些早期的作品还发现，公共交通用户更有可能步行到家附近的工作地点和工作[ 35 ]并且通常有更积极的生活方式[ 24]]。然而，这项研究表明，公共交通的使用（即使每周只有一次）也显着减少了开车上班次数和活跃模式下的旅行次数，这与丹麦成年人的调查结果相似[ 49 ]。Lachapelle和Frank [ 26 ] 首先提到了这种关系，它发现了过境通行证和步行上班之间的正相关关系。除了上述原因之外，随意观察表明，一些公共交通车手倾向于放弃过境，而是如果他们在车辆离开后到达交通站点，则步行或骑车到目的地（即，当他们期待很长时间等待运输车辆时）。如果是这种情况，两种行驶模式比以前想象的更具内在联系。
也许更有趣的是，这项研究首次揭示了公共交通车手也认为环境障碍对于主动通勤的影响不如非公共交通车手，对主动通勤具有更高的感知行为控制，并且对于骑自行车具有更高的自我效能。这些关系的因果关系不是很清楚，特别是考虑到影响通勤行为的土地使用模式没有被考虑; 例如，不知道旅行者是否认为环境因素不是障碍因为他是频繁的公共交通用户，或者如果旅行者成为公共交通用户，因为他认为这些环境因素不是障碍。天气也可能是一个因素，通常步行或骑自行车上班的人可能会在恶劣天气而不是开车时选择公共交通。需要进一步的工作来梳理这种因果关系，但这种关系的存在肯定是有趣的。
尽管缺乏因果关系的方向，但在控制这些类型的行为因素时，公共交通乘客似乎是在个人之间工作的主动通勤行为的预测因素。这一结果强化了伯克和布朗的猜想[ 33通过步行和骑自行车增加身体活动可以通过促进公共交通服务来实现。旨在促使从汽车到公共交通的模式转变的措施 - 例如增加过境服务或补贴过境票价 - 不仅可以增加机动性并减少车辆排放，而且还应该具有促进步行和骑自行车上班的额外好处。最近的证据表明，拥有一个连接良好且完整的公共交通网络可能会导致一些人的汽车/家庭减少，这与积极旅行的增加有关[ 50 ]。由于活性通勤模式对健康的益处是有据可查的[ 7，8，9，11，12[ 13]，这进一步突出了公共交通服务与更好的人口健康之间的联系。因此，公共交通不仅可以成为宜居城市的重要组成部分[ 51]，而且也是健康社区的重要组成部分。
除了公共交通使用外，结果还突出了一些关于主动通勤的其他重要见解。即使在控制公共交通使用时，诸如AC的感知行为控制，骑自行车的自我效能和AC行为信念等心理因素与作为主动通勤者的可能性增加显着相关。因此，行为策略可能成功地促进积极的通勤。例如，旨在提高城市骑行技能和舒适度的课程应该有助于提高某人骑自行车的自我效能，并导致他们骑自行车上下班的可能性增加[ 52 ]。范德克洛夫等人。[ 53]采用这种方法与阿姆斯特丹的一些非西方移民妇女建立自行车技能，并取得了可喜的成果。强调日常体育活动重要性的教育外展以及如何通过积极的旅行模式实现这一目标也可能有助于激励上班族步行或骑车上班。这些行为策略应特别针对那些生活在密集城市地区的人们，那里的通勤旅行通常较短，因为那些感知旅行时间较短的人通常更倾向于使用主动模式。

工作场所的因素也被认为对于成为主动通勤者的可能性很重要，即使在控制公共交通使用时也是如此。与Kaczynski及其同事的研究结果类似，美国的社会和物理支持样本对AC的影响很大[ 54]，目前的研究指出了这些影响的重要性。不仅主动模式的雇主支持（例如灵活的工作时间，储物柜/更衣室，自行车停放）与增加的主动通勤显着相关，而且仅仅是对雇主支持和工作中的停车问题的看法增加了某人是活跃的通勤者。因此，工作场所的有针对性的政策（例如，停车收费或向不开车上班的人提供金钱奖励）可以帮助激励员工转向公共交通或主动模式，此外还有更好的员工对设施和雇主提供的奖励。
尽管有重大发现，但仍有一些限制需要注意。本研究采用的横截面设计限制了我们对因果关系如何与AC行为相关的因果关系陈述或时间假设的能力。我们的抽样策略和使用志愿者，便利样本限制了普遍性以及我们客观评估土地使用因素的能力。我们的策略是响应率低; 然而，鉴于该调查以电子方式提供，我们报告的回复率极可能过于保守，因为完成调查的许多电子邀请都可能被过滤为“垃圾邮件”“/垃圾邮箱从未被潜在的参与者看到。其中一个最重要的限制是我们依赖自我报告措施来衡量交流行为，公共交通的使用以及所有人际关系，工地，社区和环境因素。该领域的其他调查应考虑对运输方式采用替代或更客观的测量形式，并可能对旅行方式的选择产生影响。我们还注意到，我们没有询问个人如何往返于他们的中转站，因此我们缺乏这些可能的多模式旅行的数据。此外，我们只检查了主动交通工作，并且无法确定一般活动旅行对个人的作用。其他研究应调查AC与整体主动运输的关系。最后，这项工作的另一个限制是无法控制通勤者工作和家庭周围的土地使用模式。这些土地利用模式也可能对公共交通使用和主动通勤行为产生重大影响，在未来的研究中应予以考虑。

尽管有这些限制，但这项研究揭示了AC与公共交通使用之间的复杂关系。鉴于非常具有潜在的健康，环境和经济效益，需要进一步研究调查空中交通和公共交通的使用情况以及如何调节另一个。该研究为未来针对AC的人群层面健康策略提供了基础。正在计划进一步研究以解决当前努力的局限性。

