---
title: "STAT 561"
subtitle: "Sutdy notes"
author: "Teached by Fountain"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  xaringan::moon_reader:
    css: "example.css"
    seal: yes
    nature:
      highlightStyle: github
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
options(width = 2000)
options(repos="https://cran.rstudio.com")
```

 2018-09-26: www.mth.pdx.edu/~fountain
#### 1. 
1. Definition: An **experiment** is a process that leads to one of several possible outcomes.
    
1. Definition: The **sample space** (S) is the set of all possible outcomes of an experiment.

1. Definition: An **event** is a subset of S

- subset
- intersection
- union
- Complemnet of A
- empty set
---
#### 2. 
1. Definition: A and B are _disjiont or mutually exclusive_, if $A\cup B=\emptyset$

1. Let B be a subset of all possible subset of S. Then B is a **Borel field** or a $\sigma$-algebra, if
    
   (1). $A\cup B=\emptyset$
    
   (2). if $A\in B, then\ A^c\in B$
    
   (3). if $\{A_{1},A_{2},A_{3},...\}\subset B, then\ \bigcup_{n=1}^{\infty}\in B$

#### 3. Kolmugorov axious/properties
let B be a **Borel field**. Then P is a **probability set function** if
    
   (1). $\forall A\in B,\ P(A)\ge0$
    
   (2). $P(S)=1$
    
   (3). If $A_{1},A_{2},A_{3}$,...are pairavise disjoint, then $\ P(\bigcup_{n=1}^{\infty}A_i)=\sum_{i=1}^{\infty}P(A_{i})$
---

#### 4. Example
Roll a 6-sides die $S=\{1,2,3,4,5,6\}$

  $B=\{\emptyset ,S,\{1,2\},\{3,4,5,6\}\}$
  
  is a well-defined **Borel field**
  
Define：
  $P(A)=\begin{cases}1&if\ 2\in A \\o &otherwise\end{cases}$
  
  This is a well-defined **probability function**
  
Define: 
  $P(A)=\frac{element in A}{6}$
  
  This is also a well-defined **probability function**

---

##### 5. 
Theorem:
   $\forall A\in B,\ P(A^c)=1-P(A)$
   
   Proof: $A\cap A^c=\emptyset$; $A\cup A^c=S$
   $P(A\cup A^c)=P(A)+P(A^c)$  [by K-3]
   $P(S)=1$                   [by K-2]
   $P(S)=1$

Theorem:  
   $P(\emptyset)=0$
   
   Proof: $\emptyset\cap S=\emptyset$; $\emptyset\cup S=S$
   $P(\emptyset\cup S)=P(\emptyset)+P(S)$; $P(\emptyset\cup S)=P(S)=1$

---
##### 6. 

Theorem:  
   Let $A_{1}$ and $A_{2}$ the elements of B
   with $A_{1}\subset A_{2}$, then $P(A_{1})\le P(A_{2})$
   
   Proof:
   Let $A_{1}\subset A_{2}$ with $A_{2}=A_{1}\cup (A_{2}\cap A_{1}^c)$
   Also $A_{1}\cap(A_{2}\cap A_{1}^c)=\emptyset$
   So $P(A_{2})=P(A_{1})+P(A_{2}\cap A_{1}^c)$
   $P(A_{2}\cap A_{1}^c)\ge0$, $\therefore\ P(A_{2})\ge P(A_{1})$

---
 2018-09-27
##### 1. 
Theorem:
   $P(A\cap B^c)=P(A)-P(A\cap B)$
   
   Proof:
   $A=(A\cap B)\cup(A\cap B^c)=A\cap(B\cup B^c)$ by disirb law
   $=A\cap S=A$
   So $P(A)=P(A\cap B)+P(A\cap B^c)$
   
Define: 
   $A \B =A\cap B^c$
---

##### 2. 
Theorem:
   $P(A\cap B^c)=P(A)-P(A\cap B)$

---

# Why Regression Analysis?

- Regression analysis allows scientists to quantify how the average of one variable systematically varies according to the levels of another variable;
- Comparing with hypothesis testing techinque we reviewed before, additional variables can be introduced into regression models to help to determine if a relationship is genuine or spurious;
- Regression models also allow scientists to examine the mechanisms that their theories and ideas suggest explain the association between a particular predictor variable and an outcome;
- Regression models can be used to examine how two predictors jointly associate with an outcome variable;
- Regression models can be used for predictions or scenario analysis.

---

# Why Regression Analysis - An Example

[Eng, Sothy. 2012. “Cambodian Early Adolescents’ Academic Achievement: The Role of Social Capital.” Journal of Early Adolescence 33(3): 378–403.](http://journals.sagepub.com/doi/pdf/10.1177/0272431612441069)
