---
title: "Case Study Discussion"
subtitle: "USP 537"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  xaringan::moon_reader:
    css: "example.css"
    seal: yes
    nature:
      highlightStyle: github

---

## 

****

### 01/22	Congestion Charge

Leape, J. (2006). The London congestion charge. The Journal of Economic Perspectives, 20(4), 157-176.

Albalate, D., & Bel, G. (2009). What local policy makers should know about urban road charging: Lessons from worldwide experience. Public administration review, 69(5), 962-974.

Vonk Noordegraaf, D., Annema, J. A., & Van Wee, B. (2014). Policy implementation lessons from six road pricing cases. Transportation Research Part A: Policy and Practice, 59, 172-191.

****

### 01/29	Variable Road Pricing

Burris, M., & Sullivan, E. (2006). Benefit-cost analysis of variable pricing projects: QuickRide HOTlanes. Journal of transportation engineering, 132(3), 183-190.

Sullivan, E., & Burris, M. (2006). Benefit-cost analysis of variable pricing projects: SR-91 express lanes. Journal of transportation engineering, 132(3), 191-198.

Janson, M., & Levinson, D. (2014). HOT or not: Driver elasticity to price on the MnPASS HOTlanes. Research in Transportation Economics, 44, 21-32.

****

### 02/05	Bus Rapid Transit

Cervero, R. (2013). Bus Rapid Transit (BRT): An Efficient and Competitive Mode of PublicTransport. IURD Working Paper 2013-01.

Nelson, A. C., Appleyard, B., Kannan, S., Ewing, R., Miller, M., &Eskic, D. (2013). Bus Rapid Transit and Economic Development: Case Study of the Eugene-Springfield BRT System. Journal of Public Transportation, 16(3).

****

### 02/12	Parking

Pierce, G., & Shoup, D. (2013). SFpark: Pricing Parking by Demand. ACCESS Magazine, 43.

Arnott, R., & Inci, E. (2006). An integrated model of downtown parking and traffic congestion. Journal of Urban Economics, 60(3), 418-442.

Anderson, S. P., & de Palma, A. (2004). The economics of pricing parking. Journal of UrbanEconomics, 55(1), 1-20.

****

### 02/26	Privatization

Estache, A., Carbajo, J., & De Rus, G. (1999). Argentina's transport privatization and re-regulation: ups and downs of a daring decade-long experience (Vol. 2249). World Bank Publications.

Estache, A., González, M., & Trujillo, L. (2002). What does “privatization” do for efficiency?Evidence from Argentina’s and Brazil’s railways. World Development, 30(11), 1885-1897. 

Litman, T. (2011). Contrasting Visions of Urban Transport Critique of “Fixing Transit: The CaseFor Privatization”. Victoria Transport Policy Institute.

****

### 03/05	Fuel Economy Standards

Anderson, S. T., Parry, I. W., Sallee, J. M., & Fischer, C. (2011). Automobile fuel economystandards: Impacts, efficiency, and alternatives. Review of Environmental Economics and Policy, 5(1), 89-108.

Portney, P. R., Parry, I. W., Gruenspecht, H. K., & Harrington, W. (2003). Policy Watch: The Economics of Fuel Economy Standards. The Journal of Economic Perspectives, 17(4), 203- 217.

****

### 03/12	Ridesharing

Chan, N. D., & Shaheen, S. A. (2012). Ridesharing in North America: Past, present, and future. Transport Reviews, 32(1), 93-112.

Murray, G., Chase, M., Kim E., & McBrayer, M. (2012). Ridesharing as a Complement to Transit.TCRP Synthesis 98. Transportation Research Board.

Anderson, D. N. (2014). “Not just a taxi”? For-profit ridesharing, driver strategies, andVMT. Transportation, 41(5), 1099-1117.