---
title: 'USP537 Schedule'
author: ""
date: "Winter 2019"
output: html_document
---

# 

## I. Introduction & Microeconomic Foundations

[GTW] Chap 11 – “The Urban Transportation Problem: A Reexamination and Update”

Klein, Moore & Reja [KMR] Chap 1 – “Introduction”

[KMR] Chap 2 – “The Triumph of the Automobile”

[KMR] Chap 3 – “The Fizzle of Traditional Transit”


## II. Demand for Transportation

[GTW] Chap 2 – “The Demand for Transportation: Models and Applications”

[GTW] Chap 10 – “Determinants of Motorization and Road Provision”

[GTW] Chap 13 – “Accessibility and Economic Opportunity”

Graham, D. J., & Glaister, S. (2004). Road traffic demand elasticity estimates: a review. Transport reviews, 24(3), 261-274.

Litman, T. (2007). Transportation elasticities - How Prices and Other Factors Affect


## III. Transportation and Land Use

[GTW] Chap 12 – “Transportation and Land Use”

## IV. Project Evaluation

[GTW] Chap 5 – “Project Evaluation”

Lakshmanan, T. R., & Chatterjee, L. R. (2005). Economic Consequences of Transport Improvements. Access, 26:28-33. University of California Transportation Center.

GAO (2005). Highlights from an Expert Panel - The Benefits and Costs of Highway and Transit Investments.

## V. Supply of Transportation

[GTW] Chap 3 – “Learning about Transport Costs”

[GTW] Chap 4 – “Pricing”

Flyvbjerg, B., Holm, M. S., & Buhl, S. (2002). Underestimating costs in public works projects: Error or lie? Journal of the American Planning Association, 68(3), 279-295.

Lave, C. (1994). It Wasn't Supposed To Turn Out Like This: Federal Subsidies and Declining Transit Productivity. Access 5, 21-25.

Rufolo, A. M., &Bertini, R. L. (2003). Designing alternatives to state motor fuel taxes. Transportation Quarterly, 57(1), 33-46.

## VI. Pricing and Externalities

[GTW] Chap 6 – “Congestion”

[GTW] Chap 7 – “The Politics of Controlling Auto Air Pollution”

[GTW] Chap 8 – “Fuel Economy and Auto Safety Regulations: Is the Cure Worse than the Disease?”

Anas, A., & Lindsey, R. (2011). Reducing urban road transportation externalities: Road pricing in theory and in practice. Review of Environmental Economics and Policy.

Taylor, B. D. (2002). Rethinking traffic congestion. Access, 21, 8-16.

Small, K. (2005). Road pricing and public transit: Unnoticed lessons from London. Access, 26(3), 10-15.
