---
title: 'STAT562 Homework'
author: ""
date: "Winter 2019"
output: html_document
---

#  {.tabset .tabset-fade .tabset-pills}

## HW1

**4.4**  A pdf is defined by 

f(x ) = c(x + 2y) if 0 <y< 1 and 0 < x < 2 , 

0 otherwise.

 (a). Find the value of C.
 (b). Find the marginal distribution of X.
 (c). Find the joint cdf of X a.nd Y.
 (d). Find the pdf of the random variable Z=9/(X + 1)^2

---

**4.11** Let U the number of trials needed to get the first head and V the number of trials needed to get two heads in repeated tosses of a fair coin. Are U and V independent random variables?


---

**4.16** Let X and Y be independent random variables with the same geometric distribution.

 (a). Show that U and V are independent, where U and V are defined by

U = min(X, Y ) an d V = X - Y.

 (b). Find the distribution of Z = X/(X + Y), where we define Z = 0 if X+Y=O.

 (c). Find the joint pdf of X and X + Y.

---

**4.17** Let X be an exponential( l ) random variable, and define Y to be the integer part of X + 1, that is

Y = i + l if and only if i S X < i + l , i = O, 1, 2, . . . .

(a) Find the distribution of Y . What well-known distribution does Y have?
(b) Find the conditional distribution of X -4 given $Y\ge5$.

---

**4.20** Xl and X2 are independent $n(0, \sigma^2)$ random variables.

 (a). Find the joint distribution of Y1 and Y2 , where
 
$Y_1 = X_1^2 + X_2^2$ and $Y_2 =\frac{X_1}{\sqrt{Y_1}}$

 (b). Show that Y1 and Y2 are independent, and interpret this result geometrically.


## HW1

**5.7** In Example 5.2. 10, a partial fraction decomposition is needed to derive the distribution of the sum of two independent Cauchy random variables. This exercise provides the details that are skipped in that example.

 (a). Find the constants A, B, C, and D that satisfy

1 1
1 + (W/U)2 1 + « z - w)/r)2
Aw B Cw
1 + (w/a)2 +
1 + (w/aF - 1 + « z 􀤃 w)/r)2

where A, B, C, and D may depend on z but not on w.

 (b). Using the facts that

D
1 + « z - w)/r)2 '
J 1 : t2 dt = 􀀦 log ( 1 + t2 ) + constant and J 􀁠
2 dt = arctan(t) + constant,
l + t

evaluate (5.2.4) and hence verify (5.2.5).

(Note that the integration in part (b) is quite delicate. Since the mean of a Cauchy does not exist, the integrals J::::' 1+(:/'0")2 dw and J􀄌oo 1+« .°:)/1')2 dw do not exist.
However, the integral of the difference does exist, which is all that is needed.)

---

**5.10** Let Xl , ... , Xn be a ra.ndom sample from a $n(\mu,\sigma2)$ population.

 (c). Calculate Var 82 a completely different (and easier) way: Use the fact that
(n 1)82/(72 '" X-l '

---

**5.13** Let Xl , . . . , X". be iid n(J1., (72). Find a function of 82, the sample variance, say g(82),
that satisfies Eg(82) (J". ( Hint: Try g(82) c..(S2, where c is a constant.)

---

**5.15** Establish the following recursion relations for means and variances. Let X.,. and 8! be the mean and variance, respectively, of Xl , . . . , Xn• Then suppose another observation, Xn+l , becomes available. Show that

 (a). X _ xn + l + n n+1 - X',,- n + 1


 (b). n8n+l - (n - 1)8.. + n + - 2 1 (Xn+1 - Xn) .
 
 
