---
title: 'STAT 661: ADV MTH STAT I'
author: "Jacob, Robin, Ryan & Shen"
date: Dec, 2019
subtitle: Zip_EM
output:
  ioslides_presentation: 
    incremental: true
  beamer_presentation:
    includes:
      in_header: "preamble.tex"
  slidy_presentation: default
---

# Topic

Schmee, J., & Hahn, G. (1979). A Simple Method for Regression Analysis With Censored Data. Technometrics, 21(4), 417-432.

## Abstract {.smaller}


Problems requiring regression analysis of censored data arise frequently in practice. For example, in accelerated testing one wishes to relate stress and average time to failure from data including unfailed units, i. e., censored observations. Maximum likelihood is one method for obtaining the desired estimates; in this paper, we propose an alternative approach. An initial least squares fit is obtained treating the censored values as failures. Then, based upon this initial fit, the expected failure time for each censored observation is estimated. These estimates are then used, instead of the censoring times, to obtain a revised least squares fit and new expected failure times are estimated for the censored values. These are then used in a further least squares fit. The procedure is iterated until convergence is achieved. This method is simpler to implement and explain to non-statisticians than maximum likelihood and appears to have good statistical and convergence properties. The method is illustrated by an example, and some simulation results are described. Variations and areas for further study also are discussed.


## Introduction

## Related work and literature

## Description of method for simple situation

$$\mu_x=\beta_0+\beta_1x$$
$$\mu^\star_x=\mu_x+\frac{\sigma f(z)}{1-F(z)}$$
where
$$z=\frac{(c_x-\mu_x)}{\sigma}$$

- Iteration 0

- Iteration 1

## Numerical Example {.smaller}

```{r}
n=matrix(c(1764,2772,3444,3542,3780,4860,5196),7,1)
```

## Iteration 0 {.smaller}

- Step 1:

$\hat\beta_0^{(0)}=-4.9307$,$\hat\beta_1^{(0)}=3.7471$,$\hat\sigma^{(0)}=0.1572$.

- Step 2:

$$x=\frac{1000}{170+273.2}=2.256318$$

$$\hat\mu^{(0)}_{2.26}=-4.9307+3.7471\frac{1000}{170+273.2}=3.523948$$

$$C_{2.26}=\ln(5448)=8.603004$$

$$z=\frac{C_{2.26}-\hat\mu^{(0)}_{2.26}}{\sigma}=\frac{8.603004-3.523948}{0.1572}=32.30952$$

$$\hat\mu^{\star(0)}_{2.26}=\hat\mu^{(0)}_{2.26}+\hat\sigma^{(0)}\frac{ f(z)}{1-F(z)}=3.8089$$
Or 6440 hours

## Iteration 1

- Step 1:

$\hat\beta_0^{(1)}=-5.2603$,$\hat\beta_1^{(1)}=3.9263$,$\hat\sigma^{(1)}=0.1799$.

- Step 2:

$$\hat\mu^{\star(1)}_{2.26}=3.83972 $$

## Subsequent Iterations

$\hat\beta_0=-5.81829$,$\hat\beta_1= 4.20426$,$\hat\sigma= 0.204322$.

$$\hat\mu^{\star(17)}_{2.26}=3.87676 $$

## Results of simulation analysis


