---
title: 'USP654 Fall 2017 HW2'
subtitle: Multiple Regression, Dummy Variable, Interaction, and Diagnostics
date: "10/23/2017"
output: html_document
---

**Due on 11/15 on D2L**

Please answer the following questions to the best of your ability using any combination of lectures, readings, and labs to support your work. In some cases I ask you to calculate things via equations, but you are welcome to use R/SPSS functions to check your work. If you use R or SPSS to answer a question, please provide the output including the code.

I am in general far more interested in how you grapple with a question than your final results. In particular, I will not mark you down automatically for an incorrect numeric answer! Anyone can get “the answer” to multiple decimal places these days. Fewer can engage with those answers in a meaningful way. Understanding how an answer might be wrong is often more valuable than a trivially correct result.

1. For the multiple regression result below, answer the series of questions that follows. You may sketch or use software to plot if it helps, but it is not required unless specified. Standard errors (NOT t-stats) are given in parentheses.

    a. Explain the regression equation structure in words (no numbers!)
    a. Perform hypothesis tests on each non-intercept coefficient
    a. Plot the `transit` sample regression line separately for light rail and heavy and commuter rail, and briefly explain the characteristics and differences between the two SRLs.
    a. Interpret the OLS estimation results (this time with numbers), making reference to significance, effect sizes, reasonableness, and overall model fit.
    a. Calculate (showing work), the expected mean housing value for the following properties:
        i. property near light rail with 0.4 transit share and density of 5 units/acre;
        i. property near heavy rail with 0.4 transit share and density of 5 units/acre.
    a. Provide one critique of the model as it is, making reference to your interpretation in d.
    a. Provide one additional variable along with your expectations for its impact on the model (direction, effect size).
    
    
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(huxtable)
californiatod <- read_csv("californiatod.csv")
huxreg(
  lm(houseval ~ transit * railtype + density + I(density^2), data=californiatod)
  )
```

2. Using your own dataset, complete the following in either R or SPSS (or with permission, software of your choice). (If you don't yet have a reasonable dataset that allows you to complete all the steps, consider using the [this dataset of a sample of real estate properties in Portland](taxlot_sample.csv).)

    a. Estimate and report on a regression of your dependent variable on a single numeric indepdent variable. Be sure to include discussion of significance, model fit, and parameter size and reasonableness. Use plain English and examples where possible. You DO NOT need to perform any diagnostics in this step.
    a. Estimate a second model in which you add another numeric variable, and explain the new variable and how it changes your interpretation in a, if it does.
    a. Estimate a third model in which you add a dummy variable, interpret the estimation results of the model;
    a. Do partial F tests on model a, b, and c; What are your hypotheses for these tests and what is your conclusion?
    a. Estimate another model in which you include a nonlinear in variables specification (quadratic, linear-log, log-linear, or log-log). Interpret the new model.
    a. Interpret and compare the four diagnostic plots discussed in lecture. What do you conclude? If any stand out, describe one or two observations that are potential outliers and you might consider removing due to their influence on the regression.
    a. Choose any one of the formal tests from lecture and apply to b & c. What do you conclude?
    a. Finally, choose one additional variable from the remaining variables of your dataset that interests you. State a hypothesis. Test at least 3 specifications (e.g. linear, dummy variable, nonlinear, transformed variable, interaction) with the variable and briefly report on your exercise here (be sure to include regression output, but NOT diagnostics; messy is OK for now). 
    
1. Similar to HW1, Part 3, CHOOSE ONE of the included articles (Both papers available on D2L), and ONE MODEL in the paper that uses dummy variables and nonlinear variables. Summarize, interpret and critique in no more than a few paragraphs. Include an interpretation of the dummy and nonlinear component(s). Be sure to include questions you have and suggestions for what the authors might have done differently in each case.
    a. [Kakar et al. AirBnB price discrimination in San Francisco](https://d2l.pdx.edu/d2l/le/content/667907/viewContent/3159224/View)
    a. [Chen et al. Impact of light rail on property values](https://d2l.pdx.edu/d2l/le/content/667907/viewContent/3159225/View)
