---
title: "STAT 572: Bayesian Statistics" 
subtitle: "Homework 2"
output:
  pdf_document: default
  html_document: default
  html_notebook: default
---

\vspace{1cm}

**(to be submitted online in D2L before October 21st at 5:00 pm)**

\vspace{1cm}

1. If $X_1,\ldots, X_n \sim\text{Bernoulli}(\theta)$, then the distribution of the sum $Z=\sum_{i=1}^n X_i$ has the Binomial$(n,\theta)$ distribution. Show that with $n$ fixed, the Binomial$(n,\theta)$ distributions form a one-parameter exponential family.
2. Consider the family of generating distributions $\left\{\text{Poisson}(\theta): \theta>0\right\}$ for the random sample $Y_1,\ldots,Y_n$ together with the conjugate family of priors $\left\{\text{Gamma}(a,b): a,b>0 \right\}$ for $\theta$.  
  + Verify that the family of posteriors for $\theta|X=x$, can be expressed in the same form as Equation (3) of Section 3 in the \emph{Exponential Families and Conjugacy} class notes. 
  + Show that what is referred to as $t^\star$ in the class notes can be expressed as a convex combination of the ``prior guess'' $t_0$ and the sufficient statistic $t(y)$ that you obtain for this problem.
3. Show that for a certain choice of $t(y)$ and $h(y)$, the Gamma$(a, b)$ distributions are in natural form with natural parameter $\theta = (a, b)^T$.

