---
title: "STAT 572: Bayesian Statistics" 
subtitle: "Homework 6 (Multivariate Normal and Regression)"
output:
  pdf_document: default
  html_document: default
  html_notebook: default
---

\vspace{-0.5cm}
\begin{center}
(to be submitted online in D2L by Wednesday December 4th by noon)
\end{center}

\vspace{1cm}

1. Exercise 7.1 from the Hoff Book (pg 238)



2. Exercise 7.2 from the Hoff Book (pg 238) 


3. Exercise 7.4 from the Hoff Book (pg 239) 

```{r}
#Store the agehw.dat files in the same folder as this Rmd file
Y.marr <- read.table("agehw.dat",sep=" ",header=T)
```
  
4. Exercise 9.1 from the Hoff Book (pg 242) 

```{r}
#Store the agehw.dat files in the same folder as this Rmd file
Ywide.swim <- read.table("swim.dat") #one column per swimmer
Y.swim <- reshape2::melt(Ywide.swim)[,-1]
Y.swim <- cbind(Y.swim, rep(seq(1,12,by=2),each=4), rep(1:4,times=6))
colnames(Y.swim) <- c("time","week","swimmer")

```
  
5. Exercise 9.3 from the Hoff Book (pg 243) 

```{r}
data("UScrime",package="MASS")
namvars <- names(UScrime)
```
  


