---
title: "Homework 2"
author: "Wei Shi"
date: "May 7, 2018"
output: word_document
---

# 1. Kernelized ridge regression
## 1.1 code the kernelized ridge regression for 2d example
```{r, echo=TRUE, message=FALSE, warning=FALSE}
data <- data.frame(matrix(runif(100,min = -10, max=10),nrow = 50, ncol = 2))
data$y <- ifelse(data$X1<=data$X2,1,-1)

library(ggplot2)
ggplot(data = data, aes(x = X1, y = X2, color = as.factor(y))) + 
  geom_point(size = 2) +
  scale_color_manual(values=c("#000000", "#FF0000")) +
  theme(legend.position = "none")

krr_class <- function(new,data){
  N = nrow(data)
  ident.N = diag(rep(1,N))
  lambda <- 1
  K <- matrix(rep(0,N^2),N,N)
   for(i in 1:N){
    for (j in 1:N){
      K[i,j] = kernel(as.matrix(data[i,c(-3)]),data[j,c(-3)])
    }
   }
  # return(K)
  # return(alpha)
  alpha = solve(K+ N*lambda*ident.N ) %*% data$y
  f = sum(alpha%*%kernel(new[1],new[2]))
  return(ifelse(f>=0,1,-1))
}

```


## 1.2 Show 3 examples using 3 different kernels
```{r, echo=TRUE, message=FALSE, warning=FALSE}
# linear
kernel <- function(a,b){return(a %*% t(b))}

krr_class(c(1,3),data)
krr_class(c(1,-1),data)
krr_class(c(-5,8),data)

# polinomial
kernel <- function(a,b){return((a %*% t(b) +1)^2)}

krr_class(c(1,3),data)
krr_class(c(1,-1),data)
krr_class(c(-5,8),data)

# polinomial
kernel <- function(a,b){return((a %*% t(b) +1)^3)}

krr_class(c(1,3),data)
krr_class(c(1,-1),data)
krr_class(c(-5,8),data)
```


# 2. MNIST
## 2.1 Load data
```{r}
rm(list=ls())
library(pROC)
load_mnist <- function() {
  load_image_file <- function(filename) {
    ret = list()
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    ret$n = readBin(f,'integer',n=1,size=4,endian='big')
    nrow = readBin(f,'integer',n=1,size=4,endian='big')
    ncol = readBin(f,'integer',n=1,size=4,endian='big')
    x = readBin(f,'integer',n=ret$n*nrow*ncol,size=1,signed=F)
    ret$x = matrix(x, ncol=nrow*ncol, byrow=T)
    close(f)
    ret
  }
  load_label_file <- function(filename) {
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    n = readBin(f,'integer',n=1,size=4,endian='big')
    y = readBin(f,'integer',n=n,size=1,signed=F)
    close(f)
    y
  }
  train <<- load_image_file('train-images-idx3-ubyte')
  test <<- load_image_file('t10k-images-idx3-ubyte')
  
  train$y <<- load_label_file('train-labels-idx1-ubyte')
  test$y <<- load_label_file('t10k-labels-idx1-ubyte')  
}


show_digit <- function(arr784, col=gray(128:1/128), ...) {
  image(matrix(arr784, nrow=28)[,28:1], col=col, ...)
}

load_mnist()
```

## 2.2 Run kernelized ridge regression for the digit zero versus all the other ones.
```{r}
# train data using Guassian
train_krr <- list(x=train$x[1:1000,1:748],y=train$y[1:1000])
train_krr$class <- ifelse(train_krr$y==0,1,0)

ptm <- proc.time()

N <- nrow(train_krr$x)
kk <- tcrossprod(train_krr$x)
dd <- diag(kk)
ident.N <- diag(rep(1,N))

Gau.kernel <- exp((-matrix(dd,N,N)-t(matrix(dd,N,N))+2*kk))

alphas <- solve(Gau.kernel + .0001*N*ident.N) %*% train_krr$class
f <- Gau.kernel %*% alphas

proc.time() - ptm

# test accuracy
test_krr <- list(x=test$x[1:1000,1:748],y=train$y[1:1000])

ptm <- proc.time()

N <- nrow(test_krr$x)
kk <- tcrossprod(test_krr$x)
dd <- diag(kk)
ident.N <- diag(rep(1,N))
RBF.kernel <- exp((-matrix(dd,N,N)-t(matrix(dd,N,N))+2*kk))
f <- RBF.kernel %*% alphas
y <- ifelse(test_krr$y==0,1,0)

proc.time() - ptm

performance <- data.frame(cbind(f,y))
Performance <- ifelse((performance$V1 - performance$y)==0, "Right", "Wrong")
table(Performance)

```

