---
title: 'STAT311 Notes'
author: ""
date: ""
output: html_document
---

#  {.tabset .tabset-fade .tabset-pills}

Introduction to Mathematical Analysis

1. TOOLS FOR ANALYSIS
 1.1 BASIC CONCEPTS OF SET THEORY
 1.2 FUNCTIONS
 1.3 THE NATURAL NUMBERS AND MATHEMATICAL INDUCTION
 1.4 ORDERED FIELD AXIOMS
 1.5 THE COMPLETENESS AXIOM FOR THE REAL NUMBERS
 1.6 APPLICATIONS OF THE COMPLETENESS AXIOM
 
2. SEQUENCES
 2.1 CONVERGENCE
 2.2 LIMIT THEOREMS
 2.3 MONOTONE SEQUENCES
 2.4 THE BOLZANO-WEIERSTRASS THEOREM
 2.5 LIMIT SUPERIOR AND LIMIT INFERIOR
 2.6 OPEN SETS, CLOSED SETS, COMPACT SETS, AND LIMIT POINTS
 
3. LIMITS AND CONTINUITY
 3.1 LIMITS OF FUNCTIONS
 3.2 LIMIT THEOREMS
 3.3 CONTINUITY
 3.4 PROPERTIES OF CONTINUOUS FUNCTIONS
 3.5 UNIFORM CONTINUITY
 3.6 LIMIT SUPERIOR AND LIMIT INFERIOR OF FUNCTIONS
 3.7 LOWER SEMICONTINUITY AND UPPER SEMICONTINUITY
 
4. DIFFERENTIATION
 4.1 DEFINITION AND BASIC PROPERTIES OF THE DERIVATIVE
 4.2 THE MEAN VALUE THEOREM
 4.3 SOME APPLICATIONS OF THE MEAN VALUE THEOREM
 4.4 L’HOSPITAL’S RULE
 4.5 TAYLOR’S THEOREM
 4.6 CONVEX FUNCTIONS AND DERIVATIVES
 4.7 NONDIFFERENTIABLE CONVEX FUNCTIONS AND SUBDIFFERENTIALS

