---
title: 'STAT551 Notes'
author: ""
date: "Fall 2018"
output: html_document
---

Applied Statistics for Engineers and Scientists

#  {.tabset .tabset-fade .tabset-pills}

## 1. Basic Statistical Concepts

### 1.2 Populations and Samples

In statistics the word population is used to denote the set of all objects or subjects relevant to the particular study that are exposed to the same treatment or method.
The members of a population are called population units.

Sampling refers to the process of selecting a number of population units and recording their characteristic(s).

### 1.6 Proportions, Averages, and Variances

#### 1.6.1 Population Proportion and Sample Proportion

The sample proportion $\hat p$ approximates but is, in general, different from
the population proportion p.

#### 1.6.2 Population Average and Sample Average

**Definition** the population average or population mean, denoted by μ, is simply the arithmetic average of all numerical values in the statistical population.

$$μ=\frac1N\sum_{i=1}^N\nu_i$$

**Definition** If the random variable X denotes the value of the variable of a randomly selected population unit, then a synonymous term for the population mean is expected value of X, or mean value of X, and is denoted by $μ_X$ or E(X).

**Definition** If a sample of size n is randomly selected from the population, and if $x_1,x_2,..,x_n$ denote the variable values corresponding to the sample units (note that a different symbol is used to denote the sample values), then the sample average or sample mean is simply 

$$\bar x=\frac1n\sum_{i=1}^nx_i$$

> The sample mean x approximates but is, in general, different from the population mean μ.

> A proportion is a special case of mean.

#### 1.6.3 Population Variance and Sample Variance

The population variance and standard deviation offer a quantification of the intrinsic variability of the population.

**Definition** of Population Variance $σ^2$, the variance of the random variable X, $σ^2_X$, or $Var(X)$.

$$\sigma^2=\frac1N\sum_{i=1}^N(\nu_i-\mu)^2=\frac1N\sum_{i=1}^N\nu_i^2-\mu^2$$

**Definition** The positive square root of the population variance is called the population standard deviation and is denoted by $σ$.

**Definition** If a sample of size n is randomly selected from the population, and if $x_1,x_2,..,x_n$ denote the variable values corresponding to the sample units, then the sample variance is

$$S^2=\frac1{n-1}\sum_{i=1}^n(x_i-\bar x)^2=\frac1{n-1}\left[\sum_{i=1}^nx_i^2-\frac1n(\sum_{i=1}^nx_i)^2\right]$$

> $S^2$ and $S$ approximate but are, in general, different from $σ^2$ and $σ$.

**Definition** the statistical parlance of degrees of freedom: Because the definition of $S^2$ involves the deviations of each observation from the sample mean, that is, $x_1−\bar x, x_2−\bar x,.., x_n−\bar x$, and because these deviations sum to zero, that is,
$$\sum_{i=1}^n(x_i-\bar x)=0$$
there are n−1 degrees of freedom, or independent quantities (deviations) that determine $S^2$. 

### 1.7 Medians, Percentiles, and Boxplots

**Definition** The 50th sample percentile is also called the sample median and is denoted by $\tilde x$; it is the value that separates the upper or largest 50% from the lower or smallest 50% of the data. The 25th, the 50th, and the 75th sample percentiles are also called sample quartiles, as they divide the sample into roughly four equal parts. We also refer to the 25th and the 75th sample percentiles as the lower sample quartile ($q_1$) and upper sample quartile ($q_3$),

**Definition 1.7-1** The sample interquartile range, or sample IQR, defined as
$IQR = q_3 − q_1$ is an estimator of the population IQR, which is a measure of variability.

**Definition 1.7-2** Let $x_{(1)}, x_{(2)},.., x_{(n)}$ denote the ordered sample values in a sample of size n. Then $x_{(i)}$, the $i$th smallest sample value, is taken to be the $100(\frac{i−0.5}n)$-th sample percentile. Sample percentiles estimate the corresponding population percentiles.

**Definition 1.7-3** Let $x_{(1)}, x_{(2)},.., x_{(n)}$ denote the order statistics. Then

1. The sample median is defined as
$$\tilde x=\begin{cases}x_{(\frac{n+1}2)} &\text{, if n is odd}\\\frac{x_{(\frac{n}2)}+x_{(\frac{n}2+1)}}2 &\text{, if n is even}\end{cases}$$

2. The sample lower quartile is defined as

q1 = Median of smaller half of the data values

where, if n is even the smaller half of the values consists of the smallest n/2 values, and if n is odd the smaller half consists of the smallest (n + 1)/2 values. Similarly, the sample upper quartile is defined as

q3 = Median of larger half of the data values

where, if n is even the larger half of the values consists of the largest n/2 values, and if n is odd the larger half consists of the largest (n+1)/2 values.

### 1.8 Comparative Studies

#### 1.8.3 Causation: Experiments and Observational Studies

Sample Effect of Level i in a One-Factor Design $\widehatα_i =\bar x_i −\bar x$

 - the sample effects estimate the k population effects $α_i =\mu_i −\mu$ where $\mu=\frac1k\sum_{i=1}^k\mu_i$

#### 1.8.4 Factorial Experiments: Main Effects and Interactions

**Definition 1.8-1** When a change in the level of factor A has different effects on the levels of factor B we say that there is interaction between the two factors. The absence of interaction is called additivity.

 - Main Row and Column Effects $α_i=μ_{i·}−\bar μ_{··}$, $β_j =\bar μ_{·j} −\bar μ_{··}$

Under additivity, the cell means μij are given in terms of their overall average, $μ_{··}$ and the main row and column effects in an additive manner:

 - Cell Means under Additivity $μ_{ij}=\bar μ_{··}+α_i+β_j$

When there is interaction between the two factors, the cell means are not given
by the additive relation (1.8.5). The discrepancy/difference between the left and
right-hand sides of this relation quantifies the interaction effects:

 - Interaction Effects $γ_{ij}=μ_{ij}−(\barμ_{··}+α_i+β_j)$

 - Sample Mean of Observations in Cell (i,j)
 
$$\bar x_{ij}=\frac1{n_{ij}}\sum_{k=1}^{n_{ij}}x_{ijk}$$

 - Sample Main Row and Column Effects $\widehatα_i=x_{i·}−\bar x_{··}$, $β_j =\bar x_{·j} −\bar x_{··}$

 - Sample Interaction Effects $\widehatγ_{ij} =x_{ij}−(\bar x_{··}+\widehatα_i+\widehatβ_j)$

## 2. Introduction to Probability

### 2.2 Sample Spaces, Events, and Set Operations

**Definition 2.2-1** The set of all possible outcomes of an experiment is called the sample space of the experiment and will be denoted by $S$.

Such subsets of the sample space (i.e., collections of individual outcomes) are called events. An event consisting of only one outcome is called a simple event. Events consisting of more than one outcome are called compound.

## 3. Random Variables and Their Distributions
## 4. Jointly Distributed Random Variables
## 5. Some Approximation Results
## 7.1 Introduction to Confidence Intervals

